fix #11583 #11443
ant-design/ant-design pull request #11601
Opened 2018-08-03 12:51 UTC by jljsj33

#11583 
#11443

2018-08-03 14:59 UTC, afc163 commented
ci

2018-08-06 00:31 UTC, chenshuai2144 commented
ie11也跑不起来了，

ie 系列全挂了

2018-08-06 12:34 UTC, jljsj33 commented
@chenshuai2144 你老板喊你干活了。。。

2018-08-07 05:28 UTC, afc163 requested changes
分成两个 PR，一个修复 bug 发到 master，一个新增特性发到 feature-3.9.0。

2018-08-07 14:04 UTC, chenshuai2144 commented
周五搞

2018-08-07 14:32 UTC, closed without merging