feature: Added Hebrew translations
ant-design/ant-design pull request #12463
Opened 2018-09-28 22:06 UTC by orenk86

Notice that rc-pagination and rc-calendar still use the en_US locale.
I've submitted pull requests to both libraries with Hebrew translations, they were already merged, but haven't been included in a release yet.
You can see them [here](https://github.com/react-component/calendar/pull/416) and [here](https://github.com/react-component/pagination/pull/146).

Once they will be released, I'll update this PR, or submit a new one.

2018-09-30 14:31 UTC, orenk86 commented
Okay, rc-calendar and rc-pagination libraries have been updated and everything seems okay. This PR is ready as far as I'm concerned 😊

2018-10-03 17:03 UTC, orenk86 commented
Worth mentioning that the failing tests seem unrelated to this PR. They also fail locally for me, with the same errors.
When I run `npm test -- -u` the snapshots get updated and all of the tests pass locally for me.

Should I include an update for the snapshots in this PR? Seems a bit unrelated.
Perhaps it would be better to open another one...

2018-10-10 05:55 UTC, zombieJ requested changes

2018-10-10 05:55 UTC, zombieJ commented on docs/react/i18n.en-US.md
> +|Hebrew|he_IL|
Pls order with `Filename` field.

2018-10-11 06:54 UTC, merged

2018-11-20 22:48 UTC, orenk86 commented
@afc163 @zombieJ May I ask when this will be included in a release? Thanks!