Cascader support limit filtered item count
ant-design/ant-design pull request #13206
Opened 2018-11-20 05:24 UTC by zombieJ

Add `limit` prop in `showSearch`. Default value: 50:
```jsx
<Cascader
  {...props}
  showSearch={{ limit: 30 }}
/>
```

ref: #13097

2018-11-20 05:56 UTC, JLHwung requested changes

2018-11-20 05:56 UTC, JLHwung commented on components/cascader/index.tsx
> +const defaultLimit = 50;
Please document this variable in comments as it is too far from lines where it is used.

2018-11-20 05:56 UTC, JLHwung commented on components/cascader/index.tsx
> +      filtered = flattenOptions.filter((path) => filter(this.state.inputValue, path, names));
As `limit` is backed by a default value, a user can only specify
```
<Cascader showSearch={{ filter, limit: -1 }} />
```
to go into this branch.

I suggest just cap the `limit` to be non-negative and remove this branch.

2018-11-20 06:02 UTC, JLHwung commented
I can tell from the implementation details that this change is actually a breaking change. The following code
```
<Cascader
  {...props}
/>
```
will now have at most 50 filtered item unless they modify their code and specify that
```
<Cascader
  {...props}
  showSearch={{ limit: Infinity }}
/>
```

It is a good idea to add default limit to `Cascader`. I hope that the limit itself is configurable in a project level, so people can opt in to the new behaviour without breaking other's code.

2018-11-20 06:20 UTC, JLHwung commented on components/cascader/index.en-US.md
> +| limit | Set the count of filtered items | boolean | 50 |
Shouldn't it be of the type `number`? 🤔

2018-11-26 03:18 UTC, afc163 approved these changes

2018-11-26 03:20 UTC, JLHwung approved these changes

2018-11-26 03:29 UTC, merged