new components  PageHeader
ant-design/ant-design pull request #13637
Opened 2018-12-15 04:44 UTC by chenshuai2144

页头用来声明页面的主题，包含了用户所关注的最重要的信息，使用户可以快速理解当前页面是什么以及它的功能。

## API

| 参数      | 说明                                      | 类型         | 默认值 |
|----------|------------------------------------------|-------------|-------|
| title | title 区域 | ReactNode | - |
| tags | title 旁的 tag 列表 | [Tag](https://ant.design/components/tag-cn/)[] | - |
| action | 操作区，位于 title 行的行尾 | ReactNode | - |
| logo | logo区域 | ReactNode | - |
| content | 内容区 | ReactNode | - |
| extraContent | 额外内容区，位于content的右侧 | ReactNode | - |
| breadcrumb | 面包屑的配置 |  [breadcrumb](https://ant.design/components/breadcrumb-cn/)  | - |
| tabBars | tab 页面导航列表 | array<{key: string, tab: ReactNode}> | -  |
| tabsProps | tabs 的配置 | 同[Tab](https://ant.design/components/tabs-cn/#Tabs) | -  |
| onBack | 返回按钮的点击事件 | ()=>void | - |

2018-12-15 04:45 UTC, chenshuai2144 commented
![image](https://user-images.githubusercontent.com/8186664/50039101-445ba900-0067-11e9-86cb-599f41170d38.png)

2018-12-17 01:37 UTC, zombieJ commented
* add `subTitle`
* remove `logo`, keep `extraContent`
* `content` -> `children`
* `Breadcrumb` or `Tabs`：`breadcrumb={<Breadcrumb>{...}</Breadcrumb>}`? 感觉也不太好

或者 `action` 和 `tabs` 移到 `renderFooter` 里让用户自己搞算了。否则下面这个看着有点蛋疼。

@chenshuai2144 @afc163

2018-12-17 04:01 UTC, yutingzhao1991 commented
问一个问题，这个不做在 ant-design-pro 里面？我们按照什么标准来划定一个组件是在 antd 还是再 ant-design-pro 里面呢？

2018-12-17 04:15 UTC, chenshuai2144 commented
扭头问一下你左边的男人

2018-12-18 03:59 UTC, afc163 commented
extraContent 去掉好了，感觉用的很少。

2018-12-18 04:06 UTC, chenshuai2144 commented
extraContent 还是很有用的。这两种如果有extraContent 实现起来很容易
![image](https://user-images.githubusercontent.com/8186664/50131492-4cad2180-02bd-11e9-89bf-de4e6e89efb8.png)

2018-12-18 04:08 UTC, chenshuai2144 commented on components/page-header/index.en-US.md
> +| extraContent | Extra content area, on the right side of content | ReactNode | - |
action 感觉还不错，extraContent的确感觉有点扯。
不如叫 rightContent 和 leftContent 吧

2018-12-18 08:36 UTC, zombieJ commented
Card 里右上角叫 extra，这边也这么叫吧。叫 action 又要多记一个。

2018-12-18 08:38 UTC, zombieJ commented
extraContent 或者让用户自己用 Flex 去实现？

2018-12-21 03:49 UTC, afc163 commented on components/page-header/demo/basic.md
> +import { PageHeader } from "antd";
应该是单引号。

2018-12-26 03:00 UTC, afc163 commented on components/page-header/index.tsx
> +    return this.renderBack(prefixCls);
renderBack 可以不出现么？感觉很多场景不需要返回。

2018-12-27 15:35 UTC, zombieJ commented
Codacy 就差一口气啦 😄

2018-12-27 15:42 UTC, afc163 commented
一个个能不能早点睡！

2018-12-27 16:06 UTC, zombieJ commented
Synced with @chenshuai2144 :
* tag 的例子删掉
* 图片的例子也可以删了，或者把左边文字加多一点。不要用 margin-top: -40px，太黑了。
* “解释一下标题” -> “这是一个附属标题”

2018-12-28 02:39 UTC, chenshuai2144 commented
![image](https://user-images.githubusercontent.com/8186664/50500524-df537a80-0a8c-11e9-8538-e09de79ef767.png)

2018-12-28 08:24 UTC, zombieJ submitted a review, later dismissed

2018-12-29 00:32 UTC, ybning commented
@chenshuai2144 PageHeader移到antd，在antd-pro，PageHeader还保留吗？

2018-12-29 02:06 UTC, chenshuai2144 commented
@ybning pro 中 pr 比较少，可能做一个封装继续使用

2018-12-29 06:56 UTC, yesmeck commented on components/page-header/demo/content.md
> +    <p>Ant Design 将色彩体系解读成两个层面：系统级色彩体系和产品级色彩体系。</p>
例子里要写英文吧

2018-12-29 06:57 UTC, yesmeck commented on components/page-header/index.tsx
> +  onBack: (e: React.MouseEvent<HTMLElement>) => void;
有部分属性应该是可选的。

2018-12-29 07:01 UTC, yesmeck commented on components/page-header/index.tsx
> +  tags: Tag[] | Tag;
这个类型不对。

我不传 `<Tag />`，传别的可以吗？

2018-12-29 07:03 UTC, yesmeck commented on components/page-header/index.zh-CN.md
> +| backNode | 自定义 back icon ，如果为 false 不渲染 back icon | ReactNode | `<Icon type="arrow-left" />` |
`backNode` 这个名字换成 `backIcon` 是不是好点？

2018-12-29 07:03 UTC, yesmeck commented on components/page-header/index.zh-CN.md
> +| onBack | 返回按钮的点击事件 | ()=>void | - |
`() => void`

2018-12-29 07:04 UTC, yesmeck commented on components/page-header/__tests__/index.test.js
> +        breadcrumbName: '一级菜单',
测试里也可以改成英文

2018-12-29 07:05 UTC, yesmeck commented on components/page-header/demo/actions.md
> +.content.padding {
demo 的样式最好加个前缀，现在这个样式是全局的。

2018-12-29 07:08 UTC, yesmeck commented on components/page-header/demo/actions.md
> +.content.padding {
bisheng 会自动加一个 `#components-page-header-demo-actions` 这样的 id 的。

2018-12-29 07:09 UTC, yesmeck commented on components/page-header/index.tsx
> +  onBack: (e: React.MouseEvent<HTMLElement>) => void;
文档里的 `onBack` 是没参数的。

2018-12-29 07:10 UTC, chenshuai2144 commented on components/page-header/index.tsx
> +  tags: Tag[] | Tag;
希望是一个 tag，如果是别的样式会出问题

2018-12-29 07:11 UTC, ztplz approved these changes

2018-12-29 07:11 UTC, ztplz commented on components/page-header/index.en-US.md
>  | backNode | Custom back icon, if false does not render back icon | ReactNode | `<Icon type="arrow-left" />` |
`if false the back icon will not be displayed`

2018-12-29 07:11 UTC, yesmeck commented on components/page-header/style/index.less
> +@pageheader-prefix-cls: ~'@{ant-prefix}-pageheader';
不是 `ant-page-header`吗？

2018-12-29 07:12 UTC, chenshuai2144 commented on components/page-header/index.tsx
> +  onBack: (e: React.MouseEvent<HTMLElement>) => void;
我用了partial

2018-12-29 07:12 UTC, yesmeck commented on components/page-header/__tests__/index.test.js
> +    expect(wrapper.find('.ant-pageheader-back-icon')).not.toHaveLength(1);
`toHaveLength(0)`

2018-12-29 07:12 UTC, ztplz submitted a review, later dismissed

2018-12-29 07:12 UTC, ztplz commented on components/page-header/index.en-US.md
> +| tabsProps | tabs configuration | 同[Tab](https://ant.design/components/tabs-cn/#Tabs) | -  |
`同`?

2018-12-29 07:12 UTC, chenshuai2144 commented on components/page-header/style/index.less
> +@pageheader-prefix-cls: ~'@{ant-prefix}-pageheader';
组件名叫pageheader。。

2018-12-29 07:15 UTC, chenshuai2144 commented on components/page-header/index.zh-CN.md
> +| backNode | 自定义 back icon ，如果为 false 不渲染 back icon | ReactNode | `<Icon type="arrow-left" />` |
backNode 我想表达可以放一个 react node,不只是一个 icon

2018-12-29 07:17 UTC, yesmeck commented on components/page-header/index.tsx
> +  onBack: (e: React.MouseEvent<HTMLElement>) => void;
别这样用，`PageHeaderProps` 既然 export 出去了，也要像 API 一样对待。

2018-12-29 07:30 UTC, afc163 commented on components/page-header/style/index.less
> +@pageheader-prefix-cls: ~'@{ant-prefix}-pageheader';
page-header is right

2018-12-29 11:43 UTC, HsuanXyz commented on components/page-header/demo/breadcrumb.md
> +  en-US: Breadcrumb Page Header
文档中几处英文标题和描述缺少翻译，并且 `带面包屑页头` 的例子出现了2次

2018-12-29 11:44 UTC, HsuanXyz commented on components/__tests__/__snapshots__/index.test.js.snap
> +  "PageHeader",
这里应该按照字母排序

2018-12-29 11:52 UTC, HsuanXyz commented on components/page-header/index.tsx
> +          window.history.back();
`onBack ` 的默认行为是否因该放在 `defaultProps` 中？

2018-12-29 15:07 UTC, afc163 commented on components/page-header/index.tsx
> +          window.history.back();
不要加 `window.history.back()`，点击的行为和指向应该交由业务方自行决定。

支持 onBack 或者指定这个图标的 link。

2018-12-29 23:56 UTC, chenshuai2144 commented on components/page-header/index.tsx
> +          window.history.back();
现在是有 onBack 的，这个默认行为我在写一些业务的时候很好用，就是返回上一页。

2018-12-30 05:17 UTC, afc163 commented on components/page-header/index.zh-CN.md
> +| backNode | 自定义 back icon ，如果为 false 不渲染 back icon | ReactNode | `<Icon type="arrow-left" />` |
就叫 backIcon 好了

2018-12-30 05:18 UTC, afc163 commented on components/page-header/index.tsx
> +          window.history.back();
还需要能指定 link，否则 hover 没链接。

2018-12-30 05:18 UTC, afc163 commented on components/page-header/index.zh-CN.md
> +| backNode | 自定义 back icon ，如果为 false 不渲染 back icon | ReactNode | `<Icon type="arrow-left" />` |
默认改为 false 吧，Pro 里默认都没用到的

2019-01-02 15:00 UTC, chenshuai2144 commented on components/page-header/index.tsx
> +          window.history.back();
backIcon能解决这个问题的

2019-01-02 15:26 UTC, ztplz submitted a review, later dismissed

2019-01-02 21:51 UTC, davidpanzarella commented on components/page-header/style/index.less
> +    line-height: 16px;
Line-height should always be unitless. I've noticed that throughout Ant, these are typically containing a unit based value, which cause all sorts of problems to children within elements that have parents' line-heights set to a unit based value.

2019-01-03 02:49 UTC, hsuanxyz requested changes

2019-01-03 02:49 UTC, HsuanXyz commented on components/page-header/index.en-US.md
> +subtitle: PageHeader
英文文档应该没有 subtitle。
![image](https://user-images.githubusercontent.com/22736418/50622029-35209a80-0f45-11e9-8882-d6eb70a7655d.png)

2019-01-03 03:10 UTC, afc163 commented on components/page-header/demo/actions.md
> +    <Description term="单据备注">浙江省杭州市西湖区工专路</Description>
Demo 需要使用英文来写。

2019-01-03 03:11 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
自定义样式太多了，想办法精简一下。

2019-01-03 03:13 UTC, chenshuai2144 commented on components/page-header/demo/actions.md
> +    <Description term="单据备注">浙江省杭州市西湖区工专路</Description>
英文排版会很蛋疼

2019-01-03 03:14 UTC, afc163 commented on components/page-header/demo/actions.md
> +    <Description term="单据备注">浙江省杭州市西湖区工专路</Description>
那说明我们的设计有问题...

2019-01-03 03:16 UTC, chenshuai2144 commented on components/page-header/demo/actions.md
> +}
这个组件最复杂的就是这个样式，这个东西应该是用户自己写的
我们提供了一个方案，如果写在组件的里面就变成原来的PageHeader了
密密麻麻的api

2019-01-03 03:17 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
我们的自定义 css 里面要想办法前缀的展示去掉，不然很多人会直接复制过去用。

2019-01-03 03:19 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
这两段样式是重复的。

2019-01-03 03:20 UTC, afc163 commented on components/page-header/index.tsx
> +              {this.props.children && (
children 应该解构出来。

2019-01-03 03:20 UTC, afc163 commented on components/page-header/index.tsx
> +          const { prefixCls: customizePrefixCls, style, footer } = this.props;
定义应该写到 render 下面。

2019-01-03 03:21 UTC, afc163 commented on components/page-header/style/index.less
> +    padding: 20px 32px;
&-have-footer

2019-01-03 03:22 UTC, afc163 commented on components/page-header/style/index.less
> +  .@{pageheader-prefix-cls}-back-icon {
&-back-icon

底下很多样式也是类似的。

2019-01-03 03:22 UTC, afc163 commented on components/page-header/style/index.tsx
> +import './index.less';
要写其他模块的样式依赖，不然会丢。参考 Table 的写法。

2019-01-03 05:56 UTC, chenshuai2144 commented on components/page-header/style/index.less
> +      line-height: 24px;
1或者1.2这样的？

2019-01-04 09:07 UTC, yesmeck commented on components/page-header/index.tsx
> +class PageHeader extends React.PureComponent<PageHeaderProps, {}> {
不要用 `PureComponent`, 这不是一个 pure component，让用户自己去优化。

2019-01-04 09:59 UTC, zombieJ commented on components/page-header/index.tsx
> +class PageHeader extends React.PureComponent<PageHeaderProps, {}> {
没有 state，直接 SFC？

2019-01-04 10:07 UTC, afc163 commented on components/page-header/index.tsx
> +class PageHeader extends React.PureComponent<PageHeaderProps, {}> {
直接 SFC 。

2019-01-09 03:01 UTC, tangjinzhou commented
> 问一个问题，这个不做在 ant-design-pro 里面？我们按照什么标准来划定一个组件是在 antd 还是再 ant-design-pro 里面呢？

@yutingzhao1991 左边男人怎么说，同有这个疑惑？

不仅仅PageHeader，Comment我都感觉过于业务了，当然我的感觉并没有一个量化的标准

克制克制克制！！！

cc @afc163

2019-01-09 03:20 UTC, afc163 commented
> > 问一个问题，这个不做在 ant-design-pro 里面？我们按照什么标准来划定一个组件是在 antd 还是再 ant-design-pro 里面呢？
> 
> @yutingzhao1991 左边男人怎么说，同有这个疑惑？
> 
> 不仅仅PageHeader，Comment我都感觉过于业务了，当然我的感觉并没有一个量化的标准
> 
> 克制克制克制！！！
> 
> cc @afc163

这是设计价值观的问题了。Ant Design 究竟是啥，她要负责的范畴是什么？

从三年前开始，Ant Design 一直对标的是 bootstrap，旨在提供中后台 PC 应用的原子组件，一些复杂和上层业务组件都交由业务线或者业务组件库完成。随着自身业务和社区实践，我们发现，作为中后台应用研发解决方案，antd 有很多问题其实不能解决，例如之前的评论组件，很多人一直在要的富文本编辑器，布局框架，图表卡片，结果，页头页尾等等。在我们设计师的实践中，这些部分也一直在不同的业务上不断造轮子，业务的实现五花八门良莠不齐，因此我们才有了 Ant Design Pro 这样的整套解决方案。

Ant Design Pro 的问题有两个，一是臃肿（这个会在 umi block 和未来的 v4 版本中解决），二是业务组件的开发方式/用户量/范畴都处在一个更加尴尬的状态。因此我们有了这一步：把 pro 中的通用业务组件进一步提炼到 antd 中，pro 接下来只会有一个简洁纯粹的布局脚手架和一系列可组装的页面区块。而 antd 会继续之前的使命，解决长久以来用 antd 搭不出完整中台应用的尴尬，真正成为一个中后台应用研发的基础场景的材料提供者（至少对我们自有业务的基础场景要能尽量覆盖）。

在这个过程中，我们会逐步提炼通用的所谓『业务』组件（PageHeader、Comment、Statictis、Result、Empty 等等）到 antd 中，同时也会**异常重视**这些组件的通用性（属性精简/场景泛化）。antd 仍然会是一个通用 UI 解决方案。

2019-01-10 09:11 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
还是没改。。。

2019-01-10 09:12 UTC, afc163 commented on components/page-header/demo/content.md
> +];
是不是直接挖个坑，把 Breadcrumb 组件拿过来直接用。

2019-01-10 09:13 UTC, afc163 commented on components/page-header/demo/content.md
> +Breadcrumb Page Header
注意标点符号。

2019-01-10 09:14 UTC, afc163 commented on components/page-header/index.en-US.md
> +Use when you need the user to quickly understand what the current page is and what its features are.
这两段可以找海纳再补充一下。

2019-01-10 09:15 UTC, afc163 commented on components/page-header/index.tsx
> +          return;
return 多余

2019-01-10 09:15 UTC, afc163 commented on components/page-header/index.zh-CN.md
> +| subTitle | subTitle 文字 | ReactNode | - |
说明要写有意义的中文

2019-01-10 09:16 UTC, afc163 commented on components/page-header/style/index.less
> +    display: inline-block;
要有 hover  效果和  transition

2019-01-10 09:42 UTC, chenshuai2144 commented on components/page-header/demo/actions.md
> +}
demo里面也需要修改吗?

2019-01-10 13:52 UTC, afc163 commented on components/page-header/demo/breadcrumb.md
> +带面包屑页头
1. 标点。
2. 这些描述和标题一样都太性冷淡了，自己加工加工。

2019-01-14 07:39 UTC, afc163 commented on components/page-header/demo/basic.md
> +标准页头，适合使用在需要简单描述的场景
标点符号

2019-01-14 07:44 UTC, afc163 commented on components/page-header/__tests__/index.test.js
> +  it('pageHeader should contain back it back', async () => {
目测用例都不需要 async。

2019-01-15 07:17 UTC, Akatsukikikiki commented
- 有几处间距，以及 icon 的尺寸需要调整下：
<img width="712" alt="2019-01-15 3 05 30" src="https://user-images.githubusercontent.com/33214700/51164547-386a3d80-18d8-11e9-9c1d-9da6b45565df.png">

<img width="948" alt="2019-01-15 3 12 59" src="https://user-images.githubusercontent.com/33214700/51164559-46b85980-18d8-11e9-840f-ba0fd61c053b.png">

- 简介少了句号：
<img width="890" alt="2019-01-15 3 15 34" src="https://user-images.githubusercontent.com/33214700/51164607-75363480-18d8-11e9-9a39-f3e81ff35916.png">

2019-01-15 07:30 UTC, Akatsukikikiki commented
padding 没有把 button 包进去：

<img width="916" alt="2019-01-15 3 28 42" src="https://user-images.githubusercontent.com/33214700/51165206-6c466280-18da-11e9-8be6-f9888b243603.png">

<img width="895" alt="2019-01-15 3 28 49" src="https://user-images.githubusercontent.com/33214700/51165214-6fd9e980-18da-11e9-98fe-35518e31e577.png">

2019-02-19 07:00 UTC, zombieJ commented on components/page-header/style/index.tsx
> +import '../../breadcrumb/style';
加个 typography 的 style

2019-02-19 07:54 UTC, zombieJ submitted a review, later dismissed

2019-02-19 07:57 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
这些 css 多余了吧。

2019-02-19 08:03 UTC, afc163 commented on components/page-header/demo/actions.md
> +}
Description 直接用新的 Descriptions 吧，这里代码好冗余。

2019-02-19 08:04 UTC, chenshuai2144 commented on components/page-header/demo/actions.md
> +}
我想的是先把他弄出去，众测一波，不知道api 设计的合不合理

2019-02-19 08:06 UTC, afc163 commented
预览链接在哪里。

2019-02-19 08:19 UTC, ztplz approved these changes

2019-02-19 08:22 UTC, chenshuai2144 commented
# preview link

https://5c6bb981452bb3000cc7c50e--ant-design.netlify.com/

2019-02-28 14:18 UTC, zombieJ commented
CI 修一下，准备合了

2019-03-02 07:51 UTC, merged