feat: Dropdown support set right icon
ant-design/ant-design pull request #15996
Opened 2019-04-10 09:11 UTC by DiamondYuan

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

### 💡 Solution

### 📝 Changelog

- English Changelog:
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2019-04-10 09:13 UTC, DiamondYuan commented
demo 有 __snapshots__ 测试了。

2019-04-10 09:16 UTC, afc163 commented on components/dropdown/demo/dropdown-button.md
> +可以设置 icon 属性 来修改右边的 icon
```suggestion
可设置 `icon` 属性来修改右边的图标。
```

2019-04-10 09:17 UTC, afc163 commented on components/dropdown/index.zh-CN.md
> +| 参数 | 说明 | 类型 | 默认值 |版本|
版本前后少空格。

2019-04-10 09:17 UTC, afc163 commented on components/dropdown/index.zh-CN.md
> +| icon | 右侧的 icon | ReactNode | - |3.17.0|
3.17.0 前后少空格。

2019-04-10 14:06 UTC, afc163 commented on components/dropdown/demo/dropdown-button.md
> +    <Dropdown.Button onClick={handleButtonClick} overlay={menu} disabled style={{ marginLeft: 8 }}>
换行比较好，不然太长了。

2019-04-10 14:20 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +    <Dropdown.Button onClick={handleButtonClick} overlay={menu} disabled style={{ marginLeft: 8 }}>
我运行 npm run lint-fix:demo 怎么改了这么多文件


![image](https://user-images.githubusercontent.com/9692408/55886714-da02e180-5bde-11e9-89da-1c372f83532d.png)

2019-04-10 14:25 UTC, afc163 commented on components/dropdown/demo/dropdown-button.md
> +    <Dropdown.Button onClick={handleButtonClick} overlay={menu} disabled style={{ marginLeft: 8 }}>
估计这个 lint 有点问题，我空了排查一下。

2019-04-11 04:12 UTC, zombieJ commented on components/dropdown/demo/dropdown-button.md
> +      style={{ marginLeft: 8 }}
统一搞个 demo 样式吧，现在切行了有点丑：
<img width="450" alt="屏幕快照 2019-04-11 下午12 12 07" src="https://user-images.githubusercontent.com/5378891/55930247-0ce6bd00-5c53-11e9-9f7e-b098293503f1.png">

2019-04-11 04:12 UTC, zombieJ commented on components/dropdown/demo/sub-menu.md
> +const {SubMenu} = Menu;
```diff
- const {SubMenu} = Menu;
+ const { SubMenu } = Menu;
```

2019-04-11 04:21 UTC, afc163 commented on components/dropdown/demo/sub-menu.md
> +const {SubMenu} = Menu;
lint 没生效？

2019-04-11 06:19 UTC, zombieJ commented on components/dropdown/demo/sub-menu.md
> +const {SubMenu} = Menu;
看了一下，我们的 tslint 里没设置 object-curly-spacing 这个 rule。

2019-04-11 06:37 UTC, afc163 commented on components/dropdown/demo/sub-menu.md
> +const {SubMenu} = Menu;
加上吧

2019-04-11 06:50 UTC, zombieJ commented on components/dropdown/demo/sub-menu.md
> +const {SubMenu} = Menu;
Patched in `antd-tools@7.3.1`

2019-04-11 10:08 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +      style={{ marginLeft: 8 }}
![image](https://user-images.githubusercontent.com/9692408/55949245-c1e59d80-5c84-11e9-8aaa-fa5a0f2fb8a6.png)


没有切行，是因为我用了 15 寸的电脑么。

2019-04-11 12:34 UTC, afc163 commented on components/dropdown/demo/dropdown-button.md
> +      style={{ marginLeft: 8 }}
请考虑浏览器宽度变小的情况。

2019-04-12 02:47 UTC, afc163 commented
oops

2019-04-12 03:33 UTC, DiamondYuan commented
> oops

忘记重新 install 了 😳

2019-04-12 04:25 UTC, afc163 commented
rebase 失败了

2019-04-12 06:55 UTC, afc163 requested changes
mix other commits

2019-04-12 16:03 UTC, DiamondYuan commented
在国外度假，可能反应慢一点。

2019-04-12 18:14 UTC, DiamondYuan commented
应该👌了

2019-04-12 18:25 UTC, DiamondYuan commented
CI 跪了 似乎是 time picker 更新了

2019-04-13 04:09 UTC, afc163 commented
等 master 更新到 feature

2019-04-14 06:03 UTC, afc163 commented
你可以 rebase feature 了

2019-04-15 01:40 UTC, DiamondYuan commented
OK 了

2019-04-15 02:18 UTC, afc163 commented on components/dropdown/demo/dropdown-button.md
> +    <Dropdown.Button onClick={handleButtonClick} overlay={menu} style={{ marginRight: 8, marginBottom: 9 }}>
margin: '0 8px 8px 0'

2019-04-15 11:40 UTC, afc163 submitted a review, later dismissed

2019-04-15 13:13 UTC, zombieJ commented on components/dropdown/index.zh-CN.md
> +| icon | 右侧的 icon | ReactNode | - | 3.17.0 |
按照字母顺序排到 `disabled` 下面

2019-04-15 13:14 UTC, zombieJ commented on components/dropdown/dropdown-button.tsx
> +    icon: <Icon type="ellipsis" />,
这个放到 render 里，`const { icon = <Icon {...} /> } = this.props;`。

2019-04-17 02:42 UTC, DiamondYuan commented
![image](https://user-images.githubusercontent.com/9692408/56257014-7fe1af00-60fd-11e9-83e3-ef47f526ecc4.png)


本地测试一直跑不过。

npm install 了。rebase feature 了。

2019-04-17 02:44 UTC, afc163 commented
要更新本地 node_modules。

2019-04-17 03:03 UTC, DiamondYuan commented
@afc163 ci 又挂了么。

2019-04-17 08:40 UTC, zombieJ commented
嗯， 依赖的 `babel-plugin-add-module-exports` 挂了，现在好了。我重跑一下

2019-04-18 14:43 UTC, afc163 submitted a review, later dismissed

2019-04-18 14:50 UTC, zombieJ commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
这边 markdown 里可以写 id 来控制样式：
```
<style>
#components-dropdown-demo-dropdown-button .ant-dropdown-button,
#components-dropdown-demo-dropdown-button .ant-btn {
  margin: 0 8px 8px 0;
}
</style>

2019-04-18 16:03 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
````css
#components-dropdown-demo-dropdown-button {
  margin: 0 8px 8px 0;
}
````

要这样加。


![image](https://user-images.githubusercontent.com/9692408/56374749-7f98ff00-6236-11e9-9547-e51f1301de24.png)

2019-04-18 16:03 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
![image](https://user-images.githubusercontent.com/9692408/56374782-8d4e8480-6236-11e9-925c-09b803ab9d27.png)


否则有 bug

2019-04-18 16:04 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
感觉没有必要，不比写 css 简单。

2019-04-19 04:16 UTC, zombieJ commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
Demo 里 jsx 的这个样式不是必须的，用户复制还需要删掉。所以建议是额外的 style 放着。
另外 `<br />` 也是可以去掉的，让它自动换行就行了。
css 不对调整一下哈~

2019-04-19 05:34 UTC, DiamondYuan commented on components/dropdown/demo/dropdown-button.md
> +  mountNode,
我搞错了，以为 ID 是加在 dropdown 上的。其实加在外层 div 上就好了。

2019-04-19 15:23 UTC, afc163 approved these changes

2019-04-19 15:24 UTC, merged