fix: Breadcrumb filtering react.fragment
ant-design/ant-design pull request #18340
Opened 2019-08-19 04:06 UTC by long-zhuge

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 组件样式改进
- [ ] TypeScript 定义更新
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

- [#18260](https://github.com/ant-design/ant-design/issues/18260)

### 💡 需求背景和解决方案

- 问题：动态渲染 Breadcrumb 时，当子组件被 React.Fragment 包裹时，父组件的 separator 会失效，子组件的 separator 会显示默认的 '/' 符号
- 解决方案：被 React.Fragment 包裹的子项进行打平处理。

```
<Breadcrumb separator="">
    <React.Fragment>
        <Breadcrumb.Item>当前位置</Breadcrumb.Item>
        <Breadcrumb.Separator>:</Breadcrumb.Separator>,
    </React.Fragment>
</Breadcrumb>
```

### 📝 更新日志怎么写？

| 语言    | 更新描述 |
| ------- | -------- |
| 🇨🇳 中文 | Breadcrumb组件添加了过滤 Fragment 标签的方法 |

### ☑️ 请求合并前的自查清单

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2019-08-19 04:36 UTC, afc163 approved these changes

2019-08-19 04:37 UTC, afc163 commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
React.Fragment 在 React 15 下不存在，最好确认一下有没有问题。

2019-08-19 08:07 UTC, afc163 requested changes
React.Fragment 在 React 15 下不存在，最好实测确认一下有没有问题。

2019-08-20 02:06 UTC, long-zhuge commented
> React.Fragment 在 React 15 下不存在，最好实测确认一下有没有问题。

好的，我实测下是否会有问题。

2019-08-20 02:44 UTC, long-zhuge commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
React.Fragment 标签是在 React v16.2.0 版本中加入的，之前是没有的。如果在项目中使用会报错。antd cli 的 peerDependencies 中 react >= 16.0.0。所以在15以下版本应该不用考虑吧。
本地实测，在16.0.0版本中，使用 react.fragment 后 react 直接就报错了。在 16.2.0 中正常。

2019-08-20 02:49 UTC, afc163 commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
antd 3.x 还在支持 15。

2019-08-20 02:51 UTC, afc163 commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
> 使用 react.fragment 后 react 直接就报错了

不应该报错吧，顶多这句 `React.Fragment` 是 undefined，看看会不会有非预期的表现就行。

2019-08-20 06:43 UTC, long-zhuge commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
在 15 版本中 react-dom 会报错，找不到对应的类/组件。当时官方推荐使用的是 react-addons-create-fragment 插件。
我们现在修复的 bug 会覆盖以往的版本吗？

2019-08-20 06:45 UTC, afc163 commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
React 15 下肯定是不能直接用 React.Fragment 的。

我的意思是这段代码不要影响现有 React 15 的项目（即使项目里没有用 `<></>`）。

2019-08-20 07:13 UTC, long-zhuge commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
嗯啊，我打包了测试下看看。

2019-08-20 07:56 UTC, long-zhuge commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
本地测试 react v15.6.0 版本可以正常使用。
demo 下的用例也回归了一遍，都能正常使用。

2019-08-20 07:58 UTC, afc163 approved these changes

2019-08-20 07:58 UTC, merged

2019-08-20 07:59 UTC, long-zhuge commented on components/breadcrumb/Breadcrumb.tsx
> +    if (React.isValidElement(element) && element.type === React.Fragment) {
![image](https://user-images.githubusercontent.com/14194437/63328845-72fef180-c363-11e9-904b-667c525eaf20.png)