upload-add-download
ant-design/ant-design pull request #18524
Opened 2019-08-28 07:08 UTC by qq645381995

### 🤔 This is a ...

- [x ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   upload  add download icon      |
| 🇨🇳 Chinese |     upload 添加下载按钮     |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2019-08-28 07:11 UTC, qq645381995 commented
语言包只加了中文和英文

2019-08-29 01:24 UTC, qq645381995 commented
@afc163 会考虑合并吗，添加了下载 Icon，删除 Icon 改用了 delete（我觉得不是关闭，而是删除所以才改的）

2019-09-02 06:05 UTC, qq645381995 commented
@afc163 这都没人看嘛？还是没时间？

2019-09-03 04:03 UTC, afc163 commented
feature branch

2019-09-04 01:44 UTC, qq645381995 commented
终于 ok 了，

2019-09-04 02:40 UTC, afc163 requested changes
feature branch please

2019-09-04 06:02 UTC, MrHeer requested changes

2019-09-04 06:02 UTC, MrHeer commented on components/upload/index.zh-CN.md
> +| showUploadList | 是否展示文件列表, 可设为一个对象，用于单独设定 `showPreviewIcon` 和 `showRemoveIcon` 和 `showDownloadIcon` | Boolean or { showPreviewIcon?: boolean, showRemoveIcon?: boolean, showDownloadIcon?: boolean }
```diff
- | showUploadList | 是否展示文件列表, 可设为一个对象，用于单独设定 `showPreviewIcon` 和 `showRemoveIcon` 和 `showDownloadIcon` | Boolean or { showPreviewIcon?: boolean, showRemoveIcon?: boolean, showDownloadIcon?: boolean } | true |  |
+ | showUploadList | 是否展示文件列表, 可设为一个对象，用于单独设定 `showPreviewIcon`, `showRemoveIcon` 和 `showDownloadIcon` | Boolean or { showPreviewIcon?: boolean, showRemoveIcon?: boolean, showDownloadIcon?: boolean } | true |  |
```

2019-09-04 07:44 UTC, qq645381995 commented
下一步要做啥？不太懂

2019-09-04 07:52 UTC, afc163 commented
https://ant.design/docs/react/contributing-cn#%E5%88%86%E6%94%AF%E7%AE%A1%E7%90%86

2019-09-04 08:01 UTC, qq645381995 commented
> https://ant.design/docs/react/contributing-cn#%E5%88%86%E6%94%AF%E7%AE%A1%E7%90%86

https://github.com/ant-design/ant-design/pull/18661

2019-09-04 08:01 UTC, closed without merging