✨ support updating message content with a unique key
ant-design/ant-design pull request #18678
Opened 2019-09-05 02:22 UTC by wendzhue

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 组件样式改进
- [ ] TypeScript 定义更新
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志怎么写？

| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |

- 中文（可选）:

### ☑️ 请求合并前的自查清单

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2019-09-05 07:34 UTC, dengfuping commented on components/message/index.tsx
> +  key?: string;
- `string | number`

2019-09-05 07:34 UTC, dengfuping commented on components/message/demo/update.md
> +  message.open({
- 用 `message.success` 或其它方法做示例吧。

2019-09-05 07:34 UTC, dengfuping commented on components/message/demo/update.md
> +  }, 1000);
- 感觉加上 `setTimeout` 这个没什么意义，只要表明多次点击只触发一次就行。

2019-09-05 07:39 UTC, dengfuping commented
- 还需要更新下 `snapshot`。

```bash
$ npm test -- -u
```

2019-09-05 07:41 UTC, wendzhue commented on components/message/demo/update.md
> +  }, 1000);
这个是直接用的 Notification 那边的效果。

2019-09-05 07:51 UTC, dengfuping commented on components/message/demo/update.md
> +  }, 1000);
- 😯懂了，确实需要保留这个逻辑。

2019-09-05 08:04 UTC, wendzhue commented on components/message/demo/update.md
> +  message.open({
这样的话，要给 message success 等方法加参数了。

2019-09-05 08:14 UTC, dengfuping commented on components/message/demo/update.md
> +  message.open({
- 加在最后吧，不然 `key` 属性只在 `message.open` 方法生效，在 `message.success` 其它方法上不生效。`Notification` 由于都是通过 `config 对象` 传参，所以没有这个问题。

2019-09-05 09:16 UTC, dengfuping commented on components/message/index.zh-CN.md
> +| key      | 当前提示的唯一标志                            | string            | -      |      |
- `message.open` 那里的 `config` 参数也要加下 `key` 的说明。

2019-09-05 09:18 UTC, wendzhue commented on components/message/index.zh-CN.md
> +| key      | 当前提示的唯一标志                            | string            | -      |      |
啊对

2019-09-05 11:11 UTC, MrHeer submitted a review, later dismissed

2019-09-06 02:28 UTC, dengfuping commented on components/message/index.en-US.md
> +| key | The unique identifier of the Message | string | - |  |
- `string | number`

2019-09-06 02:28 UTC, dengfuping commented on components/message/index.zh-CN.md
> +| key      | 当前提示的唯一标志                            | string            | -      |      |
- `string | number`

2019-09-06 02:29 UTC, dengfuping commented on components/message/index.zh-CN.md
> +| key      | 当前提示的唯一标志                            | string            | -      |      |
- Remember to rebase it.

2019-09-06 07:04 UTC, dengfuping submitted a review, later dismissed

2019-09-06 07:05 UTC, dengfuping commented
- @wendzhue Could you rebase it to make commit history clean?

2019-09-06 07:09 UTC, afc163 commented on components/message/index.zh-CN.md
> +- `message.loading(content, [duration], onClose, [key])`
这个参数列表已经很长了（一开始没设计好），[duration] 可选会造成三个参数的调用有二义性。

可以改成

```
message.warn(content, {
  key: 'xx',
  duration: '',
  onClose: () => {},
})
```

当第二个参数是 Object 时生效。同时要保持现有用法的兼容性（需要补充一些用例）。

2019-09-06 07:11 UTC, afc163 commented on components/message/index.zh-CN.md
> +- `message.loading(content, [duration], onClose, [key])`
或者干脆

```js
message.warn({
  key: 'xx',
  content: 'content',
  duration: '',
  onClose: () => {},
})
```

2019-09-06 07:14 UTC, yoyo837 commented on components/message/index.tsx
>        duration = undefined;
key 在这里应该要跟随迁移，除非content以外的参数全部改成对象收纳

2019-09-06 08:14 UTC, wendzhue commented on components/message/index.zh-CN.md
> +- `message.loading(content, [duration], onClose, [key])`
> 或者干脆
> 
> ```js
> message.warn({
>   key: 'xx',
>   content: 'content',
>   duration: '',
>   onClose: () => {},
> })
> ```

那我就用第二种方式实现了，和 notification 组件保持一致

2019-09-12 05:00 UTC, wendzhue commented
> * @wendzhue Could you rebase it to make commit history clean?

Done. Please review again.

2019-09-16 07:49 UTC, wendzhue commented
@dengfuping Ping.

2019-09-17 06:18 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.success({ content: 'Loaded', key }), 1000);
这种不要支持了，如果接收 object 只支持一个参数，duration 也放进来。

2019-09-17 06:45 UTC, wendzhue commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.success({ content: 'Loaded', key }), 1000);
这里的参数没有 duration，只是在 1000 毫秒之后修改 message 内容

2019-09-17 06:47 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.success({ content: 'Loaded', key }), 1000);
```suggestion
        setTimeout(() => message.success({ content: 'Loaded', key, duration: 1000 }));
```

2019-09-17 09:54 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.success({ content: 'Loaded', key }), 1000);
要把 duration 加进去。当 `message.success(object)` 时，所有的参数都放到 object 里。

2019-09-24 09:58 UTC, wendzhue commented
@afc163 Ping~

2019-09-24 10:06 UTC, afc163 commented on components/message/demo/update.md
> +```
来个用例吧。

2019-09-24 10:06 UTC, afc163 commented on components/message/demo/update.md
> +可以通过唯一的 key 来更新内容。
key 加 `

2019-09-24 10:07 UTC, afc163 commented on components/message/index.zh-CN.md
>  - `message.loading(content, [duration], onClose)`
文档里专门补充两种参数用法的说明。

2019-09-24 10:07 UTC, afc163 commented on components/message/index.zh-CN.md
> +| key      | 当前提示的唯一标志                            | string\|number | -      | 3.23.0 |
如果能赶上，应该是 3.25.0 了。

2019-09-24 10:08 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.success({ content: 'Loaded', key }), 1000);
用例里这个用法没改掉。

2019-09-24 10:10 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.destroy(), 3000);
用例里 `message.success({ content: 'Loaded', key }), 1000)` 这个用法没改掉。

2019-09-24 10:50 UTC, wendzhue commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.destroy(), 3000);
这是为了测试经过一段时间后重新调用方法时 message 内容会被更新，`1000` 是 `setTimeout` 的参数。

2019-09-24 10:52 UTC, afc163 commented on components/message/__tests__/index.test.js
> +        setTimeout(() => message.destroy(), 3000);
哦，我看晕了。。

2019-09-25 02:39 UTC, afc163 commented on components/message/index.zh-CN.md
> +也可以对象的形式传递参数：
👍

2019-09-25 02:49 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/18987

我修一下用例，一会 rebase 一下 feature 就好。

2019-09-25 03:32 UTC, afc163 commented
/rebase

2019-09-25 03:40 UTC, yoyo837 commented on components/message/index.en-US.md
> +| key | The unique identifier of the Message | string\|number | - | 3.25.0 |
赶不上 3.24么？

2019-09-25 03:42 UTC, afc163 commented on components/message/index.en-US.md
> +| key | The unique identifier of the Message | string\|number | - | 3.25.0 |
搞错了。

2019-09-25 03:46 UTC, yoyo837 requested changes
预计合入3.24.0

2019-09-25 04:06 UTC, afc163 approved these changes

2019-09-25 04:07 UTC, afc163 commented
可以帮忙把主楼的 changelog 写的更详实一点，包括支持 object 参数这块。

2019-09-25 04:09 UTC, yoyo837 approved these changes

2019-09-25 04:30 UTC, merged

2019-10-14 13:50 UTC, afc163 commented
close #10320