The background for the disabled menu item is made important, so that it does not change when hover
ant-design/ant-design pull request #18706
Opened 2019-09-06 08:00 UTC by alxkosov

…ed on hover

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

Problem: menu item in disabled state when hover changes its background
the background of the disabled menu item should not change when you hover over it
Solution: make background for disabled-item !important

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2019-09-06 08:01 UTC, alxkosov commented
Sandbox with problem:
https://codesandbox.io/s/vibrant-nobel-xede1
Blue background on hover on disabled menu item

2019-09-06 08:03 UTC, alxkosov commented
Sandbox with fixed problem:
https://codesandbox.io/s/sad-jackson-ux9uc
through add !important
.ant-menu-item-disabled,
.ant-menu-submenu-disabled {
  background: none !important;
}

2019-09-06 08:04 UTC, alxkosov commented
It is necessary, because there is a need to customize the behavior of menu items on the hover, and then disabled-menu item also begins to be highlighted. he shouldn't.

2019-09-17 12:18 UTC, akaguny commented
hi!
@zombieJ anybody can help us with this PR?

2019-09-17 12:19 UTC, akaguny approved these changes
this change logic and helpfully for us

2019-09-17 12:32 UTC, yoyo837 commented
ping @afc163

2019-09-18 02:59 UTC, afc163 approved these changes

2019-09-18 03:01 UTC, afc163 requested changes
I afraid others who customize disabled menu item background will be overrided by this change.

It is better no to affect disabled menu item when you override styles: https://codesandbox.io/s/inspiring-burnell-3731v

2019-09-18 13:11 UTC, akaguny commented
> I afraid others who customize disabled menu item background will be overrided by this change.
> 
> It is better no to affect disabled menu item when you override styles: https://codesandbox.io/s/inspiring-burnell-3731v

But it is not breaking change, it is bugfix.)
override styles - very bad practice.
users must using customization, use override styles is they own risc.

2019-09-18 13:55 UTC, hextion commented
> I afraid others who customize disabled menu item background will be overrided by this change.
> 
> It is better no to affect disabled menu item when you override styles: https://codesandbox.io/s/inspiring-burnell-3731v

this fix for correct working `@dark-menu-item-hover-bg` less variable https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L414

2019-09-18 13:58 UTC, hextion approved these changes

2019-09-18 14:08 UTC, hextion commented
@alxkosov is there any solution without using `!important`? May you increase disabled menu item selector weight?

2019-09-20 07:48 UTC, alxkosov commented
@hextion, no I cannot

2019-09-26 05:52 UTC, akaguny commented
@afc163 , any comments?

2019-10-08 07:31 UTC, akaguny commented
👍 up

2019-10-23 06:48 UTC, afc163 commented
I insist not adding unneccessary `!important` styles.

2019-10-23 06:48 UTC, closed without merging