添加tooltip destroyTooltipOnHide Api说明
ant-design/ant-design pull request #18859
Opened 2019-09-17 09:00 UTC by ooolog

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2019-09-17 09:09 UTC, yoyo837 requested changes
列头内容 错位了

2019-09-17 09:34 UTC, ooolog commented
> 列头内容 错位了

😯，的确错误了，修复了

2019-09-17 09:41 UTC, yoyo837 commented on components/tooltip/index.zh-CN.md
> +| destroyTooltipOnHide | 是否在隐藏工具提示时销毁工具提示 | boolean | false |  |
> 销毁工具提示

这里的`工具提示` 应该不需要翻译

2019-09-17 10:03 UTC, ooolog commented on components/tooltip/index.zh-CN.md
> +| destroyTooltipOnHide | 是否在隐藏工具提示时销毁工具提示 | boolean | false |  |
空着就可以吗

2019-09-17 10:10 UTC, ooolog commented on components/tooltip/index.zh-CN.md
> +| destroyTooltipOnHide | 是否在隐藏工具提示时销毁工具提示 | boolean | false |  |
ok了

2019-09-17 10:18 UTC, merged

2019-09-21 05:05 UTC, zombieJ commented
这个官方文档里先不透出了，antd 里的命名规范需要改成 `destroyOnHide`。
ref #16048