fix: disabled cursor
ant-design/ant-design pull request #19403
Opened 2019-10-24 09:15 UTC by chiaweilee

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ x ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/19401

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ x ] Doc is updated/provided or not needed
- [ x ] Demo is updated/provided or not needed
- [ x ] TypeScript definition is updated/provided or not needed
- [ x ] Changelog is provided or not needed

2019-10-24 09:32 UTC, yoyo837 requested changes
`.@{checkbox-prefix-cls}-disabled` 是 `.@{checkbox-prefix-cls}-wrapper` 的后代元素，另有 `.@{checkbox-prefix-cls}-wrapper-disabled` 元素。

2019-10-24 09:32 UTC, yoyo837 commented on components/checkbox/style/mixin.less
> +    .@{checkbox-prefix-cls}-wrapper {
缺 `&` 吧，同一个元素

2019-10-24 09:32 UTC, yoyo837 commented on components/checkbox/style/mixin.less
> +    .@{checkbox-prefix-cls}-wrapper {
不对，是上一级

2019-10-24 16:22 UTC, yoyo837 approved these changes

2019-10-24 16:26 UTC, yoyo837 commented
@afc163 `netlify` 怎么重新触发部署？

2019-10-24 16:27 UTC, yoyo837 commented
好像所有PR的 `netlify` 都这样了...

2019-10-25 03:12 UTC, afc163 commented
> 好像所有PR的 netlify 都这样了...

netlify service down.

2019-10-25 03:37 UTC, merged