fix: timeline content style
ant-design/ant-design pull request #21049
Opened 2020-01-21 09:57 UTC by xrkffgg

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/21048

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2020-01-21 10:07 UTC, yoyo837 commented on components/timeline/style/index.less
> +            text-align: left;
这个修改 会破坏 “右侧时间轴点”

2020-01-21 10:20 UTC, yoyo837 requested changes
rtl 右侧时间轴点会破坏

2020-01-21 10:36 UTC, xrkffgg commented on components/timeline/style/index.less
> +            text-align: left;
确实是，看来要把这两种模式的分开才行

2020-01-22 03:25 UTC, zombieJ commented
CI failed.

2020-01-22 03:40 UTC, closed without merging

2020-01-22 03:42 UTC, yoyo837 commented
上游分支先更新到最小，本分支rebase 它 ，然后可以继续修改，push 时 加强制 --force

2020-01-22 03:48 UTC, xrkffgg commented
我 push 的时候直接用了 VSCode 的 😅，前面操作一样的

2020-01-22 03:55 UTC, xrkffgg commented
@yoyo837 
1. master : git fetch ant
2. master: git merge ant/master
3. master: git checkout k
4. k: git rebase master
5. k: git push --force

是这样吗？

2020-01-22 04:06 UTC, yoyo837 commented
假如你的remote 上游叫ant
1.切换到你想要基于修改的分支，比如master 
2.git fetch ant
3.git rebase ant/master
3.git push --force
4.git checkout -b 新分支
5.在新分支修改
6.push
7. 创建PR

当上游又变动后，
就先同步好自己fork的分支，然后新分支从自己的基分支再rebase一遍呗。方法好几种。

2020-01-22 04:17 UTC, xrkffgg commented
谢啦，我以后再试试





------------------ Original ------------------
From: Amumu <notifications@github.com&gt;
Date: Wed,Jan 22,2020 0:06 PM
To: ant-design/ant-design <ant-design@noreply.github.com&gt;
Cc: xrkffgg <xrkffgg@vip.qq.com&gt;, State change <state_change@noreply.github.com&gt;
Subject: Re: [ant-design/ant-design] fix: timeline content style (#21049)




假如你的remote 上游叫ant
 1.切换到你想要基于修改的分支，比如master
 2.git fetch ant
 3.git rebase ant/master
 3.git push --force
 4.git checkout -b 新分支
 5.在新分支修改
 6.push
 7. 创建PR
 
当上游又变动后，
 就先同步好自己fork的分支，然后新分支从自己的基分支再rebase一遍呗。方法好几种。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.