add Azerbaijani translation
ant-design/ant-design pull request #21341
Opened 2020-02-11 13:43 UTC by orkhan-huseyn

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Added Azerbaijani translation into locale provider

### 💡 Background and solution

Added Azerbaijani translation into locale provider

### 📝 Changelog

Added Azerbaijani translation into locale provider

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-02-11 14:03 UTC, yoyo837 commented on components/locale-provider/az_AZ.tsx
> +export default {
```js
import locale from '../locale/az_AZ';

export default locale;
```

2020-02-11 14:16 UTC, yoyo837 requested changes
components/locale-provider/az_AZ.tsx: 
```js
import locale from '../locale/az_AZ';

export default locale;
```

2020-02-11 17:12 UTC, yoyo837 commented on components/locale/az_AZ.tsx
> +export default {
![image](https://user-images.githubusercontent.com/6134547/74260463-80a29c00-4d34-11ea-81bc-bc68cf1d50aa.png)

Please refer to this code.

2020-02-12 04:52 UTC, orkhan-huseyn commented
Hi, 
I have added `az_AZ` locale to `rc-picker` library and it has been merged.
Why am I getting this error on Circle CI?

```
components/date-picker/locale/az_AZ.tsx:1:28 - error TS2307: Cannot find module 'rc-picker/lib/locale/az_AZ'.

1 import CalendarLocale from 'rc-picker/lib/locale/az_AZ';
```

2020-02-12 05:30 UTC, yoyo837 commented
rc-picker has not released a new version

2020-02-12 05:44 UTC, yoyo837 commented on components/calendar/locale/az_AZ.tsx
> +import tr_TR from '../../date-picker/locale/az_AZ';
typo

2020-02-12 05:59 UTC, orkhan-huseyn commented on components/calendar/locale/az_AZ.tsx
> +import tr_TR from '../../date-picker/locale/az_AZ';
Fixed

2020-02-12 06:54 UTC, yoyo837 commented
`rc-pagination` need a PR for this.

And commits should be clean.

2020-02-12 06:57 UTC, orkhan-huseyn commented
I have added the same locales to `rc-pagination` as well. And it has been [merged](https://github.com/react-component/pagination/pull/249) into master.

2020-02-12 07:07 UTC, yoyo837 commented
Also not released yet

2020-02-14 05:20 UTC, orkhan-huseyn commented
Hi, when do we know that the depended packages are released new version?
Also, what should I do about commits? I already have 8 commits for a simple feature.

2020-02-14 05:26 UTC, yoyo837 commented
Your commits is mixed with other people's changes.

About dependent new version, you can watch its release.

![image](https://user-images.githubusercontent.com/6134547/74503935-83b4ac80-4f2d-11ea-8802-c6bc15cbf16c.png)

2020-02-14 05:33 UTC, orkhan-huseyn commented
That's because I have fethced and rebased before pushing. What should I do about them?

2020-02-14 05:48 UTC, yoyo837 commented
You can try rebase again.

2020-02-14 09:38 UTC, zombieJ commented
`+ rc-picker@0.0.1-rc.6`

2020-02-14 09:39 UTC, zombieJ commented on components/form/style/vertical.less
> +  }
Should not affect other files

2020-02-15 07:20 UTC, yoyo837 commented
I think you may need to send a new PR, please remember to pull the latest before that.

2020-02-15 07:56 UTC, orkhan-huseyn commented
Alright. I am closing this PR then

2020-02-15 07:56 UTC, closed without merging