style: 💄 Add hover background for link button
ant-design/ant-design pull request #22552
Opened 2020-03-24 05:58 UTC by afc163

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

same as http://overdrive.autoguru.io/?path=/story/components-actions--standard

<img width="383" alt="image" src="https://user-images.githubusercontent.com/507615/77393126-62ba6380-6dd7-11ea-8b63-84f99107cfa8.png">

增加一个反馈效果，标识出响应区域。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add hover background color for link button. |
| 🇨🇳 Chinese | Button `type="link"` 增加 hover 时的背景颜色以标识响应区域。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-03-24 06:07 UTC, shaodahong commented
可以加个变量，但是不建议默认是有背景的，区别还是有大的，有些用户 `link` 当作 `a` 来用，有了背景会觉得很奇怪

2020-03-24 06:08 UTC, afc163 commented
这个背景（鼠标手型的点击区域）其实一直存在，其实和链接还是有区别。

2020-03-24 06:17 UTC, shaodahong commented
特地去翻了下当初加 `link` 的初衷，https://github.com/ant-design/ant-design/issues/15892，如果有了背景，又回到 Button 的原点

2020-03-24 06:20 UTC, afc163 commented
现在的实现是 hover 才有背景，默认还是一样的。

2020-03-24 06:35 UTC, shaodahong commented
> 现在的实现是 hover 才有背景，默认还是一样的。

不一样，风格不一样，我个人看法是加个 less 变量默认还是保持现在的风格，或者加个 `type="text"` 类型的 Button

2020-03-24 06:37 UTC, AshoneA commented
其实我觉得 hover 的时候鼠标手势的变化和文字有点变淡已经暗示这里是可点击区域了。

2020-04-11 16:16 UTC, raghavauppuluri13 commented
Any updates on when this will be implemented?

2020-04-18 14:30 UTC, afc163 commented
改为新增一个 text 类型按钮。

2020-04-18 16:15 UTC, yoyo837 approved these changes

2020-04-18 17:53 UTC, hengkx approved these changes

2020-04-18 19:02 UTC, abenhamdine requested changes
miss new type `text` in https://github.com/ant-design/ant-design/blob/style-link-button-bg/components/button/index.en-US.md#L43

2020-04-19 04:03 UTC, zombieJ commented
https://ant.design/docs/spec/buttons-cn#%E2%91%A2-%E6%96%87%E5%AD%97%E6%8C%89%E9%92%AE

link 类型是被归类到文字按钮类型的，`text` 是不是应该和 `primary` 对应为 `secondary` 类型才对？

2020-04-19 07:04 UTC, afc163 commented
现在真实使用场景基本上没有用 link 的，尤其是和其他按钮搭配使用时。比如：

<img width="181" alt="image" src="https://user-images.githubusercontent.com/507615/79681748-184dca80-824f-11ea-88c3-9a07a3b88c2b.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/507615/79681751-1f74d880-824f-11ea-9f3a-7b907f3f9be4.png">

2020-04-19 13:42 UTC, AshoneA commented on components/button/index.zh-CN.md
> +| type | 设置按钮类型，可选值为 `primary` `ghost` `dashed` `danger` `link` `text` 或者不设 | string | - |  |
```
| type | 设置按钮类型 | `primary` \|  `ghost` \| `dashed` \| `danger` \| `link` \|  `text`  | - |  |
```
这边这么写会比较好吧？

2020-04-21 08:55 UTC, afc163 commented
@zombieJ 的意思是改成 `type="secondary"` 么？我比较担心 `secondary` 语义上是 `primary` 的次级，但是我们的次级实际上是 default。

2020-04-21 09:18 UTC, yoyo837 commented
`secondary` 我个人也是理解为`primary` 的次级。

2020-04-21 13:24 UTC, zombieJ commented
有道理，我和设计师联系一下。问问怎么归类好了。

2020-04-23 03:55 UTC, shangguanhongzhou commented
> 有道理，我和设计师联系一下。问问怎么归类好了。

归类到「文字按钮」合适点。

> ③ 文字按钮
> 弱化的按钮，采用更轻量的按钮样式，可用于需大面积展示按钮场景，例如表格组件中的操作列。
> 

 link 按钮目前用在 操作列，
![image](https://user-images.githubusercontent.com/8383020/80057399-10e13680-8559-11ea-91e2-d29d2106192e.png)

反倒是新增的这个" text 类型按钮" 目前没有用到。

2020-04-23 03:59 UTC, afc163 commented
看看 https://github.com/ant-design/ant-design/pull/22552#issuecomment-616061627

2020-04-23 04:07 UTC, afc163 commented
还有

<img width="306" alt="image" src="https://user-images.githubusercontent.com/507615/80058052-c2cd3280-855a-11ea-99dc-c8802eed7fb8.png">

还有最下面的无边框非链接色的图标按钮，现在也是没有对应实现的。

<img width="212" alt="image" src="https://user-images.githubusercontent.com/507615/80058093-ec865980-855a-11ea-9ced-304deb37fd9f.png">

2020-04-23 05:38 UTC, shangguanhongzhou commented
> 
> 还有最下面的无边框非链接色的图标按钮，现在也是没有对应实现的。
> 
> <img alt="image" width="212" src="https://user-images.githubusercontent.com/507615/80058093-ec865980-855a-11ea-9ced-304deb37fd9f.png">

图标按钮 在表格中有用到
![image](https://user-images.githubusercontent.com/8383020/80058717-a205dc80-855c-11ea-88dd-7d920c0de2ef.png)

2020-04-23 05:40 UTC, afc163 commented
> 图标按钮 在表格中有用到

antd 按钮里没有对应实现的。

2020-04-26 03:38 UTC, afc163 commented
<img width="157" alt="image" src="https://user-images.githubusercontent.com/507615/80297062-6cf2c780-87b2-11ea-8e1a-3b8970e11649.png">

这是 linke 里的用法，更直接，hover 就带有背景色。

2020-04-29 03:16 UTC, AshoneA approved these changes

2020-04-29 12:41 UTC, zombieJ commented
我再去 ping 一下设计师

2020-05-06 02:11 UTC, shangguanhongzhou commented
> > 图标按钮 在表格中有用到
> 
> antd 按钮里没有对应实现的，用现在这个 type text 按钮就能轻松实现了。



> <img alt="image" width="157" src="https://user-images.githubusercontent.com/507615/80297062-6cf2c780-87b2-11ea-8e1a-3b8970e11649.png">
> 
> 这是 linke 里的用法，交互比这个 PR 更进一步，hover 就带有背景色。如果我们不落规范，这种其实算魔改。



> <img alt="image" width="157" src="https://user-images.githubusercontent.com/507615/80297062-6cf2c780-87b2-11ea-8e1a-3b8970e11649.png">
> 
> 这是 linke 里的用法，交互比这个 PR 更进一步，hover 就带有背景色。如果我们不落规范，这种其实算魔改。

OK， 好的！

2020-05-06 02:15 UTC, merged

2020-05-31 04:48 UTC, morenyang commented
@afc163  I thinks the border should not display when `type=text` and `danger=true` 

![image](https://user-images.githubusercontent.com/15653996/83344670-a8962980-a33c-11ea-9ef5-a7f7a94e6d73.png)

2020-05-31 05:00 UTC, afc163 commented
PR welcome~