docs: 4.1.1 changelog
ant-design/ant-design pull request #22903
Opened 2020-04-03 14:26 UTC by ycjcl868

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 组件样式改进
- [ ] TypeScript 定义更新
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志怎么写？

| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️ 

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2020-04-03 14:33 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🛠 重构 Picker 拆分成多文件。[#22850](https://github.com/ant-design/ant-design/pull/22850)
不用提，内部重构，对用户无影响。

2020-04-03 14:33 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🐞 移除 Tabs 的 tabpane 轮廓线。[#22752](https://github.com/ant-design/ant-design/pull/22752) [@MrHeer](https://github.com/MrHeer)
这个可以移到第一个，反馈比较多。

2020-04-03 14:34 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🐞 移除 Tabs 的 tabpane 轮廓线。[#22752](https://github.com/ant-design/ant-design/pull/22752) [@MrHeer](https://github.com/MrHeer)
```suggestion
- 🐞 移除 Tabs 内容区域的 focus 蓝色轮廓线。[#22752](https://github.com/ant-design/ant-design/pull/22752) [@MrHeer](https://github.com/MrHeer)
```

2020-04-03 14:34 UTC, zombieJ commented
脚本读的描述会丢失 `` ` ``，需要自己补上。

2020-04-03 14:35 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 💄 优化 `@info-color` less 变量，默认为 `@primary-color`。[3f8db](https://github.com/ant-design/ant-design/commit/3f8dbc500fd31b631a10bbacceaee07bf61df02a)
https://github.com/ant-design/ant-design/pull/22723

2020-04-03 14:36 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Table `filters` 未变化时触发 `onChange` 事件的问题。[ddb0a](https://github.com/ant-design/ant-design/commit/ddb0ac46ba7b5ccc04f496523938d87484489191)
https://github.com/ant-design/ant-design/pull/22829

2020-04-03 14:37 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Table `filters` 未变化时触发 `onChange` 事件的问题。[ddb0a](https://github.com/ant-design/ant-design/commit/ddb0ac46ba7b5ccc04f496523938d87484489191)
<img width="550" alt="截屏2020-04-03下午10 36 15" src="https://user-images.githubusercontent.com/507615/78372290-aabd5f80-75fb-11ea-8b3c-d560d19bdb28.png">

这里可以找到 PR 链接。

2020-04-03 14:37 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🐞 修复 Affix 抛出 React state update on unmounted component 警告的问题。[#22790](https://github.com/ant-design/ant-design/pull/22790)
```suggestion
- 🐞 修复 Affix 抛出 React `state update on unmounted component` 警告的问题。[#22790](https://github.com/ant-design/ant-design/pull/22790)
```

2020-04-03 14:38 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🆕 Table 行选择下拉菜单支持 `getPopupContainer`。[#22787](https://github.com/ant-design/ant-design/pull/22787) [@mikeyshing88](https://github.com/mikeyshing88)
修复 **** 不支持 **** 的问题。

2020-04-03 14:39 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🐞 修复 Tabs 不支持小尺寸。[#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```suggestion
- 🐞 修复 Tabs 不支持小尺寸的问题。[#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```

2020-04-03 14:40 UTC, zombieJ commented on CHANGELOG.en-US.md
> +  - 🆕 Table row selection dropdown should now support `getPopupContainer`. [#22787](https://github.com/ant-design/ant-design/pull/22787) [@mikeyshing88](https://github.com/mikeyshing88)
> Table row selection dropdown support `getPopupContainer`.

2020-04-03 14:42 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复当 `column` 的 children 为 `undefined` 时整列未显示的问题。[#22832](https://github.com/ant-design/ant-design/pull/22832)
```suggestion
  - 🐞 修复当 `column.children` 为 `undefined` 时整列未显示的问题。[#22832](https://github.com/ant-design/ant-design/pull/22832)
```

2020-04-03 14:42 UTC, zombieJ commented on CHANGELOG.zh-CN.md
> +- 🇫🇷 DatePicker 和 TimePicker 法语国际化。[#22769](https://github.com/ant-design/ant-design/pull/22769) [@PaulJln](https://github.com/PaulJln)
国际化可以放到最后，TS 前。

2020-04-03 14:44 UTC, zombieJ commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Form RTL 下 label 显示。[#22621](https://github.com/ant-design/ant-design/pull/22621)
“显示” 改成 “样式”，让 RTL 描述更统一一些。

2020-04-03 15:05 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/22904

2020-04-03 15:05 UTC, afc163 commented
dist 一直是挂的。

2020-04-03 15:08 UTC, shaodahong commented
@zombieJ 看看这个 https://github.com/ant-design/ant-design/pull/22755 能不能带上

2020-04-03 15:36 UTC, afc163 approved these changes

2020-04-03 15:36 UTC, afc163 commented on CHANGELOG.en-US.md
> +- 🐞 Fix Tabs remove tabpane outline. [#22752](https://github.com/ant-design/ant-design/pull/22752) [@MrHeer](https://github.com/MrHeer)
```suggestion
- 🐞 Fix Tabs panel focus outline style. [#22752](https://github.com/ant-design/ant-design/pull/22752) [@MrHeer](https://github.com/MrHeer)
```

2020-04-03 15:36 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Form RTL 下 label 样式。[#22621](https://github.com/ant-design/ant-design/pull/22621)
```suggestion
  - 🐞 修复 Form RTL 下 label 样式问题。[#22621](https://github.com/ant-design/ant-design/pull/22621)
```

2020-04-03 15:37 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Space RTL 样式。[#22809](https://github.com/ant-design/ant-design/pull/22809)
```suggestion
  - 🐞 修复 Space RTL 样式问题。[#22809](https://github.com/ant-design/ant-design/pull/22809)
```

2020-04-03 23:38 UTC, xrkffgg commented
4.1.1 怎么样了 
https://github.com/ant-design/ant-design/issues/22910
https://github.com/ant-design/ant-design/issues/22919

2020-04-04 02:09 UTC, xrkffgg commented
@afc163 @ycjcl868 @zombieJ

2020-04-04 02:42 UTC, hengkx commented
> 4.1.1 怎么样了 
> 
> https://github.com/ant-design/ant-design/issues/22910
> 
> https://github.com/ant-design/ant-design/issues/22919

关掉一个把 保留一个在那让大家知道

2020-04-04 02:59 UTC, xrkffgg commented
等更新了再关吧

2020-04-04 03:16 UTC, MrHeer requested changes

2020-04-04 03:16 UTC, MrHeer commented on CHANGELOG.en-US.md
> +- 🐞 Fix Tabs do not support small size. [#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```suggestion
- 🐞 Fix Card Tabs do not support small size. [#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```

2020-04-04 03:16 UTC, MrHeer commented on CHANGELOG.zh-CN.md
> +- 🐞 修复 Tabs 不支持小尺寸的问题。[#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```suggestion
- 🐞 修复 Card Tabs 不支持小尺寸的问题。[#22666](https://github.com/ant-design/ant-design/pull/22666) [@MrHeer](https://github.com/MrHeer)
```

2020-04-04 06:11 UTC, xrkffgg commented
https://github.com/ant-design/ant-design/pull/22513 带的上吗？

2020-04-04 06:14 UTC, xrkffgg commented
已经 merge 到 master 了

2020-04-04 13:11 UTC, ycjcl868 commented
> #22513 带的上吗？

带上了

2020-04-04 14:21 UTC, zombieJ commented
差不多可以发了吧，拖久了又会有新的 merge 进来。

2020-04-05 05:09 UTC, ycjcl868 commented
下午发

2020-04-05 08:34 UTC, merged

2020-04-05 12:31 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/22916