fix: fix menu and spin style in compact mode
ant-design/ant-design pull request #22908
Opened 2020-04-03 15:38 UTC by AshoneA

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://ant.design/components/menu-cn/#components-menu-demo-theme

https://ant.design/components/spin-cn/#components-spin-demo-size

https://github.com/ant-design/ant-design/issues/22815

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix Menu and Spin style in compact mode        |
| 🇨🇳 Chinese |   修复 Menu 和 Spin 在紧凑模式下样式        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2020-04-03 16:23 UTC, xrkffgg requested changes

2020-04-03 16:23 UTC, xrkffgg commented on components/spin/demo/size.md
> +[data-theme="compact"] .ant-spin,.ant-spin {
```
[data-theme="compact"] .ant-spin,[data-theme="dark"] .ant-spin,.ant-spin {
  margin-right: 16px;
}
```

2020-04-04 04:19 UTC, AshoneA commented on components/spin/demo/size.md
> +[data-theme="compact"] .ant-spin,.ant-spin {
换了种方式，这种做法之后再加其他模式这里还得改。

2020-04-04 12:32 UTC, xrkffgg approved these changes

2020-04-05 04:04 UTC, merged