fix: long SubMenu title display
ant-design/ant-design pull request #22971
Opened 2020-04-07 01:57 UTC by wwyx778

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
[#22609](https://github.com/ant-design/ant-design/issues/22609)

### 💡 Background and solution
Fix Long Submenu Title Being Overlayed By Arrow Icon

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-04-07 08:54 UTC, xrkffgg requested changes

2020-04-07 08:54 UTC, xrkffgg commented on components/menu/style/index.less
> +      padding: 0 34px 0 16px;
不建议在公共样式中修改，可单独处理这个。

顺便 rebase 下 master

2020-04-08 03:38 UTC, yoyo837 commented
Commits should be clean.

2020-04-08 03:42 UTC, wwyx778 commented
> Commits should be clean.

我可以关掉这个PR重新来一次吗？

2020-04-08 03:46 UTC, closed without merging

2020-04-08 03:47 UTC, yoyo837 commented
先fetch最新rebase 到 你的分支，如果是后面同步最新的可能需要`--force` push

2020-04-08 03:48 UTC, wwyx778 commented
> 先fetch最新rebase 到 你的分支，如果是后面同步最新的可能需要`--force` push

好的。谢谢。