change comment action's padding to margin
ant-design/ant-design pull request #24869
Opened 2020-06-09 08:21 UTC by lhz516

### 🤔 This is a ...

- Bug fix
- Component style update

### 💡 Background and solution
For A11Y, when we add `tabIndex` to the comment actions `span`, it has some extra space while pressing "Tab" into this element.
```jsx
<Comment
  actions={[
    <span
      role="button"
      tabIndex={0}
      key="comment-reply"
      onKeyDown={handleClickReply}
      onClick={handleClickReply}
    >
      回复
    </span>,
  ]}
  //  ...other props
/>
```

![image](https://user-images.githubusercontent.com/9879279/84122592-83b14e80-a9ed-11ea-8da6-601a644e53c3.png)

After the fix, the tab outline area is corrected:
![image](https://user-images.githubusercontent.com/9879279/84122452-4c42a200-a9ed-11ea-8ee6-21e8be555c17.png)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |Fix Comment actions' outline style when `tabIndex` is provided|
| 🇨🇳 Chinese |修复评论组件actions区域有`tabIndex`时的边框样式|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is ~~updated/provided or~~ not needed
- [x] Demo is ~~updated/provided or~~ not needed
- [x] TypeScript definition is ~~updated/provided or~~ not needed
- [x] Changelog is provided ~~or not needed~~

2020-06-09 09:16 UTC, xrkffgg requested changes

2020-06-09 09:16 UTC, xrkffgg commented on components/comment/style/index.less
> +        margin-right: 10px;
rtl 的也顺便改一下

2020-06-10 03:04 UTC, lhz516 commented on components/comment/style/index.less
> +        margin-right: 10px;
好的，改了

2020-06-10 03:51 UTC, xrkffgg commented
更新一下 snap

2020-06-10 03:51 UTC, xrkffgg commented
yarn test -u

2020-06-10 04:35 UTC, lhz516 commented
@xrkffgg Run过了，没有变化。只改style不会有snapshot变动吧？

2020-06-10 04:37 UTC, xrkffgg approved these changes

2020-06-10 04:44 UTC, merged