refactor(Grid): rewrite with hook
ant-design/ant-design pull request #24976
Opened 2020-06-13 16:24 UTC by fireairforce

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     使用hooks重构Grid      |
| 🇨🇳 Chinese |     refactor Grid with hooks     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-06-14 06:29 UTC, Rustin-Liu commented
你的 changelog 中英文写反了

2020-06-14 06:34 UTC, 0xPoe requested changes

2020-06-14 06:34 UTC, Rustin-Liu commented on components/grid/row.tsx
> +
可以在这个地方加一下 displayName

2020-06-14 06:42 UTC, fireairforce commented
搞定了～done

2020-06-14 06:46 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
能不能想想其他办法测试一下这部分逻辑呢？

2020-06-14 06:52 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
看了hooks测试的一些文章只能转换去测其他的值，但这里的这个相关的token值是函数内部的变量取不到，不知道怎么转换去测试这部分逻辑= =

2020-06-14 06:53 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
为什么要删除这个用例呢？

2020-06-14 06:54 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
可以尝试去测试 unsubscribe 的逻辑，验证到底有没有触发就可以了

2020-06-14 07:06 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
还是因为函数组件里面没有state这个原因吧，这里没办法去更改state

2020-06-14 07:26 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
如果这个地方想测试大尺寸，你可以尝试模拟 window resize， 看看会不会有效果。

2020-06-14 07:27 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
这个不是尺寸，这里没有元素出来。。。改变的是一些margin值。。。

2020-06-14 07:28 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
之前这里的测试其实就是利用组件里面的一个函数在做，但现在拿不到state也取不到instance的函数值了。。。所以这里就不能这样测试了。

2020-06-14 07:37 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
是的，但是你可以模拟触发 window 的 resize ，然后再去校验这个逻辑，不用手动去设置 state。如果你的监听订阅有效的话，和你在网页上resize是一个逻辑。 试试看 :stuck_out_tongue_winking_eye:

2020-06-14 14:48 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
`wrapper.find('xxx').props()` 更精细的比较

2020-06-14 14:56 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
好的，我try一try

2020-06-14 15:14 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
done了~

2020-06-14 15:18 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
但实际没办法测函数式组的卸载？然后去监听到unsubscribe的变化？

2020-06-14 15:30 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
因为这里的值都是封闭在组件内部的，这里也没有明显的视图变化。

2020-06-14 15:32 UTC, fireairforce commented
rebase了

2020-06-14 15:39 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
感觉这个地方还是没测试到变化。

2020-06-15 02:34 UTC, fireairforce commented
这里测试有个问题，我看了antd其他测试的代码以及谷歌了一下也没有找到，大概是这样的：测试的时候怎么去模拟网页的视图变化，然后去测`Grid`的一个适配的case，`window.innerWidth`以及`resizeTo`都使用多种方法尝试过了，但好像并没有起作用。

2020-06-15 02:44 UTC, Rustin-Liu commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
可以参考下这个 https://github.com/agilgur5/window-resizeto

2020-06-15 02:45 UTC, Rustin-Liu commented
> 
> 
> 这里测试有个问题，我看了antd其他测试的代码以及谷歌了一下也没有找到，大概是这样的：测试的时候怎么去模拟网页的视图变化，然后去测`Grid`的一个适配的case，`window.innerWidth`以及`resizeTo`都使用多种方法尝试过了，但好像并没有起作用。

可以参考下这个 https://github.com/agilgur5/window-resizeto

2020-06-15 05:26 UTC, fireairforce commented
楼上那种`Obejct.assign`的方式也试过了。。。

2020-06-15 06:19 UTC, fireairforce commented
我晚上找找其他的解决方案吧。

2020-06-15 13:31 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
这边 resize 看起来比的数值是一样的？

2020-06-15 14:34 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
嗯嗯，就是这个地方QuQ

2020-06-15 14:39 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
https://codesandbox.io/s/jovial-gareth-9yx32?file=/index.js:507-530
其实这里要是能模拟出这个demo在不同视窗的切换情况，这个例子就差不多可以测试到了

2020-06-15 15:12 UTC, fireairforce commented
我感觉可能是我重构代码出现了一些问题，我对着官网重新debug一下。

2020-06-15 16:14 UTC, fireairforce commented
重新调了一下逻辑，逻辑应该没什么问题了。。。感觉这个测试还是不知道怎么resizeTo。。。

2020-06-16 10:53 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
这个测试用例可以调整成初始化时是一个小的尺寸比较小 gutter，然后 resizeTo 一个大的尺寸，然后再比较下新的 gutter。这样更健壮些。

2020-06-16 11:05 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when typeof gutter is object array in large screen', () => {
嗯嗯，这里是打算这么写

2020-06-16 16:03 UTC, fireairforce commented
这地方我查了下[网上](https://stackoverflow.com/questions/46221210/jest-enzyme-how-to-test-at-different-viewports/51997030)关于测试resizeTo窗口的情况，同时自己也试了几种方法，发现都不能实现函数式组件模拟这种窗口切换，看 stackoverflow 上别人用这种能测试成功是因为这个是按照 react 里面的生命周期函数设计的：
![image](https://user-images.githubusercontent.com/32598811/84798079-1de84680-b02d-11ea-9c5c-fef3fcfdee28.png)
所以上面那个测试那里用了生成快照的方式，因为对比了一下使用render生成快照的方式以及之前测试直接调用class component 里面的 `getGutter` 函数来计算值的方式是等效的，具体见图：

![image](https://user-images.githubusercontent.com/32598811/84798672-d1513b00-b02d-11ea-87a3-bb6f31326977.png)

![image](https://user-images.githubusercontent.com/32598811/84798689-d4e4c200-b02d-11ea-853c-7d0bc01cfac3.png)
所以我觉得这里可以这样取代一下，因为同样达到了那条测试 "when typeof gutter is object array in large screen" 的目的。。。。

2020-06-17 08:22 UTC, fireairforce commented
这里没其他啥问题了，大佬有空的话可以瞅一瞅🤔

2020-06-18 14:32 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
也是用 style 来比较

2020-06-18 14:33 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
spyOn  ResponsiveObserve 的 unsubscribe 来测

2020-06-18 14:33 UTC, zombieJ commented on components/grid/col.tsx
> +Col.displayName = 'Col';
fowardRef

2020-06-18 14:35 UTC, zombieJ commented on components/grid/row.tsx
> +  gutter: 0,
挪到上面做默认值以减少 bundle size

2020-06-18 14:35 UTC, zombieJ commented on components/grid/row.tsx
> +Row.displayName = 'Row';
forwardRef

2020-06-18 16:25 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
这个 `gutter` 传对象数组的时候只能用 render 去把 snapshot 结果渲染出来，用 mount 去取 style 这里得出来的值和原来的值是不准确的。

2020-06-18 16:25 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
好的，这个可以试一下。

2020-06-18 16:39 UTC, fireairforce commented on components/grid/col.tsx
> +Col.displayName = 'Col';
这个组件没用到ref...这个好像可以删掉。。

2020-06-18 16:56 UTC, fireairforce commented on components/grid/row.tsx
> +  gutter: 0,
好的

2020-06-18 16:56 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> -  it('when component has been unmounted, componentWillUnmount should be called', () => {
已添加~

2020-06-18 16:58 UTC, fireairforce commented
重新改了一下，应该看上去还可以了~

2020-06-20 14:51 UTC, fireairforce commented
/rebase，PTAL

2020-06-21 05:10 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
`wrapper.update()` 强制刷新一下试试看

2020-06-21 05:11 UTC, zombieJ commented
`forwardRef` 还是木有添加……

2020-06-21 06:03 UTC, fireairforce commented
> `forwardRef` 还是木有添加……

已加，抱歉，之前有点没理解。

2020-06-21 06:14 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
![image](https://user-images.githubusercontent.com/32598811/85218075-57240c00-b3c9-11ea-83e9-51fcf9403949.png)

也不行，最后得出的结果确实不准确。。对比了下之前的class组件，class组件如果不去改变state的话，得出的结果和这边也是一样的。这里就试了一下就只有直接 `render` 出来的结果和预期符合。

2020-06-21 09:11 UTC, zombieJ commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
render 是初始化什么样子它就什么样子，这样的话其实并没有测到 screen 里的变化，我看看哪里是需要调整的。

2020-06-21 09:13 UTC, zombieJ commented on components/grid/row.tsx
> +  React.useEffect(() => {
这个 `useEffect` 和 `componentDidMount` 不等价，相当于每次 render 都重新 subscribe 一遍，把 gutter 作为 condition 再试试

2020-06-21 09:31 UTC, fireairforce commented on components/grid/row.tsx
> +  React.useEffect(() => {
这样好像也不行，已经修改了，这样还是不行。。

2020-06-21 12:31 UTC, fireairforce commented on components/grid/__tests__/index.test.js
> +    expect(wrapper).toMatchSnapshot();
原组件是改内部组件 state 绕开了这个变化测试，感觉这里很奇怪，在jest `mount`出来的style里面的 margin 值都是按照`xs`的值来设定的，改变innerWith也不会对真实的响应式造成什么影响。

2020-06-24 04:59 UTC, 07akioni commented on components/grid/row.tsx
> +  React.useEffect(() => {
传进来的 gutter 可能是个字面量，每次的引用是会变的，所以不管用。

2020-06-24 05:05 UTC, 07akioni commented on components/grid/row.tsx
> +  React.useEffect(() => {
解决方式可以是把 gutter 转化为一个基本类型，然后把转化之后的 value 作为依赖。最简单的方式是 JSON.stringify(gutter)。

2020-06-24 05:40 UTC, zombieJ commented on components/grid/row.tsx
> +  React.useEffect(() => {
直接 useRef 把 gutter 传进去好了，subscribe 也应该只有第一次 mount 才需要。

2020-06-24 16:45 UTC, fireairforce commented on components/grid/row.tsx
> +  React.useEffect(() => {
我这里的意思是测试响应式变化和这里修改好像没关系。。。因为原 class 组件也没起作用。。。

2020-06-26 06:19 UTC, zombieJ commented on components/grid/row.tsx
> +  React.useEffect(() => {
我这里提的是它和 `componentDidMount` 不等价，和测试没有关系。所以建议是通过 ref 把数据放到 `useEffect` 里，本身只注册一次。

2020-06-26 06:29 UTC, fireairforce commented on components/grid/row.tsx
> +  React.useEffect(() => {
嗯嗯好的嘿嘿嘿

2020-06-27 15:38 UTC, fireairforce commented on components/grid/row.tsx
> +  React.useEffect(() => {
done~

2020-06-28 11:27 UTC, zombieJ commented on components/grid/row.tsx
> +  }, [gutterRef.current]);
意思是 ref 里取值，不用再走 props 了，条件里也不需要设置 gutter。

``` diff
  const gutterRef = React.useRef(gutter);
+ gutterRef.current =gutter;

  useEffect(() => {
    \\ ...
-   const { gutter = 0 } = props;
+   const currentGutter = gutterRef.current || 0;
    \\ ...

- }, [gutterRef.current]);
+ }, []);
```

2020-06-28 13:51 UTC, fireairforce commented on components/grid/row.tsx
> +  }, [gutterRef.current]);
好的，已经更新了～

2020-07-02 13:36 UTC, hengkx commented on components/grid/col.tsx
> +  const renderCol = ({ getPrefixCls, direction }: ConfigConsumerProps) => {
应该可以直接使用`useContext`吧

2020-07-02 13:37 UTC, hengkx commented on components/grid/row.tsx
> +  const renderRow = ({ getPrefixCls, direction }: ConfigConsumerProps) => {
`useContext`

2020-07-02 13:38 UTC, hengkx commented
冲突了 `rebase` 下

2020-07-02 14:13 UTC, zombieJ commented on components/grid/col.tsx
> +  const renderCol = ({ getPrefixCls, direction }: ConfigConsumerProps) => {
嗯，的确不需要 Consumer 了

2020-07-10 09:38 UTC, merged