feat: support Modal.config for prefixCls
ant-design/ant-design pull request #25603
Opened 2020-07-13 10:00 UTC by afc163

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/25586
close https://github.com/ant-design/ant-design/issues/22886

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add `Modal.config` to set `prefixCls` for Modal statis methods.  |
| 🇨🇳 Chinese | 新增 `Modal.config` 用于全局配置 Modal 静态方法的 `prefixCls`.  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-07-13 13:12 UTC, zombieJ commented on components/message/index.zh-CN.md
> +| prefixCls | 消息节点的 className 前缀 | string | 'ant-message' |
版本信息

2020-07-13 13:13 UTC, zombieJ approved these changes

2020-07-13 16:13 UTC, fireairforce approved these changes

2020-07-13 23:58 UTC, Geczy commented on components/modal/confirm.tsx
> +          prefixCls={getPrefixCls(prefixCls)}
`prefixCls={prefixCls || 'ant-modal'}` would be better

2020-07-14 01:28 UTC, xrkffgg requested changes

2020-07-14 01:28 UTC, xrkffgg commented on components/message/index.en-US.md
> +| prefixCls | prefix className of message node | string | 'ant-message' |
```suggestion
| prefixCls | prefix className of message node | string | `ant-message` |
```

2020-07-14 01:28 UTC, xrkffgg commented on components/message/index.zh-CN.md
> +| prefixCls | 消息节点的 className 前缀 | string | 'ant-message' |
```suggestion
| prefixCls | 消息节点的 className 前缀 | string | `ant-message` |
```

2020-07-14 01:28 UTC, xrkffgg commented on components/message/index.en-US.md
> +| prefixCls | prefix className of message node | string | 'ant-message' |
Version

2020-07-14 01:30 UTC, xrkffgg commented
我直接来改了吧

2020-07-14 01:35 UTC, xrkffgg approved these changes

2020-07-14 01:36 UTC, xrkffgg commented on components/message/index.en-US.md
> +| prefixCls | prefix className of message node | string | `ant-message` | 4.5.0 |
```suggestion
| prefixCls | The prefix className of message node | string | `ant-message` | 4.5.0 |
```

2020-07-14 03:14 UTC, merged

2020-08-06 10:22 UTC, zqjimlove commented on components/modal/ConfirmDialog.tsx
> -  const prefixCls = props.prefixCls || 'ant-modal';
为什么要删除这行，现在导致所有 Modal.comfrim 的弹窗都有样式问题