docs: changelog 4.5.0
ant-design/ant-design pull request #25820
Opened 2020-07-26 14:03 UTC by 07akioni

- Avatar
  - 🐞 Fix Avatar not fallback correctly when `src` is invalid. [#25806](https://github.com/ant-design/ant-design/pull/25806)
  - 🆕 Add Avatar.Group for showing a set of avatars. [#25192](https://github.com/ant-design/ant-design/pull/25192)
- DatePicker
  - 🛎 Adjust DatePicker doc to remove DatePicker.XxxPicker usage and add notice to recommend developer move to `picker='xxx'` instead. [#25768](https://github.com/ant-design/ant-design/pull/25768)
  - 🆕 improve DatePicker hovering experience, the placeholder will change to format value of target-date when hovering a date cell. ([#25050](https://github.com/ant-design/ant-design/issues/25050)). [#25784](https://github.com/ant-design/ant-design/pull/25784) [@Kermit-Xuan](https://github.com/Kermit-Xuan)
  - 🆕 RangePicker onCalendarChange info support. [#25568](https://github.com/ant-design/ant-design/pull/25568) [@Kim-Wing-Fung](https://github.com/Kim-Wing-Fung)
  - 🆕 DatePicker support `panelRender` to customize panel. [#25488](https://github.com/ant-design/ant-design/pull/25488)
- Form
  - 🐞 Fix Form.Item sometime not clean up prev error message. [#25737](https://github.com/ant-design/ant-design/pull/25737)
  - 🐞 Fix Form.Item not collect `validateStatus` when children Form.Item with `noStyle` has an error. [#25734](https://github.com/ant-design/ant-design/pull/25734)
  - 🐞 Fix Form.Item labelCol's offset isn't work if layout is vertical. [#25713](https://github.com/ant-design/ant-design/pull/25713) [@zhangchen915](https://github.com/zhangchen915)
  - 🆕 Form add `role="alert"` attribute to validation message node. [#25735](https://github.com/ant-design/ant-design/pull/25735) [@AlbertAZ1992](https://github.com/AlbertAZ1992)
  - 🆕 Form.List support array in remove method. [#25638](https://github.com/ant-design/ant-design/pull/25638) [@fireairforce](https://github.com/fireairforce)
  - 🆕 Form.Item supports `dependencies` to control updating logic with render props children. [#25408](https://github.com/ant-design/ant-design/pull/25408)
  - 🆕 Adjust Form.Item validateFist to validate in order. Origin logic use parallel to validate. [#25321](https://github.com/ant-design/ant-design/pull/25321)
- Calendar
  - 🐞 Fix Calendar validRange prevents disabledDate. [#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
  - Fix Calendar month select display. [#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
- 🐞 Fix Table `indeterminate` returned by `getCheckboxProps` not working. [#25649](https://github.com/ant-design/ant-design/pull/25649)
- 🐞 Fix Select clear icon position in Form.Item. [#25728](https://github.com/ant-design/ant-design/pull/25728)
- 🐞 Fix Pagination mouse style of the page turning button. [#25772](https://github.com/ant-design/ant-design/pull/25772)
- 🐞 Fix TreeSelect `treeNodeLabelProp` affect tree node render result. [#25755](https://github.com/ant-design/ant-design/pull/25755)
- 🐞 Fix Carousel `findDOMNode` warning in strict mode. [#25744](https://github.com/ant-design/ant-design/pull/25744)
- 🆕 Input and Input.TextArea support `bordered` prop. [#25617](https://github.com/ant-design/ant-design/pull/25617)
- 🆕 Add `useMessage` hook for Message to support `context` access. [#25422](https://github.com/ant-design/ant-design/pull/25422)
- 🆕 Tree support `titleRender` to customize tree node title with unique function. [#25624](https://github.com/ant-design/ant-design/pull/25624)
- 🆕 Descriptions add `extra` prop. [#25512](https://github.com/ant-design/ant-design/pull/25512) [@zzz111](https://github.com/zzz111)
- 🆕 Add `Modal.config` to set `rootPrefixCls` for Modal statis methods. [#25613](https://github.com/ant-design/ant-design/pull/25613)
- 🆕 Drawer support push prop for multi-Drawer linkage.([#21382](https://github.com/ant-design/ant-design/issues/21382)). [#25445](https://github.com/ant-design/ant-design/pull/25445) [@jinxin0112](https://github.com/jinxin0112)
- 🆕 Add Badge.Ribbon component. [#25456](https://github.com/ant-design/ant-design/pull/25456)
- 💄 Card action pane color is unified with body color. [#25722](https://github.com/ant-design/ant-design/pull/25722)
- 💄 **Menu.Item's blue indicator line and dropdown width are the same as its content's width in `horizontal` mode.** [#25622](https://github.com/ant-design/ant-design/pull/25622)
- ⌨️ Improve Alert/message/notification accessibility by adding role attribute. [#25774](https://github.com/ant-design/ant-design/pull/25774)
- 🇭🇰 Add zh-HK locale. [#7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)

---

- Avatar
  - 🐞 修复 Avatar `src` 图片地址失效时没有正确 fallback 的问题。[#25806](https://github.com/ant-design/ant-design/pull/25806)
  - 🆕 新增 Avatar.Group 用于展现一组头像集合。[#25192](https://github.com/ant-design/ant-design/pull/25192)
- DatePicker
  - 🛎 移除 DatePicker.XxxPicker 用法并于开发时推荐替换为 `picker='xxx'`。[#25768](https://github.com/ant-design/ant-design/pull/25768)
  - 🆕 提升日期组件悬停体验，当悬停在某个日期上时占位符将变为对应的日期格式化后的值。([#25050](https://github.com/ant-design/ant-design/issues/25050))。[#25784](https://github.com/ant-design/ant-design/pull/25784) [@Kermit-Xuan](https://github.com/Kermit-Xuan)
  - 🆕 RangePicker `onCalendarChange` 支持 info。[#25568](https://github.com/ant-design/ant-design/pull/25568) [@Kim-Wing-Fung](https://github.com/Kim-Wing-Fung)
  - 🆕 DatePicker 支持 `panelRender` 以自定义渲染面板。[#25488](https://github.com/ant-design/ant-design/pull/25488)
- Form
  - 🐞 修复 Form.Item 有时候没有清理之前的错误信息的问题。[#25737](https://github.com/ant-design/ant-design/pull/25737)
  - 🐞 修复 Form.Item 在子 Form.Item 设置 `noStyle` 并校验失败时没有更新 `validateStatus` 的问题。[#25734](https://github.com/ant-design/ant-design/pull/25734)
  - 🐞 修复 Form 垂直布局时 Form.Item 设置 labelCol offset 不生效。[#25713](https://github.com/ant-design/ant-design/pull/25713) [@zhangchen915](https://github.com/zhangchen915)
  - 🆕 Form 错误信息节点增加属性 `role="alert"`。[#25735](https://github.com/ant-design/ant-design/pull/25735) [@AlbertAZ1992](https://github.com/AlbertAZ1992)
  - 🆕 Form.List 中的 remove 方法支持数组类型。[#25638](https://github.com/ant-design/ant-design/pull/25638) [@fireairforce](https://github.com/fireairforce)
  - 🆕 Form.Item 在用 render props 作为 children 时支持使用 `dependencies` 控制更新逻辑。[#25408](https://github.com/ant-design/ant-design/pull/25408)
  - 🆕 调整 Form.Item validateFirst 属性为依次执行校验，原并行逻辑改由配置 parallel 开启。[#25321](https://github.com/ant-design/ant-design/pull/25321)
- Calendar
  - 🐞 修复 Calendar 组件的 validRange 导致 disabledDate 不生效 。[#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
  - 🐞 修复 Calendar 组件 MonthSelect 月份下拉筛选。[#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
- 🐞 修复 Table `getCheckboxProps` 返回的 `indeterminate` 不生效。[#25649](https://github.com/ant-design/ant-design/pull/25649)
- 🐞 修复 Select 清除按钮在 Form.Item 下位置不对的问题。[#25728](https://github.com/ant-design/ant-design/pull/25728)
- 🐞 修复 Pagination 翻页按钮的鼠标样式。[#25772](https://github.com/ant-design/ant-design/pull/25772)
- 🐞 修复 TreeSelect `treeNodeLabelProp` 会影响树节点展示内容的问题。[#25755](https://github.com/ant-design/ant-design/pull/25755)
- 🐞 修复 Carousel 在 React 严格模式下的 `findDOMNode` 废弃警告。[#25744](https://github.com/ant-design/ant-design/pull/25744)
- 🆕 Input 和 Input.TextArea 支持 `bordered` 属性。[#25617](https://github.com/ant-design/ant-design/pull/25617)
- 🆕 Message 新增 `useMessage` hook，以支持 `context` 访问。[#25422](https://github.com/ant-design/ant-design/pull/25422)
- 🆕 Tree 添加 `titleRender` 以支持全局设置 tree node 节点。[#25624](https://github.com/ant-design/ant-design/pull/25624)
- 🆕 Descriptions 新增 extra 属性。[#25512](https://github.com/ant-design/ant-design/pull/25512) [@zzz111](https://github.com/zzz111)
- 🆕 新增 `Modal.config` 用于全局配置 Modal 静态方法的 `rootPrefixCls`。[#25613](https://github.com/ant-design/ant-design/pull/25613)
- 🆕 Drawer 增加 `push` 属性用于自定义多层级 Drawer 之间的联动([#21382](https://github.com/ant-design/ant-design/iss [...]

2020-07-26 14:27 UTC, xrkffgg commented on CHANGELOG.en-US.md
> +  - 🆕 improve DatePicker hovering experience, the placeholder will change to format value of target-date when hovering a date cell. ([#25050](https://github.com/ant-design/ant-design/issues/25050)).
```suggestion
  - 🆕 Improve DatePicker hovering experience, the placeholder will change to format value of target-date when hovering a date cell. ([#25050](https://github.com/ant-design/ant-design/issues/25050)). [#25784](https://github.com/ant-design/ant-design/pull/25784) [@Kermit-Xuan](https://github.com/Kermit-Xuan)
```

2020-07-26 14:30 UTC, xrkffgg commented on CHANGELOG.en-US.md
> +  - Fix Calendar month select display. [#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
```suggestion
  - 🐞 Fix Calendar month select display. [#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
```

2020-07-26 14:32 UTC, xrkffgg commented on CHANGELOG.zh-CN.md
> +- 🆕 添加 Badge.Ribbon 缎带组件。[#25456](https://github.com/ant-design/ant-design/pull/25456)
新增？添加？

2020-07-27 02:33 UTC, afc163 commented
重要的改动放在前面。

2020-07-27 02:36 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🛎 移除 DatePicker.XxxPicker 用法并于开发时推荐替换为 `picker='xxx'`。[#25768](https://github.com/ant-design/ant-design/pull/25768)
和 #25768 的描述对不上。

2020-07-27 02:37 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🛎 移除 DatePicker.XxxPicker 用法并于开发时推荐替换为 `picker='xxx'`。[#25768](https://github.com/ant-design/ant-design/pull/25768)
另外补上：修复 `<QuarterPicker />` 无法使用的问题。

2020-07-27 02:37 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🆕 Descriptions 新增 extra 属性。[#25512](https://github.com/ant-design/ant-design/pull/25512) [@zzz111](https://github.com/zzz111)
```suggestion
- 🆕 Descriptions 新增 `extra` 属性。[#25512](https://github.com/ant-design/ant-design/pull/25512) [@zzz111](https://github.com/zzz111)
```

2020-07-27 02:59 UTC, afc163 commented on CHANGELOG.en-US.md
> +  - 🐞 Fix QuarterPicker not working. Update DatePicker doc to remove DatePicker.XxxPicker usage and add notice to recommend developer move to `picker='xxx'` instead. [#25768](https://github.com/ant-d
```suggestion
  - 🐞 Fix QuarterPicker not working, remove DatePicker.XxxPicker and recommend `picker='xxx'` usage instead. [#25768](https://github.com/ant-design/ant-design/pull/25768)
```

2020-07-27 03:10 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/25823
https://github.com/ant-design/ant-design/pull/25821

2020-07-27 03:13 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🆕 Drawer 增加 `push` 属性用于自定义多层级 Drawer 之间的联动([#21382](https://github.com/ant-design/ant-design/issues/21382))。[#25445](https://github.com/ant-design/ant-design/pull/25445) [@jinxin0112](https://githu
```suggestion
- 🆕 Drawer 增加 `push` 属性用于自定义多层级 Drawer 之间的联动。[#25445](https://github.com/ant-design/ant-design/pull/25445) [@jinxin0112](https://github.com/jinxin0112)
```

2020-07-27 03:13 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🆕 Tree 添加 `titleRender` 以支持全局设置 tree node 节点。[#25624](https://github.com/ant-design/ant-design/pull/25624)
```suggestion
- 🆕 Tree 添加 `titleRender` 以支持定制所有节点内容。[#25624](https://github.com/ant-design/ant-design/pull/25624)
```

2020-07-27 03:13 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🆕 Form 错误信息节点增加属性 `role="alert"`。[#25735](https://github.com/ant-design/ant-design/pull/25735) [@AlbertAZ1992](https://github.com/AlbertAZ1992)
```suggestion
  - ⌨️ Form 错误信息节点增加属性 `role="alert"` 以增强可访问性。[#25735](https://github.com/ant-design/ant-design/pull/25735) [@AlbertAZ1992](https://github.com/AlbertAZ1992)
```

2020-07-27 03:15 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🆕 RangePicker `onCalendarChange` 支持 info。[#25568](https://github.com/ant-design/ant-design/pull/25568) [@Kim-Wing-Fung](https://github.com/Kim-Wing-Fung)
这句话没有信息。

```suggestion
  - 🆕 RangePicker `onCalendarChange` 参数中增加 `range` 用于指示当前触发面板。[#25568](https://github.com/ant-design/ant-design/pull/25568) [@Kim-Wing-Fung](https://github.com/Kim-Wing-Fung)
```

2020-07-27 03:15 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🆕 Form.Item 在用 render props 作为 children 时支持使用 `dependencies` 控制更新逻辑。[#25408](https://github.com/ant-design/ant-design/pull/25408)
```suggestion
  - 🆕 Form.Item 在 `children` 形为 `render props` 时支持使用 `dependencies` 控制更新逻辑。[#25408](https://github.com/ant-design/ant-design/pull/25408)
```

2020-07-27 03:17 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Calendar 组件 MonthSelect 月份下拉筛选。[#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
```suggestion
  - 🐞 修复 Calendar 组件 `validRange` 对月份下拉菜单不生效的问题。[#25626](https://github.com/ant-design/ant-design/pull/25626) [@zhangchen915](https://github.com/zhangchen915)
```

2020-07-27 03:18 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +  - 🐞 修复 Form 垂直布局时 Form.Item 设置 labelCol offset 不生效。[#25713](https://github.com/ant-design/ant-design/pull/25713) [@zhangchen915](https://github.com/zhangchen915)
```suggestion
  - 🐞 修复 Form 垂直布局时 Form.Item 设置 `labelCol={{ offset: number }}` 不生效的问题。[#25713](https://github.com/ant-design/ant-design/pull/25713) [@zhangchen915](https://github.com/zhangchen915)
```

2020-07-27 03:53 UTC, yoyo837 commented on CHANGELOG.zh-CN.md
> +- 🇭🇰 新增 zh-HK 本地化。[#7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)
```suggestion
- 🇭🇰 新增 zh-HK 本地化。[7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)
```

2020-07-27 03:53 UTC, 07akioni commented on CHANGELOG.zh-CN.md
> +- 🇭🇰 新增 zh-HK 本地化。[#7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)
神奇，我找一下原始 PR

2020-07-27 03:54 UTC, yoyo837 commented on CHANGELOG.en-US.md
> +- 🇭🇰 Add zh-HK locale. [#7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)
```suggestion
- 🇭🇰 Add zh-HK locale. [7d7cbf8](https://github.com/ant-design/ant-design/commit/7d7cbf8) [@wuchu](https://github.com/wuchu)
```

2020-07-27 05:39 UTC, zombieJ commented
Lint failed : https://github.com/ant-design/ant-design/pull/25820/checks?check_run_id=913089269

2020-07-27 05:49 UTC, zombieJ commented
@Kermit-Xuan  搭一个？ 
https://github.com/react-component/picker/pull/109

2020-07-27 06:16 UTC, Kermit-Xuan commented
> @Kermit-Xuan 搭一个？
> [react-component/picker#109](https://github.com/react-component/picker/pull/109)

开了，这个不用更新changeLog，之前已经有了，现在是优化。

2020-07-27 06:30 UTC, afc163 commented
package.json 里改一下版本号。

2020-07-27 07:19 UTC, afc163 commented
https://github.com/react-component/steps/pull/118/ 检查检查有没有要发 feature 的，别错过车了。

2020-07-27 07:29 UTC, 07akioni commented
> [react-component/steps#118](https://github.com/react-component/steps/pull/118) 检查检查有没有要发 feature 的，别错过车了。

这个还没做完，不能发。别的我会查一下

2020-07-27 07:31 UTC, afc163 commented
https://github.com/react-component/steps/pull/118 这个得上车的，不然要等一个月，业务等不了。

2020-07-27 07:36 UTC, afc163 requested changes
- [x] https://github.com/ant-design/ant-design/pull/25823
- [x] https://github.com/ant-design/ant-design/pull/25821

还有 rc-xxx 等相关依赖要升级到最新，比如 https://github.com/react-component/input-number/releases/tag/v6.0.0

2020-07-27 07:36 UTC, 07akioni commented
> [react-component/steps#118](https://github.com/react-component/steps/pull/118) 这个得上车的，不然要等一个月，业务等不了。

我催催，看看能不能今天弄好

2020-07-27 08:04 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/25822

2020-07-27 12:22 UTC, 07akioni commented
> * [ ]  #25823
> * [ ]  #25821
> 
> 还有 rc-xxx 等相关依赖要升级到最新，比如 https://github.com/react-component/input-number/releases/tag/v6.0.0

这个 6.0 是使用 father 的重构，CI 还没跑通，估计今晚上车困难。

2020-07-27 12:33 UTC, Kermit-Xuan commented
> CI 还没跑通。功能没变化，感觉不用非得今天上。

CI出什么问题了？

2020-07-27 14:21 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/25827

2020-07-27 14:26 UTC, afc163 commented on CHANGELOG.zh-CN.md
> +- 🇩🇪 改进 de_DE 本地化。[#25823](https://github.com/ant-design/ant-design/pull/25823) [@LukeTimeWalker](https://github.com/LukeTimeWalker)
Form 国际化这个的写法都可以参考 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/507615/88553771-3d28b980-d058-11ea-93ff-5e7075d4dedf.png">

2020-07-27 14:34 UTC, 07akioni commented on CHANGELOG.zh-CN.md
> +- 🇩🇪 改进 de_DE 本地化。[#25823](https://github.com/ant-design/ant-design/pull/25823) [@LukeTimeWalker](https://github.com/LukeTimeWalker)
我感觉“本地化”比“国际化”用词更安全一些，你觉得？

2020-07-27 14:40 UTC, zombieJ approved these changes

2020-07-27 15:05 UTC, merged