feat: Statistic.Countdown pause and start api
ant-design/ant-design pull request #26229
Opened 2020-08-16 12:30 UTC by zhangchen915

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #26182 

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Statistic.Countdown pause and start      |
| 🇨🇳 Chinese |      Statistic.Countdown 增加开始和暂停      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-08-16 12:58 UTC, xrkffgg reviewed
feature branch

2020-08-17 01:02 UTC, xrkffgg commented
rebase featrue 后
`git push -f`

2020-08-17 01:03 UTC, xrkffgg commented
另外建议改用 hooks

2020-08-17 11:51 UTC, zhangchen915 commented
rebase 到 featrue 发现 CI 有点问题，改用 hooks 是改成函数式组件吗？

2020-08-17 11:58 UTC, xrkffgg commented
嗯，Statistic 已经改了，可以把 Countdown 也改一下

2020-08-17 13:40 UTC, zombieJ commented
为啥需要 `autoStart`?

2020-08-17 13:42 UTC, zombieJ commented
这样设计 `value` 就不受控了

2020-08-18 13:52 UTC, xrkffgg commented on components/statistic/Countdown.tsx
> +  const [, forceUpdate] = React.useState({});
forceUpdate 可以等一下 https://github.com/ant-design/ant-design/pull/26270 结果

2020-08-25 03:20 UTC, zombieJ requested changes

2020-08-25 03:20 UTC, zombieJ commented on components/statistic/index.en-US.md
> +| pause() | Pause countdown |         |
不要提供方法出来，会让 `value` 非受控。提供一个 `disabled` 属性，设置后停止计时器，让用户恢复时重新提供一个新的 `value`。

2020-08-25 03:24 UTC, zhangchen915 commented on components/statistic/index.en-US.md
> +| pause() | Pause countdown |         |
好的

2020-08-25 03:48 UTC, afc163 commented on components/statistic/index.en-US.md
> +| pause() | Pause countdown |         |
paused 如何？

2020-08-31 09:47 UTC, zombieJ commented
@zhangchen915

2020-09-02 01:40 UTC, hengkx commented on components/statistic/index.en-US.md
> +| pause() | Pause countdown |         |
paused 感觉 更符合 这个操作一些

2021-01-30 15:08 UTC, xrkffgg commented
有冲突，rebase 下最新的

2021-04-25 09:41 UTC, afc163 commented
Closing for no further progress, feel free to open new pull request: https://github.com/ant-design/ant-design/pull/26229#discussion_r476109433

2021-04-25 09:41 UTC, closed without merging