fix: Badge not work when props.color is empty
ant-design/ant-design pull request #26375
Opened 2020-08-24 16:25 UTC by zhangchen915

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #26363 

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-08-25 00:59 UTC, xrkffgg commented
changelog 写一下

2020-08-25 06:46 UTC, afc163 commented
给个用例。

2020-08-25 13:42 UTC, xrkffgg requested changes
https://github.com/ant-design/ant-design/issues/26363#issuecomment-680031022

这个一起修了吧

2020-08-26 03:26 UTC, zhangchen915 commented
嗯，用例也加上了

2020-08-26 03:27 UTC, merged