docs: improve from list
ant-design/ant-design pull request #26675
Opened 2020-09-10 06:39 UTC by hengkx

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2020-09-10 08:27 UTC, zombieJ commented
这个例子改动目的是？

2020-09-10 08:28 UTC, hengkx commented
复杂一些的 实现， 找不到 demo

2020-09-10 08:45 UTC, zombieJ commented
加一个单独的例子好了，只提供 Select 里的 disabled 效果。这样方便理解。

2020-09-10 09:57 UTC, hengkx commented
单独的disabled没有 必要吧 就一个 属性 没什么 特别，本来 写这一块的时候 就想找找 复杂一点的 例子，没有 找到。 或者 拿出来 增加一下 详细描述？

2020-09-11 13:30 UTC, zombieJ commented
前段时间也有人问过，加吧，这样有人需要也可以学习一下。例子分开是为了降低学习成本，太多了看不过来~

2020-09-12 11:56 UTC, dengfuping requested changes
- Another single demo is required.

2020-09-14 06:40 UTC, zombieJ commented
@hengkx  ~

2020-09-14 06:58 UTC, hengkx commented
我不知道 新的 demo 取什么名字😂

2020-09-14 07:04 UTC, zombieJ commented
动态表单联动禁用选项？

2020-09-14 10:29 UTC, afc163 commented
<img width="638" alt="image" src="https://user-images.githubusercontent.com/507615/93075320-344b8000-f6b8-11ea-9144-7eb2c3329379.png">

这个间距应该是不符合 24px 的规范的。

2020-09-14 10:30 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +                  />
```suggestion
                  <MinusCircleOutlined onClick={() => remove(field.name)} />
```

2020-09-14 10:31 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
fieldKey 是啥？antd form 文档中没有相关介绍。

2020-09-14 10:32 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +  zh-CN: 动态表单联动
```suggestion
  zh-CN: 复杂的动态增减表单项
```

2020-09-14 10:33 UTC, hengkx commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
没有他好像也可以 没去 研究过干啥的 @zombieJ

2020-09-14 10:33 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +嵌套表单字段需要对 `field` 进行拓展，将 `field.name` 和 `field.fieldKey` 应用于控制字段。
这个例子演示了一个表单列中包含多个表单控件的情况。

2020-09-14 10:33 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +                        <Select disabled={!form.getFieldValue('type')} style={{ width: 100 }}>
disabled 不需要有，纯粹演示一列多字段就可以了。

2020-09-14 10:36 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +        <Select options={options} onChange={handleChange} />
补充 label，使例子像一个真实场景。

2020-09-15 01:48 UTC, afc163 commented on components/form/demo/dynamic-form-items-complex.md
> +            <div>
```suggestion
            <>
```

2020-09-15 01:49 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
没用就去掉。

2020-09-15 01:49 UTC, hengkx commented on components/form/demo/dynamic-form-items-complex.md
> +            <div>
应该可以

2020-09-15 13:04 UTC, zombieJ commented on components/form/demo/dynamic-form-items-complex.md
> +const data = [];
这个是不是没用到了？

2020-09-17 02:09 UTC, hengkx commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
@zombieJ 有用吗

2020-09-17 05:22 UTC, zombieJ commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
`noStyle` 下有用，这个可以冗余。免得别人照着改成 `noStyle` 后发现错误展示不正确了。

2020-09-17 05:24 UTC, afc163 commented on components/form/demo/dynamic-form-items-link.md
> +                        fieldKey={[field.fieldKey, 'type']}
文档里要提供一下属性的说明。

2020-09-17 05:39 UTC, hengkx commented
这分支是不是 被我 玩 坏了😂

2020-09-18 06:23 UTC, zombieJ commented
开个新的 cherry pick 一下……

2020-09-18 07:51 UTC, closed without merging