feat: TextArea showCount
ant-design/ant-design pull request #26952
Opened 2020-09-29 18:22 UTC by zhangchen915

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24940

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     TextArea show text count      |
| 🇨🇳 Chinese |    TextArea  展示字数统计     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-10-03 05:15 UTC, afc163 approved these changes

2020-10-03 05:24 UTC, afc163 requested changes
showCount 只有在 maxLength 存在时才有用，API 改成这样吧 `maxLength={{ showCount: true, value: 100 }}`，maxLength 为数字时依然有效。

2020-10-03 08:54 UTC, zhangchen915 commented
> showCount 只有在 maxLength 存在时才有用，API 改成这样吧 `maxLength={{ showCount: true, value: 100 }}`，maxLength 为数字时依然有效。

需要兼容 `maxLength=100` 这种吗，以前应该是这么写的

2020-10-04 13:58 UTC, afc163 commented
需要，我上面写了。

2020-10-04 21:34 UTC, ZhangJian-3ti commented
@zhangchen915 @afc163 这个地方showCount不一定会搭配maxlength使用。我们有时候就是只要显示用户输入了多少字符，但并不需要设置maxlength。

2020-10-06 18:12 UTC, afc163 commented on components/input/TextArea.tsx
> +          : {})}
提一些变量出来，现在的写法有点太复杂了。

2020-10-06 18:13 UTC, afc163 commented
> @zhangchen915 @afc163 这个地方showCount不一定会搭配maxlength使用。我们场景有时候就是只要显示用户输入了多少字符，但并不需要设置maxlength。因此希望保留现有的设置方式不要并入到maxlength，并且现有的API组合使用起来也更简单一些。

这样也行，那就是不设置 maxLength 的 showCount 只展示字数，不显示限制。

2020-10-07 08:39 UTC, zhangchen915 commented on components/input/TextArea.tsx
> +          : {})}
Done

2020-10-07 08:41 UTC, zhangchen915 commented
CI 好像有点问题

2020-10-09 13:39 UTC, afc163 commented
rebase 一下 feature 分支。

2020-10-10 03:30 UTC, afc163 approved these changes

2020-10-10 03:30 UTC, merged

2020-10-12 02:04 UTC, crazyair commented
这个长度需要支持中文全角区分吗

2020-10-27 05:29 UTC, xqGosky commented
<TextArea  showCount maxLength={200} /> 不显示计数 并报警告
Warning: React does not recognize the `showCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showcount` instead. If you accidentally passed it from a parent component, remove it from the DOM element