Update data-format.zh-CN.md
ant-design/ant-design pull request #26969
Opened 2020-09-30 08:02 UTC by yucongroopher

文档说明中的一些*符号没有完整显示

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [*] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2020-09-30 08:18 UTC, xrkffgg commented on docs/spec/data-format.zh-CN.md
> +| 身份证号码 | 公民身份号码由六位地址码，八位出生日期码，三位顺序码和一位校验码组成。脱敏规则分为高、中、低级：<br />高级：保留前一位与后一位，其余「\*」表示，仅能识别该人属于哪个地区。<br />中级：保留前三位与后三位，其余「\*」表示，仅能识别该人的省市与是男是女。<br />低级：保留前六位与后四位，其余「\*」表示，仅能识别该人的省市区与是男是女。 | 6\*\*\*\*\
辛苦一下，把这块的 cn en 都统一成  `*` 的形式吧 😄

2020-09-30 08:25 UTC, yucongroopher commented on docs/spec/data-format.zh-CN.md
> +| 身份证号码 | 公民身份号码由六位地址码，八位出生日期码，三位顺序码和一位校验码组成。脱敏规则分为高、中、低级：<br />高级：保留前一位与后一位，其余「\*」表示，仅能识别该人属于哪个地区。<br />中级：保留前三位与后三位，其余「\*」表示，仅能识别该人的省市与是男是女。<br />低级：保留前六位与后四位，其余「\*」表示，仅能识别该人的省市区与是男是女。 | 6\*\*\*\*\
补上了

2020-09-30 08:50 UTC, xrkffgg commented
https://github.com/ant-design/ant-design/pull/26972

两个 PR 放一起改好了

PS: cn 的风格改一下

2020-09-30 12:08 UTC, xrkffgg requested changes
en 改一下，cn 完善一下

2020-10-01 02:16 UTC, xrkffgg commented on docs/spec/data-format.zh-CN.md
> +| 专用名词 | 含有月日的专用名词采用阿拉伯数字表示时，应采用间隔号 `·` 将月、日分开，并在数字前后加引号。 | “6.1 儿童节” |
```suggestion
| 专用名词 | 含有月日的专用名词采用阿拉伯数字表示时，应采用间隔号 `·` 将月、日分开，并在数字前后加引号。 | 6.1 儿童节 |
```

2020-10-01 02:16 UTC, xrkffgg commented on docs/spec/data-format.en-US.md
> +| Bank card number | The bank card number consists of the issuing bank identification code (ranging from 6 to 12 digits), personal account identification (ranging from 6 to 12 digits), and a check co
例子里的就不加 ` ` 了。en 这里可以统一成 cn 的风格~

2020-10-01 02:18 UTC, yucongroopher commented on docs/spec/data-format.en-US.md
> +| Bank card number | The bank card number consists of the issuing bank identification code (ranging from 6 to 12 digits), personal account identification (ranging from 6 to 12 digits), and a check co
好。稍后改成统一风格。

2020-10-02 05:20 UTC, hengkx commented
![image](https://user-images.githubusercontent.com/8358236/94890492-f28d4880-04b1-11eb-8b9e-6a8497c45481.png)
是不是改成`***`好些

2020-10-02 10:32 UTC, yucongroopher commented
> ![image](https://user-images.githubusercontent.com/8358236/94890492-f28d4880-04b1-11eb-8b9e-6a8497c45481.png)
> 是不是改成`***`好些

我个人觉得确实是这样。「」本身也是符号，其实仔细读的话，也会让人产生歧义。

2020-10-02 12:08 UTC, xrkffgg commented
有一些没有改全，比如 只改了全部脱敏，而相应的部分脱敏没有改。建议当前页面都过一下，防止遗漏。

- “6.1 儿童节” 去掉 “” 

- 相对时间里还使用了 「12-08 08:00」

- 表格中 “如何使用及何时使用” 中 使用 `` ，例子中 直接展示

2020-10-03 03:46 UTC, xrkffgg approved these changes

2020-10-03 03:47 UTC, merged