feat: Modal.method support afterClose
ant-design/ant-design pull request #28053
Opened 2020-11-27 11:50 UTC by liuchao233

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Modal.method support afterClose |
| 🇨🇳 Chinese | Modal.method 支持 afterClose 属性 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-11-30 04:38 UTC, afc163 approved these changes

2020-11-30 04:54 UTC, afc163 requested changes

2020-11-30 04:54 UTC, afc163 commented on components/modal/confirm.tsx
> +          config.afterClose();
测试没覆盖到这一行。

2020-12-05 15:07 UTC, afc163 commented on components/modal/index.zh-CN.md
> +>>>>>>> a8c9b571edd85b6609a8771ed150f456556bd620
conflict

2020-12-06 01:10 UTC, liuchao233 commented on components/modal/index.zh-CN.md
> +>>>>>>> a8c9b571edd85b6609a8771ed150f456556bd620
sorry, my fault

2020-12-06 12:50 UTC, afc163 commented on components/modal/index.en-US.md
> +>>>>>>> a8c9b571edd85b6609a8771ed150f456556bd620
Please check changes carefully.

2020-12-07 05:43 UTC, afc163 approved these changes

2020-12-07 05:44 UTC, merged