Add km_KH locale to component
ant-design/ant-design pull request #32853
Opened 2021-11-14 08:01 UTC by vireakkeosokvibol

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (Localization)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-11-15 08:48 UTC, afc163 commented
Could you add test case?

2021-11-15 10:49 UTC, vireakkeosokvibol commented
> Could you add test case?

Do really apologize. Can anybody has experience with test unit help contribute the test? I'm really appreciated to the contribution.

2021-11-15 10:54 UTC, yoyo837 commented
FYI https://github.com/ant-design/ant-design/pull/32106#issuecomment-915964752

2021-11-15 10:57 UTC, yoyo837 commented
Some time later, a detailed docs about add a new locale will be added.

2021-11-15 17:49 UTC, vireakkeosokvibol commented
> Some time later, a detailed docs about add a new locale will be added.

I'm done with the test unit and docs. But for about **i18n.zh-CH.md** i'm not really sure what Khmer mean in Chinese assuming its **高棉语**. Please have a correction if its wrong.

2021-11-16 01:19 UTC, yoyo837 commented
> > FYI #32106 (comment)
> 
> I'm done with the test unit and docs. But for about **i18n.zh-CH.md** i'm not really sure what Khmer mean in Chinese assuming its **高棉语**. Please have a correction if its wrong.

It's right.

2021-11-16 02:48 UTC, afc163 commented
feature branch please.

2021-11-16 10:41 UTC, vireakkeosokvibol commented
Already switch branch to feature

> feature branch please.

2021-11-17 07:52 UTC, afc163 commented on components/input/style/mixin.less
> +    }
Mixed other commits.

2021-11-18 06:07 UTC, afc163 commented
<img width="618" alt="图片" src="https://user-images.githubusercontent.com/507615/142361467-dd7a26b0-1e6f-4fdb-8298-f95ecea0a6dc.png">

This commit is not belong to your changes.

2021-11-19 10:02 UTC, vireakkeosokvibol commented
@afc163 can you suggest a revision to pass all the CI pipeline ?

2021-11-19 10:04 UTC, yoyo837 commented
Rebase origin/feature and push by force.

2021-11-19 11:20 UTC, vireakkeosokvibol commented
> Rebase origin/feature and push by force.

Done rebase. Thank for your suggestion.

2021-11-19 11:25 UTC, yoyo837 commented
Looks like you still need:
1. Rebase origin/feature and push by force. (You already did.)
2. `rm -rf node_modules`
3. `npm install`
4. `npm test -- -u`
5. Push all file changes.

2021-11-19 14:34 UTC, afc163 requested changes
<img width="618" alt="图片" src="https://user-images.githubusercontent.com/507615/142361467-dd7a26b0-1e6f-4fdb-8298-f95ecea0a6dc.png">

This commit is not belong to your changes.

2021-11-19 14:51 UTC, vireakkeosokvibol commented
> <img alt="图片" width="618" src="https://user-images.githubusercontent.com/507615/142361467-dd7a26b0-1e6f-4fdb-8298-f95ecea0a6dc.png">
> 
> This commit is not belong to your changes.

Have dropped that commit.

2021-11-20 07:02 UTC, afc163 approved these changes

2021-11-20 07:02 UTC, merged