feat: dropdown support arrow pointing at center
ant-design/ant-design pull request #33658
Opened 2022-01-10 13:28 UTC by MadCcc

- feat: add pointAtCenter prop for dropdown
- feat: dropdown support arrow pointing at center

[[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue
https://github.com/ant-design/ant-design/issues/33507

### 💡 需求背景和解决方案

### 📝 更新日志

| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |Dropdown support arrow pointing at center|
| 🇨🇳 中文 |Dropdown 组件支持指向元素正中间|

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-01-10 13:34 UTC, MadCcc commented
这个单元测试实在是不知道咋写。。看了眼 tooltip 的 arrowPointAtCenter 对应的单元测试其实都没有生效 😂

2022-01-10 13:52 UTC, afc163 commented on components/dropdown/placements.ts
> +}
直接用 tooltip 的 getPlacements 如何？

2022-01-11 02:19 UTC, MadCcc commented on components/dropdown/placements.ts
> +}
> 直接用 tooltip 的 getPlacements 如何？

这两个的 placementMap 有些不太一样，试过直接用不太行。
不过理论上应该是可以复用的，可以和 tooltip 那边一起改下。

2022-01-11 02:38 UTC, afc163 commented on components/dropdown/placements.ts
> +}
小改动体积多了 213B 不太划算

2022-01-11 05:41 UTC, afc163 commented on components/dropdown/dropdown.tsx
> +    });
```suggestion
```suggestion

  const builtinPlacements = getPlacements({
    arrowPointAtCenter: typeof arrow === 'object' && arrow.pointAtCenter,
  });
```

然后下面直接 `builtinPlacements={builtinPlacements}`，这样是不是更直观一点。
```

2022-01-12 02:58 UTC, afc163 commented on components/dropdown/dropdown.tsx
> +  'bottom',
topCenter 和 bottomCenter 的用法可以废弃掉。

2022-01-13 02:59 UTC, afc163 requested changes
topCenter 和 bottomCenter 的用法可以废弃掉。

1. 文档中不体现。
2. 代码里给 warning。

2022-01-13 05:33 UTC, afc163 commented
@xrkffgg Preview 服务，代码修改后这里状态一直是 loading：https://github.com/ant-design/ant-design/pull/33658#issuecomment-1008874907

2022-01-13 05:34 UTC, afc163 approved these changes

2022-01-13 05:34 UTC, merged