Let Checkbox and Radio work with Popover directly
ant-design/ant-design pull request #3638
Opened 2016-10-28 08:06 UTC by yesmeck

Fix #3455

2016-10-28 08:16 UTC, afc163 requested changes

2016-10-28 08:16 UTC, afc163 commented on components/checkbox/index.tsx
>            {...restProps}
restProps 这里要排除掉，不然会运行两次。

2016-10-28 08:21 UTC, yesmeck commented on components/checkbox/index.tsx
>            {...restProps}
奥，对。

2016-10-28 08:46 UTC, yesmeck commented on components/checkbox/index.tsx
>            {...restProps}
感觉这里会有坑：

```javascript
import { Checkbox, Popover } from 'antd';

function handleClick(e) {
  console.log(e);
}

ReactDOM.render(
  <Popover content="Content" title="Title">
    <Checkbox onClick={handleClick}>Checkbox</Checkbox>
  </Popover>
, mountNode);
```

上面这种情况会导致 `Checkbox` 本身的 `onClick` 被 `Trigger` 覆盖掉。

2016-10-28 08:50 UTC, afc163 commented on components/checkbox/index.tsx
>            {...restProps}
没关系，onClick 只要触发了就行，不影响本身的逻辑。

2016-10-28 09:07 UTC, benjycui commented on components/_util/getTriggerHandlers.tsx
> +export default function getTriggerHandlers(props) {
写成个通用点的 pick 函数？ http://ramdajs.com/docs/#pick

2016-10-28 09:13 UTC, yesmeck commented on components/_util/getTriggerHandlers.tsx
> +export default function getTriggerHandlers(props) {
> 下面这几个 field 其实就是用户传入的 trigger

什么意思？这几个回调是 Trigger 传过来的。

2016-10-28 09:18 UTC, yesmeck commented on components/checkbox/index.tsx
>            {...restProps}
还有个问题就是如果在 antd 这边把 onClick 拦截下来的话，原来 rc-checkbox 的  onClick 是绑在 input 上的，现在绑在 antd 这边的 label 上了，其实行为跟之前不一样了。

2016-10-28 09:23 UTC, benjycui commented on components/_util/getTriggerHandlers.tsx
> +export default function getTriggerHandlers(props) {
忽略。。。看错。

2016-11-09 03:18 UTC, yesmeck commented
发现 Trigger 里对 onClick 做了 `event.preventDefaut()` https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L275 ，会导致下面的代码无法勾选：

```javascript
<Popover content="hello" trigger="click">
  <Checkbox>Check</Checkbox>
</Popover>
```

2016-11-14 03:51 UTC, yesmeck commented
原来的分支被我删了，我重新发个 PR。

2016-11-14 03:51 UTC, closed without merging