add searchable Tree demo
ant-design/ant-design pull request #3693
Opened 2016-11-02 07:47 UTC by ddcat1115

close #3563

2016-11-02 07:48 UTC, yesmeck commented
新增 Demo 统一用 ES6 的 class？

2016-11-02 08:05 UTC, ddcat1115 commented
目前的demo好像都是老的写法，如果不统一是不是不太好？比如用户需要这儿copy一点那copy一点的时候？

2016-11-02 08:06 UTC, yesmeck commented
@benjycui 后面是不是会把 demo 里的 js 独立出来？如果是的话那后面统一转换下好了。

2016-11-02 08:14 UTC, afc163 commented
可以，新的用 ES6 写法好了。

2016-11-02 08:24 UTC, ddcat1115 commented
ok，我改下好了，本来也要调整下

2016-11-03 05:57 UTC, afc163 requested changes
需按评论的进行修改。

2016-11-04 07:28 UTC, ddcat1115 commented
updated~

2016-11-04 07:35 UTC, afc163 approved these changes

2016-11-04 08:14 UTC, benjycui commented
顺手把 title 里面的 `[WIP]` 去掉？

2016-11-08 03:45 UTC, benjycui commented
ping~ @RaoHai

2016-11-09 06:45 UTC, merged

2016-12-12 09:10 UTC, EtachGu commented
Demo 中 当子节点是展开状态，父节点无法收缩