Anchor Component
ant-design/ant-design pull request #3720
Opened 2016-11-03 08:50 UTC by RaoHai

- close #3557

2016-11-04 07:15 UTC, yesmeck requested changes

2016-11-04 07:15 UTC, yesmeck commented on components/anchor/index.zh-CN.md
> +  </Anchor>
没对齐

2016-11-04 07:15 UTC, yesmeck commented on components/anchor/style/index.zh-CN.md
> +---
这个文件是多余的？

2016-11-05 08:21 UTC, yesmeck approved these changes

2016-11-05 08:21 UTC, yesmeck commented
@afc163 这个要放在 2.3.0 里吗？

2016-11-05 08:32 UTC, afc163 commented
看下完成度，没明显 bug 就上。

2016-11-05 09:47 UTC, yesmeck commented
@RaoHai  圆里的白点跟灰线没对齐的问题打算处理吗？

2016-11-05 09:55 UTC, yesmeck commented on components/anchor/demo/basic.md
> +    <AnchorLink href="#components-anchor-demo-independ" title="独立使用" />
Demo 里的文案是不是都写成英文？

2016-11-07 03:13 UTC, merged