update spin animation style
ant-design/ant-design pull request #3722
Opened 2016-11-03 10:01 UTC by jljsj33

2016-11-03 12:57 UTC, afc163 requested changes

2016-11-03 12:57 UTC, afc163 commented on components/spin/style/index.less
> +        left: 10px;
改成四个角落。

```
left: 0;
top: 0;
```

```
right: 0;
top: 0;
```

```
right: 0;
bottom: 0;
```

```
bottom: 0;
left: 0;
```

2016-11-04 03:57 UTC, jljsj33 commented on components/spin/style/index.less
> +        left: 10px;
不是一样吗，，，大爷的

2016-11-04 04:01 UTC, afc163 commented on components/spin/style/index.less
> +        left: 10px;
不一样，这样调整大小的时候，只要改外面的宽度就行了。

2016-11-04 04:09 UTC, jljsj33 commented on components/spin/style/index.less
> +        left: 10px;
改了

2016-11-04 05:43 UTC, afc163 approved these changes

2016-11-04 05:50 UTC, merged

2016-11-04 05:58 UTC, wangfengcool commented
greater