feat: update rc-steps
ant-design/ant-design pull request #38319
Opened 2022-11-01 03:07 UTC by heiyu4585

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      修复items 在方法外不能正确修改样式的问题     |
| 🇨🇳 Chinese |      fix items correct     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-11-01 14:33 UTC, afc163 approved these changes

2022-11-01 15:04 UTC, afc163 requested changes

2022-11-01 15:04 UTC, afc163 commented on components/steps/__tests__/index.test.tsx
> +    expect(screen.getByText(/进行中/i)).toHaveClass('rc-steps-item-process');
这个用例是挂的。

2022-11-03 06:24 UTC, heiyu4585 commented on components/steps/__tests__/index.test.tsx
> +    expect(screen.getByText(/进行中/i)).toHaveClass('rc-steps-item-process');
done

2022-11-03 06:27 UTC, afc163 approved these changes

2022-11-03 06:28 UTC, merged