`Input` add NumericInput demo & update searchInput demo
ant-design/ant-design pull request #3861
Opened 2016-11-15 17:08 UTC by ddcat1115

close #3561

2016-11-16 01:44 UTC, benjycui commented on components/input/demo/search-input.md
> +  constructor(props) {
其实我觉得没必要为了写个 `this.state = {...}` 就用到 constructor，可以直接用：

```jsx
class Abc extends React.Compoennt {
  state = {
    ...
  };
  ...
}
```

2016-11-16 01:46 UTC, benjycui commented on components/input/demo/tooltip.md
> +  // 如果小数点在末尾 或 只有'-'
或则注释应该也用英文，毕竟中英文文档共用一份代码。

2016-11-16 03:51 UTC, afc163 commented
这个组件直接内置。

2016-11-16 03:58 UTC, ddcat1115 commented on components/input/demo/tooltip.md
> +  value += '';
这里好像没有报

2016-11-16 04:04 UTC, afc163 commented on components/input/demo/tooltip.md
> +function formatNumber(value) {
http://stackoverflow.com/a/30106316/3040605

2016-11-16 04:06 UTC, afc163 commented on components/input/demo/tooltip.md
> +    </div>);
最好换行下来。

```
return (
  <div>
  </div>
)
```

2016-11-16 04:06 UTC, afc163 commented on components/input/demo/tooltip.md
> +	width: 120px;
要缩进。

2016-11-21 09:58 UTC, afc163 requested changes

2016-11-21 09:58 UTC, afc163 commented on components/input/demo/tooltip.md
> +	width: 120px;
未修改。

2016-11-22 12:42 UTC, yesmeck commented
这个需要 rebase 一下，并且跑一下 `npm run jest` 把 snap 文件也提交上来了。

2016-11-24 03:40 UTC, afc163 approved these changes

2016-11-24 03:41 UTC, afc163 commented on components/input/demo/search-input.md
> +const InputSearch = Input.Search;
就叫 Search 好了。

2016-11-24 06:03 UTC, merged