fix(table): no border-bottom when the cells are merged
ant-design/ant-design pull request #38735
Opened 2022-11-19 09:56 UTC by LuciNyan

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Closes: #38724

### 💡 Background and solution

![image](https://user-images.githubusercontent.com/22126563/202845261-052204a1-0212-46db-8586-e335b07d7395.png)
![image](https://user-images.githubusercontent.com/22126563/202845305-dd9be12b-ca48-4f8c-b546-7fb880f68869.png)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix the issue that no border is displayed  when cells are merged   |
| 🇨🇳 Chinese |     修复合并单元格时不显示边框的问题      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

2022-11-19 10:13 UTC, li-jia-nan commented
可以补充一个测试用例吗？

2022-11-19 12:25 UTC, LuciNyan commented
Hi @li-jia-nan! Thanks for the reminder! But I don't know how to add unit tests for the CSS changes. Could you give me some more tips? <3

2022-11-19 12:51 UTC, li-jia-nan commented
> Hi @li-jia-nan! Thanks for the reminder! But I don't know how to add unit tests for the CSS changes. Could you give me some more advice? <3

```ts
const element = container.querySelector<HTMLDivElement>('xxxx');

const getStyle = getComputedStyle(element);

expect(getStyle.borderBlockEnd).toBe('xxxx');
```

2022-11-19 12:56 UTC, afc163 commented
这样的测试用例没啥意义。

2022-11-19 12:58 UTC, li-jia-nan commented
> 这样的测试用例没啥意义，不能保证样式是对的。

OK，那这个让闲夕大佬来跟进一下，我就不管啦❤️❤️❤️

2022-11-22 11:19 UTC, afc163 approved these changes

2022-11-22 11:23 UTC, afc163 reviewed
这样会让 table 丢失底部 border，看 https://preview-38735-ant-design.surge.sh/components/table-cn#components-table-demo-basic

最好和 4.x 样式对对，看看哪个样式缺了

2022-11-22 11:23 UTC, afc163 requested changes
这样会让 table 丢失底部 border，看 https://preview-38735-ant-design.surge.sh/components/table-cn#components-table-demo-basic

最好和 4.x 样式对对，看看哪个样式缺了

2022-12-22 08:03 UTC, closed without merging