style(Modal): Adopt a better way to break lines
ant-design/ant-design pull request #39249
Opened 2022-12-04 13:36 UTC by MuxinFeng

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

[使用 Modal.info(), content 属性中的内容较长时，会超出 Modal 边界
](https://github.com/ant-design/ant-design/issues/39247)

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Add `max-width` to `modal-confirm-content` to achieve a line break effect (a supplement to `non-CJK` text wrapping)    |
| 🇨🇳 Chinese |    给`modal-confirm-content`加上`max-width`，来达到换行效果（算是对非 `CJK` 文字换行的补充）      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-12-04 13:39 UTC, afc163 requested changes

2022-12-04 13:39 UTC, afc163 commented on components/modal/style/index.tsx
> +            flexBasis: '100%',
```suggestion
            flexBasis: '100%',
            maxWidth: `calc(100% - ${token.modalConfirmIconSize + token.marginSM})`,
```

改这个就好。别动 wordWrap，这个和 4.x 保持一致就行。

2022-12-04 13:40 UTC, afc163 commented on components/modal/demo/hooks.tsx
> +  content: <p>`Reachable: !aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)`</p>,
demo 不用改。

2022-12-04 13:42 UTC, MuxinFeng commented on components/modal/demo/hooks.tsx
> +  content: <p>`Reachable: !aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)`</p>,
大佬神速，我刚想改来着

2022-12-04 13:42 UTC, MuxinFeng commented on components/modal/style/index.tsx
> +            flexBasis: '100%',
好嘞，我研究下

2022-12-04 14:12 UTC, MuxinFeng commented on components/modal/style/index.tsx
> +            flexBasis: '100%',
代码改好了，`changelog`也改好了。
对于`word-break`这个方案不能用的情况我还有些疑惑，并且在历史 pr 里没找到相关的说明，大佬能给些关键词吗

2022-12-04 15:32 UTC, afc163 commented on components/modal/style/index.tsx
> +            flexBasis: '100%',
break-word 会让英文单词被砍断，不是最合理的排版方式，所以一般不会作为默认样式设置。

2022-12-04 15:34 UTC, afc163 approved these changes

2022-12-04 15:34 UTC, merged

2022-12-05 01:29 UTC, MuxinFeng commented on components/modal/style/index.tsx
> +            flexBasis: '100%',
感谢答疑