fix(grid): fix justify and align properties are not reactive for Row
ant-design/ant-design pull request #39706
Opened 2022-12-21 07:40 UTC by candy4290

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
ref: #39690

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix justify and align properties are not reactive for Row     |
| 🇨🇳 Chinese |     修复Row组件justify和align属性，动态改变不生效的问题      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-12-21 20:41 UTC, azro352 commented on components/grid/__tests__/index.test.tsx
> +      const [justify, setjustify] = useState<any>('start');
```suggestion
      const [justify, setJustify] = useState<any>('start');
```

2022-12-22 01:52 UTC, afc163 approved these changes

2022-12-22 01:53 UTC, afc163 requested changes
ci 挂了

2022-12-22 02:14 UTC, candy4290 commented
> ci 挂了
我改下，少改了个地方

2022-12-22 02:59 UTC, afc163 approved these changes

2022-12-22 02:59 UTC, merged