refactor(Radio): Gets the disabled state correctly when nested
ant-design/ant-design pull request #40741
Opened 2023-02-15 11:03 UTC by Yuiai01

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Improve https://github.com/ant-design/ant-design/pull/40728

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Gets the disabled state correctly when nested   |
| 🇨🇳 Chinese |  被嵌套时正确获取 `disabled` 状态         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2023-02-16 03:00 UTC, Wxh16144 commented on components/radio/__tests__/radio.test.tsx
> +    );
expect(getByRole('radio')).not.toBeDisabled();

2023-02-16 03:15 UTC, Wxh16144 requested changes

2023-02-16 03:15 UTC, Wxh16144 commented on components/radio/radio.tsx
> +  radioProps.disabled = radioProps.disabled ?? disabled;
}

  radioProps.disabled ??= groupContext?.disabled ?? disabled;

2023-02-16 03:15 UTC, Wxh16144 commented on components/radio/__tests__/radio.test.tsx
> +    );
expect(getByRole('radio')).not.toBeDisabled();

2023-02-16 03:24 UTC, Wxh16144 commented on components/radio/__tests__/radio.test.tsx
> +    );
```suggestion
   expect(getByRole('radio')).not.toBeDisabled();
```

2023-02-16 03:24 UTC, Wxh16144 commented on components/radio/__tests__/radio.test.tsx
> +    const { container } = render(
```suggestion
    const { getByRole } = render(
```

2023-02-16 03:24 UTC, Wxh16144 commented on components/radio/radio.tsx
> +  radioProps.disabled = radioProps.disabled ?? disabled;
```suggestion
  }

  radioProps.disabled ??= groupContext?.disabled ?? disabled;
```

2023-02-16 03:36 UTC, MadCcc commented on components/radio/radio.tsx
> +  radioProps.disabled = radioProps.disabled ?? disabled;
这个有 if 块的还是建议分开写，逻辑上比较连贯

2023-02-16 05:02 UTC, Yuiai01 commented on components/radio/__tests__/radio.test.tsx
> +    );
这里这样写语义确实更加清晰，感谢大佬！

2023-02-16 10:10 UTC, Yuiai01 commented on components/radio/__tests__/radio.test.tsx
> +    const { container } = render(
目前系统里基本都是使用 `screen.getByRole` ，如果直接使用大佬你这种解构方法的话，感觉可以删掉 `screen` 🤔

2023-02-16 10:12 UTC, Yuiai01 commented on components/radio/radio.tsx
> +  radioProps.disabled = radioProps.disabled ?? disabled;
嗯嗯，这里我是考虑到如果不存在 groupContext，没必要进行判断，可以减少一些操作

2023-02-17 02:23 UTC, MadCcc approved these changes

2023-02-17 02:23 UTC, merged