fix: radio button在disabled和checked状态多了点box-shadow
ant-design/ant-design pull request #4114
Opened 2016-12-02 13:32 UTC by jdz321

![sc](https://cloud.githubusercontent.com/assets/8564681/20835665/c3548194-b8d6-11e6-8237-b9fd57aed378.png)

2016-12-02 13:49 UTC, afc163 requested changes
感谢 PR !~ 👍 

1. `package.json` 和 `radiobutton.md` 不用改动。
2. 邮箱信息建议修改或绑定一下。

![](https://zos.alipayobjects.com/rmsportal/AzYhamskRILOhjAYCdNS.png)

2016-12-03 04:03 UTC, afc163 commented
@jdz321

2016-12-05 02:38 UTC, jdz321 commented
done  2333

2016-12-05 03:26 UTC, afc163 commented
<img width="281" alt="image" src="https://cloud.githubusercontent.com/assets/507615/20872937/b786c008-badd-11e6-89f0-e715b73c3c80.png">

2016-12-05 05:08 UTC, jdz321 commented
我把那条ci删了  好麻烦 orz

2016-12-05 05:15 UTC, afc163 approved these changes

2016-12-05 05:15 UTC, merged

2016-12-27 12:48 UTC, ystarlongzi commented
`<ButtonGroup />` 里如果将 `primary` 和另外两种状态混用，也有同样的问题，[查看demo](http://codepen.io/ystarlongzi/pen/zoVNxz?editors=011)。

另外，感觉 [button/style/index.less](https://github.com/ant-design/ant-design/blob/master/components/button/style/index.less#L31) 的 `.@{btn-prefix-cls}` 是不是可以改成 `&`