mention-testing
ant-design/ant-design pull request #4158
Opened 2016-12-06 10:29 UTC by RaoHai

```
--------------------------------|----------|----------|----------|----------|----------------|
File                            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------|----------|----------|----------|----------|----------------|
components/mention              |    76.27 |    54.55 |    70.59 |    84.21 |                |
  index.tsx                     |    76.27 |    54.55 |    70.59 |    84.21 |       30,31,32 |
```

原来是0。。

2016-12-07 03:01 UTC, yesmeck commented on tests/mention/__snapshots__/demo.test.js.snap
> +exports[`test renders ./components/mention/demo/async.md correctly 1`] = `
这个不应该提交上来？Mention 的 snapshot 测试是跳过的，因为  editorKey 的关系。

2016-12-07 13:10 UTC, yesmeck commented on tests/mention/Mention.test.js
> +    mount(<MentionWrapper onChange={onChange} onSelect={onSelect} />);
那其实这里可以这样写：

```javascript
it('fires change on mount', () => {
  const handleChange = jest.fn();
  const wrapper = mount(
    <Mention
      onChange={handleChange}
      defaultValue={toEditorState('@afc163')}
      suggestions={['afc163', 'benjycui', 'yiminghe']}
    />
  );

  expect(getMentions(handleChange.mock.call[0][0])[0]).toBe('@afc163');
});
```

上面的`MentionWrapper`是不需要的，测试里的例子应该只要设置测试关注的点就可以了。
`it` 后面应该写清楚测试的点（不过我看你这里目的是要测试在设置 defaultValue 的时候第一次 render 能触发 onChange?），然后可以试试 `jest.fn` 来 mock 方法。

2016-12-08 03:55 UTC, benjycui commented on tests/mention/Mention.test.js
> +import Mention, { toEditorState, getMentions } from '../../components/mention';
cc @yesmeck @afc163

2016-12-08 04:01 UTC, yesmeck commented on tests/mention/Mention.test.js
> +import Mention, { toEditorState, getMentions } from '../../components/mention';
确实放 components 下比较方便。

2016-12-08 04:03 UTC, yesmeck commented on tests/mention/Mention.test.js
> +import Mention, { toEditorState, getMentions } from '../../components/mention';
每个组件自己的测试可以放每个组件自己的目录下，公共的部分可以继续放在 tests 下。

2016-12-09 06:44 UTC, benjycui commented on tests/mention/Mention.test.js
> +    mount(<MentionWrapper onChange={onChange} onSelect={onSelect} />);
用 [`toHaveBeenCalledWith `](https://facebook.github.io/jest/docs/api.html#tohavebeencalledwitharg1-arg2-) 可读性好点。

2016-12-09 06:47 UTC, yesmeck requested changes
这个测试我觉得是应该写在  `rc-editor-mention`.

2016-12-13 08:44 UTC, RaoHai commented
那就 close 掉，过后自行添加到 rc-editor-mention 里

2016-12-13 08:44 UTC, closed without merging