remove hardcoded inputs height
ant-design/ant-design pull request #4175
Opened 2016-12-07 15:10 UTC by pierre-b

This PR concerns #4144 

However it would be nice to put the line-height of the components dynamic. Because changing the height of the inputs will not change the line-height.

2016-12-08 01:59 UTC, benjycui commented on components/pagination/style/index.less
> +    min-width: @input-height-base;
I think we need a new variable for this case, for Pagination is not a form control.

2016-12-09 06:59 UTC, yesmeck requested changes

2016-12-09 06:59 UTC, yesmeck commented on components/pagination/style/index.less
> +    min-width: @input-height-base;
@pierre-b Could you please revert this file?

2016-12-12 04:14 UTC, benjycui commented on components/pagination/style/index.less
> +    min-width: @input-height-base;
？？ haven't revert?

2016-12-13 11:26 UTC, pierre-b commented on components/pagination/style/index.less
> +    min-width: @input-height-base;
@benjycui The second commit reverts the pagination component [https://github.com/ant-design/ant-design/pull/4175/commits/d90e14eacf376d98ad36653d2f09007da019ea1d](https://github.com/ant-design/ant-design/pull/4175/commits/d90e14eacf376d98ad36653d2f09007da019ea1d)

Is this not correct?

2016-12-14 01:19 UTC, benjycui commented on components/pagination/style/index.less
> +    min-width: @input-height-base;
Just read the diff https://github.com/ant-design/ant-design/pull/4175/files it's still here.

2016-12-15 01:24 UTC, benjycui approved these changes

2016-12-15 03:14 UTC, yesmeck requested changes

2016-12-15 03:14 UTC, yesmeck commented on components/pagination/style/index.less
> +      line-height: @input-height-base;
@pierre-b

2016-12-15 03:16 UTC, yesmeck approved these changes

2016-12-15 03:17 UTC, merged

2016-12-15 03:17 UTC, yesmeck commented
Thanks, @pierre-b .

2016-12-15 04:05 UTC, afc163 commented on components/switch/style/index.less
> +  height: @input-height-base;
Should not modify this:

<img width="207" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21211472/c319607c-c2be-11e6-96cd-025c947e3e26.png">

2016-12-15 04:07 UTC, afc163 commented on components/switch/style/index.less
> +  height: @input-height-base;
https://github.com/ant-design/ant-design/commit/d9b6ff5c8fcd8a7d612c12c1ae3090c62435aae0

2016-12-15 05:52 UTC, yesmeck commented on components/switch/style/index.less
> +  height: @input-height-base;
`@input-height-sm`

2016-12-15 06:18 UTC, afc163 commented on components/switch/style/index.less
> +  height: @input-height-base;
感觉也不合适。