<CheckboxGroup /> support className
ant-design/ant-design pull request #4240
Opened 2016-12-14 06:36 UTC by ystarlongzi

当前 `<CheckboxGroup />` 组件不支持 `className`，然后不方便开发者自定义样式，比如[垂直布局](http://codepen.io/ystarlongzi/pen/oYaMbW)。

然后参照了 `<RadioGroup />` 组件代码，使 `<CheckboxGroup />` 支持 `className`。

2016-12-14 09:59 UTC, afc163 commented
不要用同一个 branch 开发两个特性。

2016-12-14 10:02 UTC, ystarlongzi commented
哦哦，抱歉，现在可以撤销吧，我撤销下

2016-12-15 03:20 UTC, yesmeck requested changes

2016-12-15 09:32 UTC, benjycui commented on components/checkbox/Group.tsx
> +    const { prefixCls, className = '' } = this.props;
为了应对 TypeScript 的 null check

2016-12-15 11:11 UTC, ystarlongzi commented on components/checkbox/Group.tsx
> +    const { prefixCls, className = '' } = this.props;
那还是需要默认值的？我看 <RadioGroup />里是有默认值的。

2016-12-15 12:16 UTC, yesmeck commented on components/checkbox/Group.tsx
> +    const { prefixCls, className = '' } = this.props;
跟 @benjycui 沟通过了，现在不需要默认值了。

2016-12-16 08:44 UTC, benjycui commented
这个 PR 怎么有两个不同的改动？ @ystarlongzi

2016-12-16 09:25 UTC, closed without merging