callback is triggered only when the value changes
ant-design/ant-design pull request #4250
Opened 2016-12-14 10:21 UTC by ystarlongzi

如题，见 #4242

2016-12-15 01:27 UTC, benjycui commented on components/radio/group.tsx
> +    if (ev.target.value === this.props.value) {
这判断不对吧，Radio.Group 同时支持受控和非受控模式的。

2016-12-15 09:44 UTC, ystarlongzi commented on components/radio/group.tsx
> +    if (ev.target.value === this.props.value) {
嗯嗯，对👍👍。我再改下，O(∩_∩)O谢谢

2016-12-15 10:10 UTC, yesmeck commented
这样的话，最好能写下测试吧。

2016-12-15 10:27 UTC, ystarlongzi commented
@yesmeck 
好的。是在`radio/__tests__/group.test.js`里写测试吧？

2016-12-15 10:45 UTC, yesmeck commented
对的，可以参考 table 下测试。

2016-12-15 10:49 UTC, ystarlongzi commented
好的，谢谢

2016-12-15 16:24 UTC, ystarlongzi commented
@yesmeck @benjycui 求助！

在尝试写测试时候，按照下面方法写是可以通过的。
```javascript
function createRadioGroup(props) {
    return (
      <RadioGroup
        {...props}
      >
        <Radio value="A">A</Radio>
        <Radio value="B">B</Radio>
        <Radio value="C">C</Radio>
      </RadioGroup>
    );
  }

describe('Radio', () => {
  it('fire change events when value changes', () => {
    const onChange = jest.fn();

    const wrapper = mount(
      createRadioGroup({
        onChange
      })
    );
    const radios = wrapper.find('input');

    wrapper.instance().setState({ value: 'B' });
    radios.at(0).simulate('change');
    expect(onChange).toHaveBeenCalled();
  });

  it('won\'t fire change events when value not changes', () => {
    const onChange = jest.fn();

    const wrapper = mount(
      createRadioGroup({
        onChange
      })
    );
    const radios = wrapper.find('input');

    wrapper.instance().setState({ value: 'A' });
    radios.at(0).simulate('change');
    expect(onChange).not.toHaveBeenCalled();
  });
});
```

然后，我想将这两个测试合并成一个，就通不过了。猜测是由于 state 批量更新导致的，请问这种情况怎么解决？还是说我写错了？代码如下：
```javascript
it('check change events', () => {
    const onChange = jest.fn();

    const wrapper = mount(
      createRadioGroup({
        onChange
      })
    );
    const radios = wrapper.find('input');

    wrapper.instance().setState({ value: 'B' });

    radios.at(0).simulate('change');
    expect(onChange).toHaveBeenCalled();

    radios.at(0).simulate('change');

    // ⚠️⚠️⚠️提示这个条件无法通过。
    expect(onChange).not.toHaveBeenCalled();
  });
```

2016-12-15 16:28 UTC, yesmeck commented
@ystarlongzi 把 onRadioChange 里相关的变量打印出来看看吧。

2016-12-15 16:29 UTC, yesmeck commented
不过分开来写挺好的，测试的点不一样。

2016-12-15 16:33 UTC, yesmeck commented
`expect(onChange).not.toHaveBeenCalled();`

这里不能这么写了, onChange 在上面已经被调用过了，要判断 `onChange.mock.calls.length` 的长度才行。

2016-12-16 01:22 UTC, ystarlongzi commented
@yesmeck 

为了方便查看 onChange 调用的参数，我把 `group.tsx` 里触发 onChange 的代码改成了如下：
```javascript
if (onChange && value !== lastValue) {
  // onChange(ev)
  onChange(value, lastValue);
}
```

然后，我写的第二种方案，也就是合并到一起的那个测试，未通过的提示如下：
```
Radio › check change events

    expect(jest.fn()).not.toHaveBeenCalled()
    
    Expected mock function not to be called but it was called with:
      ["A", "B"]
```

然后，你建议判断 `onChange.mock.calls.length` 也是没有通过，提示如下：

```
Radio › check change events

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      0
    Received:
      1

```

2016-12-16 08:45 UTC, benjycui commented
和 className 那个 PR 串了，麻烦分开两个分支来修改和 PR 哈。

2016-12-16 08:47 UTC, benjycui requested changes
需要和另外一个 PR 分开到两个分支修改，建议先学习 GitHub 的工作流。

2016-12-16 08:47 UTC, ystarlongzi commented
哦哦，是的，抱歉，我改下。

嗯嗯，github 工作流是不熟悉，有推荐的文章可以看下嘛？

2016-12-16 08:53 UTC, yesmeck commented
@ystarlongzi 你理解错 mock 方法的用法的了。第二次应该判断 `expect(onChange.mock.calls.length).toBe(1);`，这里的 calls 是这个用例里总的 calls。不过，还是分开来写吧。

2016-12-16 09:25 UTC, ystarlongzi commented
我把这个 和 #4240  的关掉，在重新提下吧。
搞不定了。

2016-12-16 09:25 UTC, closed without merging