add warning when using Breadcrumb without its Item
ant-design/ant-design pull request #4435
Opened 2016-12-31 10:09 UTC by kunsam

fix issue ' Warning: Unknown prop `separator` on <div> tag. When I using Breadcrumb #4403'

ps: 我是个前端beginner， - ( ゜- ゜)つロ， 这是我第一个PR welcome, 如果写错或者还有更好的写法请大神指正。thanks

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

2016-12-31 10:13 UTC, kunsam commented
增加警告信息当使用Breadcrumb时未嵌套BreadcrumbItem
add warning when using `<Breadcrumb >` without `<BreadcrumbItem >`  as wrapper of each children. Otherwise React will warn

2016-12-31 11:21 UTC, yesmeck commented
用 type.name 去做判断是会有问题的，代码 uglify  后 name 就变掉了。但是如果直接用 type 去比较的话就会碰到 react-hot-reload 的问题（ https://github.com/ant-design/ant-design/issues/3550 ）。需要花时间统一处理一下这类问题。

2016-12-31 12:32 UTC, kunsam commented
@yesmeck 请教两个问题：
1. 你提到的 uglify 是webpack 内置的还是你们自己的库， uglify 执行会压缩声明的字符串吗?
比如我写一句 `if ( car === 'BMW' ) do();` , 'BMW'会被uglify掉吗？
2. 那我写的那个可以改为

` const hasBreadcrumbItem = element.type.name === <BreadcrumbItem />.type.name; `
` if(!hasBreadcrumbItem) warn()`
吗？ 这样被压缩了也没有关系吧?

2016-12-31 12:48 UTC, yesmeck commented
1. 一般业务项目上线的时候会做 uglify，变量名会被替换掉，BreadcrumbItem 会变成别的名字;
2. 也是有问题的，见 https://github.com/ant-design/ant-design/issues/3550#issuecomment-263830835 的讨论。

2017-01-03 06:39 UTC, yesmeck commented
还是用 type 比较把，暂时不考虑 RHL 了。

2017-01-03 06:46 UTC, benjycui commented on components/breadcrumb/Breadcrumb.tsx
> +        const hasBreadcrumbItem = element.type.name === 'BreadcrumbItem';
用 type 判断而非字符串。

2017-01-03 06:48 UTC, benjycui commented on components/breadcrumb/Breadcrumb.tsx
> +          return (
没必要做兼容吧。。直接 warning 就好。

2017-01-09 02:40 UTC, yesmeck requested changes
按 @benjycui  的留言调整下吧

2017-01-13 13:14 UTC, afc163 commented
@kunsam

2017-01-14 07:25 UTC, merged

2017-01-14 07:25 UTC, afc163 commented
感谢 PR ~