normalize code based on lint message
ant-design/ant-design pull request #4457
Opened 2017-01-03 12:16 UTC by pinggod

https://github.com/ant-design/ant-design/issues/4302

2017-01-03 12:23 UTC, afc163 commented on site/theme/template/Layout/Header.jsx
> +          <Link onClick={this.handleHideMenu} to={utils.getLocalizedPathname('/', isZhCN)}>
这样绑定貌似略多余，试试监听 url 变化如何？

https://github.com/ReactTraining/react-router/issues/964#issuecomment-175592865

2017-01-03 12:24 UTC, pinggod commented on site/theme/template/Layout/Header.jsx
> +          <Link onClick={this.handleHideMenu} to={utils.getLocalizedPathname('/', isZhCN)}>
嗯嗯 我明天试一下

2017-01-04 01:50 UTC, benjycui commented on site/theme/template/Layout/Header.jsx
> +          <Link onClick={this.handleHideMenu} to={utils.getLocalizedPathname('/', isZhCN)}>
bisheng 把 browserHistory 封装起来了，用这种方法监听吧： https://github.com/ant-design/ant-design/blob/master/site/theme/template/Layout/index.jsx#L41

2017-01-04 03:57 UTC, benjycui requested changes

2017-01-04 03:57 UTC, benjycui commented on site/theme/template/Layout/Header.jsx
> +            this.context.router.listen(this.handleHideMenu);
如果用户不断的 resize 浏览器，`match` 方法会反复执行的，这样你就监听同一个事件多次了。

2017-01-04 05:03 UTC, pinggod commented on site/theme/template/Layout/Header.jsx
> +            this.context.router.listen(this.handleHideMenu);
是否有方式可以取消监听？

2017-01-04 06:59 UTC, benjycui commented on site/theme/template/Layout/Header.jsx
> +            this.context.router.listen(this.handleHideMenu);
componentDidMount 里面监听不可以么？

2017-01-04 07:07 UTC, pinggod commented on site/theme/template/Layout/Header.jsx
> +            this.context.router.listen(this.handleHideMenu);
在 componentDidMount 中监听可以实现，只是纯粹的想了解一下是否有取消监听的方式。

2017-01-06 08:48 UTC, pinggod commented
这个还有什么需要修改的吗？

2017-01-07 07:35 UTC, afc163 commented
@benjycui

2017-01-08 11:16 UTC, merged