Customize Input Component of AutoComplete
ant-design/ant-design pull request #4483
Opened 2017-01-05 09:47 UTC by RaoHai

close: #4082

- usage:
  ```jsx
  <AutoComplete>
    <textarea onKeyDown={someKeyDownCallback} />
  </AutoComplete>
  ```

2017-01-05 13:05 UTC, RaoHai commented on components/auto-complete/style/index.less
> +  &.@{select-prefix-cls} {
没看出来。。

2017-01-05 13:18 UTC, afc163 commented on components/auto-complete/style/index.less
> +  &.@{select-prefix-cls} {
我看错了。。

2017-01-05 13:21 UTC, RaoHai commented
补一下 React.Children.only, 免得传多个 children。。。

2017-01-06 04:07 UTC, benjycui commented on components/auto-complete/demo/options.md
> +        dataSource={children}
!!!!

没理解错的话，breaking changes?

可以做下兼容么。。如果 children 是一个数组，且为 `AutoComplete.Option` 则用回之前的逻辑。

2017-01-06 04:10 UTC, afc163 commented on components/auto-complete/demo/antd.md
> +        <textarea onKeyPress={this.handleKeyPress} />
被包裹的元素有什么要求，最好文档解释一下。

2017-01-06 06:05 UTC, RaoHai commented on components/auto-complete/demo/options.md
> +        dataSource={children}
其实不一定是数组。。

```jsx
<AutoComplete>
  <Option />
</AutoComplete>
```

2017-01-09 02:42 UTC, yesmeck commented
这个怎么带了其他人的 commit？

2017-01-09 02:56 UTC, RaoHai commented
不知道啊，我 rebase 一下，，，

2017-01-09 02:58 UTC, yesmeck requested changes
这个可以写下测试，input 是自定义的情况。

2017-01-09 02:58 UTC, yesmeck commented on components/auto-complete/index.tsx
> +export type InvalidInputElement =
应该是 Valid？

2017-01-09 02:58 UTC, yesmeck commented on package.json
> -
空行是特意保留的

2017-01-09 14:24 UTC, yesmeck commented on components/auto-complete/index.tsx
> +    Array<React.ClassicComponentClass<OptionProps>>;
这里不对吧，`<Option />` 也是 `ReactElement`，`Option` 才是 `React.ClassicComponentClass<OptionProps>`

2017-01-10 02:22 UTC, RaoHai commented on components/auto-complete/index.tsx
> +    Array<React.ClassicComponentClass<OptionProps>>;
确实。。。

2017-01-10 08:57 UTC, yesmeck requested changes

2017-01-10 08:57 UTC, yesmeck commented on components/auto-complete/index.en-US.md
> +| children (for dataSource) | Data source for autocomplet | React.ClassicComponentClass<OptionProps> /  Array<React.ClassicComponentClass<OptionProps>> | - |
`React.ClassicComponentClass<OptionProps>` 这里也要改掉。

2017-01-12 08:17 UTC, yesmeck approved these changes

2017-01-13 13:19 UTC, merged