feat(mentions): supports 'allowClear' option
ant-design/ant-design pull request #46396
Opened 2023-12-12 01:42 UTC by yociduo

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/react-component/mentions/pull/204
https://github.com/ant-design/ant-design/issues/46278

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Mentions support `allowClear` prop |
| 🇨🇳 Chinese | Mentions 支持 `allowClear` 属性 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2023-12-17 05:05 UTC, afc163 commented on components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
> +    classes="[object Object]"
这个肯定是有问题的。

2023-12-17 05:14 UTC, yociduo commented on components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
> +    classes="[object Object]"
需要等这个PR合并了，https://github.com/ant-design/ant-design/pull/46435

2023-12-18 09:54 UTC, MadCcc commented
https://github.com/ant-design/ant-design/pull/46435 已经合并了

2023-12-18 15:10 UTC, afc163 commented on components/mentions/index.tsx
> +  let mergedAllowClear: BaseInputProps['allowClear'];
这个类型是不是可以从 antd Input 中引过来？这样不需要走 rc-input/lib/xxx

2023-12-18 15:10 UTC, afc163 commented on components/mentions/index.tsx
> +    mergedAllowClear = { clearIcon: <CloseCircleFilled /> };
```suggestion
    mergedAllowClear = {
      clearIcon: <CloseCircleFilled />,
    };
```

2023-12-18 15:12 UTC, afc163 commented on components/mentions/index.tsx
> +    allowClear,
默认是 false。

2023-12-18 15:12 UTC, afc163 commented
不知道为啥 https://preview-46396-ant-design.surge.sh/ 无法访问。

2023-12-19 01:24 UTC, yociduo commented on components/mentions/index.tsx
> +    mergedAllowClear = { clearIcon: <CloseCircleFilled /> };
这块改到hooks去了

2023-12-19 02:38 UTC, yociduo commented
> 不知道为啥 https://preview-46396-ant-design.surge.sh/ 无法访问。

我可以访问的

2023-12-19 02:50 UTC, afc163 commented on components/_util/hooks/useAllowClear.tsx
> +export default useAllowClear;
这个貌似不是个 hooks，没必要叫 useXxxx，可以用 getXxx

2023-12-19 03:24 UTC, afc163 commented on components/_util/hooks/getAllowClear.tsx
> +export default getAllowClear;
自然也不应该放在 hooks 目录下。

2023-12-19 05:23 UTC, afc163 commented
搞个 demo 吧，这样预览链接里可以看看效果。

2023-12-20 06:47 UTC, afc163 commented
<img width="116" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/cad25fc8-59f0-4de5-a4c5-4507f0ba04a2">

清除按钮位置有点偏上了。

2023-12-22 09:11 UTC, afc163 commented
<img width="611" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/acf5f736-1d95-4684-b8fc-601a2765a0db">

多行输入框时，清除按钮是不是还是和 TextArea 一样放在顶部比较好？

<img width="548" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/9e6e13d5-ae20-4a90-be8b-b752da417dac">

2023-12-22 09:15 UTC, yociduo commented
> <img alt="图片" width="611" src="https://private-user-images.githubusercontent.com/507615/292449407-acf5f736-1d95-4684-b8fc-601a2765a0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzY2NzcsIm5iZiI6MTcwMzIzNjM3NywicGF0aCI6Ii81MDc2MTUvMjkyNDQ5NDA3LWFjZjVmNzM2LTFkOTUtNDY4NC1iOGZjLTYwMWEyNzY1YTBkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwOTEyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmY3ODNjNDliMGZkNjVjOTNlMTU3ODQyOWIxMjBhZGQwNzhjM2UxOTFiZTg3NDg2NzEzZDA0NGM5ZjJjYjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M7NKWXE8svgYeAn-AGEMAN91ueq_jKx5-ZqY7gaT7Rc">
> 多行输入框时，清除按钮是不是还是和 TextArea 一样放在顶部比较好？
> 
> <img alt="图片" width="548" src="https://private-user-images.githubusercontent.com/507615/292449440-9e6e13d5-ae20-4a90-be8b-b752da417dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzY2NzcsIm5iZiI6MTcwMzIzNjM3NywicGF0aCI6Ii81MDc2MTUvMjkyNDQ5NDQwLTllNmUxM2Q1LWFlMjAtNGE5MC1iZThiLWI3NTJkYTQxN2RhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwOTEyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZjZWYyM2NmNTA5YTgyOGNlNDU0ZTExYzQxMTc3ODU3NjlkZDViMTk2YTkxYjFmNjI2MDJjZDY3MTA1ZjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VqEXUIxla6L3l0Je_lM_hjPVFxzLD3JIMIUZupvh3FQ">

实现有点不一样，输入框那边，input是居中的，textarea是固定在顶部的。我看下能不能做到

2023-12-24 07:03 UTC, afc163 approved these changes

2023-12-24 07:04 UTC, afc163 commented
## size-limit report 📦 
| Path                              | Size                  |
| --------------------------------- | --------------------- |
| `./dist/antd.min.js`              | 329.97 KB (+103 B 🔺) |
| `./dist/antd-with-locales.min.js` | 375.82 KB (+381 B 🔺) |
Error creating comment. This can happen for PR's originating from a fork without write permissions.

2023-12-24 07:05 UTC, afc163 requested changes
看下 image diff 的对比：https://github.com/ant-design/ant-design/pull/46396#issuecomment-1857833232

圆角处貌似有点问题。

2023-12-25 02:37 UTC, afc163 commented
效果已经很好了，我先合并了。体积大了 100b，感觉有点多，后面可以看看有没有办法再优化一下。

2023-12-25 02:37 UTC, afc163 approved these changes

2023-12-25 02:37 UTC, merged

2023-12-25 07:29 UTC, yociduo commented
> 效果已经很好了，我先合并了。体积大了 100b，感觉有点多，后面可以看看有没有办法再优化一下。

应该是样式那边的关系