fix(transfer): input search change totalSize instantly fix #4654
ant-design/ant-design pull request #4665
Opened 2017-01-20 09:02 UTC by paranoidjk

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

2017-01-20 09:31 UTC, afc163 reviewed
看不懂，onSearchFilter 是干什么用的，感觉搞复杂了。

2017-01-20 09:38 UTC, paranoidjk commented
@afc163 
- 命名可能不太合适，简单解释下, 在每个`Item`的`render()`里加了`props.onSearchFilter()`来通知父组件自己是否符合用户的输入筛选条件
- 从而父组件`List`在收到所有子`Item`的Notify之后，就可以决定顶部的显示总数，以及全选时可以选中哪些。

原因
在Item的render()里才得到筛选结果 [code](https://github.com/ant-design/ant-design/blob/master/components/transfer/item.tsx#L37)

2017-01-22 08:47 UTC, yesmeck commented
现在这样看起来是有点别扭，filter 放在 `Transfer` 和 `List` 里做会比较好，不过现在这样放在 `Item` 里做是性能的原因？

2017-01-22 08:49 UTC, afc163 commented
当初是为了性能做优化，避免点击选择一个时，其他 item 要跑 render。

2017-01-22 08:50 UTC, yesmeck commented
好像现在没必要了吧，只有 viewport 里的 Item 会 render 吧。

2017-01-22 08:53 UTC, afc163 commented
嗯对的，可以拿出来。

2017-01-22 08:57 UTC, paranoidjk commented
把filter往上提的话这个mr可以close掉了 @yesmeck

2017-01-22 08:59 UTC, afc163 commented
不用 close ，重新提交就好，可以看到讨论记录。

2017-01-22 09:56 UTC, paranoidjk commented
cc @afc163 @yesmeck  updated

2017-01-22 10:22 UTC, afc163 commented on components/transfer/list.tsx
> +      totalDataSource.push(item);
应该直接用下面的 filteredDataSource ？

2017-01-22 10:34 UTC, paranoidjk commented on components/transfer/list.tsx
> +      totalDataSource.push(item);
要看产品设计了，我看原来的的设计，顶部显示的总条数是包含disable的item的，所以：
- totalDataSource： 显示在顶部总数（包括可选的+disabled）
- filteredDataSource: 点全选的时候可以全部选中的（不包含disbaled的）

2017-01-22 10:35 UTC, afc163 commented on components/transfer/list.tsx
> +      totalDataSource.push(item);
貌似是 totalDataSource 更合理一些。

2017-01-22 10:38 UTC, yesmeck commented
写下测试吧。

2017-01-22 12:11 UTC, paranoidjk commented
@yesmeck done. 测了两个feature点，but覆盖率貌似基本无变化...

2017-01-23 03:13 UTC, benjycui approved these changes

2017-01-23 12:29 UTC, yesmeck requested changes
还要测试下，点击 `>` 后穿过的选项是筛选后的结果，

2017-01-23 12:29 UTC, yesmeck commented on components/transfer/__tests__/index.test.js
> +    const wrapper = mount(<Transfer {...searchTransferProps} showSearch filterOption={filterOption} render={renderFunc} onSelectChange={handleSelectChange} />);
太长了，要换行，下面也是的。

2017-01-23 13:58 UTC, paranoidjk commented
@yesmeck ok, 加上了

2017-01-23 14:06 UTC, yesmeck approved these changes

2017-01-25 13:37 UTC, afc163 approved these changes

2017-01-27 09:08 UTC, merged