fix(Menu): vertical menu margin collapsed in v5
ant-design/ant-design pull request #46896
Opened 2024-01-10 07:13 UTC by liuyib

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix: https://github.com/ant-design/ant-design/issues/46886

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix(Menu): vertical menu margin collapsed in v5     |
| 🇨🇳 Chinese |     fix(Menu): v5 垂直菜单 margin 坍塌      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2024-01-10 07:16 UTC, liuyib commented
v4 里也有防止垂直方向 margin 坍塌的代码，样式是这样的：
<img width="917" alt="image" src="https://github.com/ant-design/ant-design/assets/38221479/f51c6565-ac84-47ce-adfb-e8e307d2914f">

v5 的代码里我没找到 `-vertical-left, -vertical-right` 的类名，可能是移除了？需要大佬们再确认下。
所以目前 v5 的样式是这样：
![image](https://github.com/ant-design/ant-design/assets/38221479/2278c3da-77e0-4f8c-84e3-768869c651dd)

2024-01-10 07:43 UTC, li-jia-nan commented on components/menu/style/vertical.ts
> +          paddingBottom: '.02px',
这里的单位不能写 px，可以参考一下其它地方

2024-01-10 07:53 UTC, liuyib commented on components/menu/style/vertical.ts
> +          paddingBottom: '.02px',
好的，我再瞅瞅

2024-01-10 07:55 UTC, li-jia-nan commented on components/menu/style/vertical.ts
> +          paddingBottom: '.02px',
`unit(0.02)`

2024-01-10 08:01 UTC, liuyib commented on components/menu/style/vertical.ts
> +          paddingBottom: '.02px',
嗯嗯，改了 ❤️

2024-01-10 08:47 UTC, zombieJ commented on components/menu/style/vertical.ts
> +          paddingBottom: unit(0.02),
搞个伪类占行？

2024-01-10 08:51 UTC, afc163 commented
看下diff，不太对。

2024-01-10 09:23 UTC, afc163 requested changes
看下 image diff 的检查，现在不太对。

这样会让 item 之间的距离不相等，下面的偏大。

<img width="302" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/179f5556-3ed8-4e97-8087-bf5a66b28b0c">

2024-01-10 09:41 UTC, liuyib commented on components/menu/style/vertical.ts
> +          paddingBottom: unit(0.02),
好的，我尝试下其他方案，感谢大佬建议~

2024-01-10 09:42 UTC, liuyib commented
> 看下 image diff 的检查，现在不太对。
> 
> 这样会让 item 之间的距离不相等，下面的偏大。
> 
> <img alt="图片" width="302" src="https://private-user-images.githubusercontent.com/507615/295515135-179f5556-3ed8-4e97-8087-bf5a66b28b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzk5NTUsIm5iZiI6MTcwNDg3OTY1NSwicGF0aCI6Ii81MDc2MTUvMjk1NTE1MTM1LTE3OWY1NTU2LTNlZDgtNGU5Ny04MDg3LWJmNWE2NmIyOGIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwOTQwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDc0NjFiZTg3MWU0Mjk5NzRhYWFlMGYyOGE5NjE3YWE0YjEzY2RjMTkzMjIwNGQwN2Q2OWYzYzMzOGMwZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.so6zn60jxT9sDuMmVxQTYEH1KWt_F5vjI-cgASsHSrU">

好的，我换个方案尝试下~

2024-01-10 11:59 UTC, MadCcc commented
现在应该是利用了 margin 坍缩来保证的间距一致，所以可能要换种方式来保证动画效果

2024-01-12 00:08 UTC, li-jia-nan commented on components/menu/style/vertical.ts
> +        [`${componentCls}-submenu`]: {
这里是不是可以直接简写，少嵌套一层对象：

```ts
[`${componentCls}-submenu`]: clearFix(),
```

2024-01-12 06:43 UTC, liuyib commented on components/menu/style/vertical.ts
> +        [`${componentCls}-submenu`]: {
好的，我改下。现在可能还不能直接 clear，margin 坍塌解决后，diff 可以看到和之前不一样。按群里问大佬们的意思，应该是 v5 的菜单项间距就是和 v4 不一样，我还得找个其他方式保证 v5 间距还是 4px（默认）

2024-01-23 08:23 UTC, liuyib commented
抱歉，我最近没有时间跟踪这个问题了，目前也没找到太好的解决办法，请求大佬们的帮助~

2024-09-07 05:33 UTC, closed without merging