为antd的editable-card类型的TabPane增加不可删除属性
ant-design/ant-design pull request #4807
Opened 2017-02-09 01:21 UTC by lixiaoyang1992

部分 TabPane 可以删除，部分不可以并且不显示删除按钮

2017-02-09 01:21 UTC, lixiaoyang1992 commented
需要配合使用：[react-component/tabs#50](react-component/tabs#50)

2017-02-09 06:51 UTC, benjycui commented
这个需要 rc-tabs 那边合并先吧，我没有对应的 npm 权限 @afc163

2017-02-10 02:42 UTC, ddcat1115 approved these changes

2017-02-10 02:51 UTC, ddcat1115 commented
@lixiaoyang1992 等rc-tabs那边发布了，这边的依赖应该需要升个版本~

2017-02-10 03:09 UTC, afc163 requested changes

2017-02-10 03:09 UTC, afc163 commented on components/tabs/index.tsx
>                {child.props.tab}
把 unclosable 的 className 加到这里。

https://github.com/react-component/tabs/pull/50#issuecomment-278846022

2017-02-10 03:34 UTC, lixiaoyang1992 commented on components/tabs/index.tsx
>                {child.props.tab}
但是样式中的一个hover是针对rc-tabs那里的，在这边没法给tab样式

[TabBarMixin.js](https://github.com/react-component/tabs/blob/master/src/TabBarMixin.js)

      const key = child.key;
      let cls = activeKey === key ? `${prefixCls}-tab-active` : '';
      cls += ` ${prefixCls}-tab`;
      let events = {};
      if (child.props.disabled) {
        cls += ` ${prefixCls}-tab-disabled`;
      } else {
        events = {
          onClick: this.onTabClick.bind(this, key),
        };
      }
      const ref = {};
      if (activeKey === key) {
        ref.ref = 'activeTab';
      }
      rst.push(<div
        role="tab"
        aria-disabled={child.props.disabled ? 'true' : 'false'}
        aria-selected={activeKey === key ? 'true' : 'false'}
        {...events}
        className={cls}
        key={key}
        {...ref}
      >
        {child.props.tab}
      </div>);

这里不处理的话，叉号不显示的时候，tab宽度是不应该变窄的

    &&-editable-card > &-bar &-tab:not(&-tab-active):not(&-tab-uncloseable):hover {
       padding-left: 8px;
       padding-right: 8px;
     }

2017-02-10 03:43 UTC, afc163 commented
closeable => closable

2017-02-10 03:44 UTC, afc163 commented on components/tabs/index.tsx
>                {child.props.tab}
```jsx
cloneElement(child.props.tab, {
  className: classNames(child.props.className, {
    ['xxx-closable']: !!child.props.closable,
  }),
})
```

2017-02-10 03:58 UTC, afc163 commented on components/tabs/index.tsx
>                {child.props.tab}
确实 tab 上加 className 会比较麻烦。

2017-02-10 04:02 UTC, afc163 commented on components/tabs/index.tsx
>                {child.props.tab}
可以把原来的样式改成这样：

<img width="429" alt="image" src="https://cloud.githubusercontent.com/assets/507615/22813708/c37c5f82-ef88-11e6-9ba8-0e5e48b15959.png">

2017-02-10 07:08 UTC, lixiaoyang1992 commented on components/tabs/index.tsx
>                {child.props.tab}
根据这个思路，修改完了

2017-02-10 07:11 UTC, afc163 commented on components/tabs/index.tsx
> +            <div className={ closable ? undefined : `${prefixCls}-tab-unclosable` }>
`className={}` 前后不加空格。

2017-02-13 07:43 UTC, benjycui approved these changes

2017-02-13 07:43 UTC, merged

2017-02-14 03:09 UTC, benjycui commented
Close: https://github.com/ant-design/ant-design/issues/4286