fix: change empty font color to text description
ant-design/ant-design pull request #48131
Opened 2024-03-27 13:26 UTC by LonelySnowman

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/48124

### 💡 Background and solution

change empty description font style --ant-color-text to --ant-color-text-description

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | change empty description font color to --ant-color-text-description |
| 🇨🇳 Chinese | 将 Empty 组件描述字体颜色更改为 --ant-color-text-description |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2024-03-27 13:28 UTC, afc163 submitted a review, later dismissed

2024-03-28 07:13 UTC, afc163 commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
![图片](https://github.com/ant-design/ant-design/assets/507615/43164347-34d3-44bd-b96a-d2e5005c053d)

这个感觉不太对。

2024-03-28 07:53 UTC, LonelySnowman commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
我的疏忽，应该改为 token.colorTextDisabled

2024-03-28 08:12 UTC, afc163 commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
感觉是符合预期的，我看 4.x 就是这样。https://4x.ant.design/components/empty/

2024-03-28 08:17 UTC, LonelySnowman commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
目前的代码中只有 image = Empty.PRESENTED_IMAGE_SIMPLE 会展示 token.colorTextDescription，是需要全部换为展示 token.colorText ？

https://github.com/ant-design/ant-design/blob/master/components/empty/style/index.ts#L65-L71 发现这段 css 没有被使用，等下可以删掉

2024-03-29 03:47 UTC, afc163 commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
应该是只有 PRESENTED_IMAGE_SIMPLE 是使用 colorTextDescription，其他都是 colorText。

2024-03-29 09:44 UTC, LonelySnowman commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
已更改
这个 issue https://github.com/ant-design/ant-design/issues/48124 是要求统一 description 的颜色
这下 PRESENTED_IMAGE_SIMPLE 和 PRESENTED_IMAGE_DEFAULT 会展示 colorTextDescription 其余均为 colorText

2024-03-31 09:32 UTC, afc163 commented on components/empty/style/index.ts
> +        color: token.colorTextDescription,
我感觉原来的文字颜色没问题，可能就是这么设计的。

2024-04-02 07:55 UTC, yoyo837 commented
rebase

2024-04-02 09:20 UTC, afc163 requested changes
我感觉原来的文字颜色没问题，可能就是这么设计的。

2024-04-02 10:22 UTC, LonelySnowman commented
GET，那这个 PR 就关闭了？

2024-04-02 10:42 UTC, closed without merging