fix: TableTransfer 反选当前页无效
ant-design/ant-design pull request #48248
Opened 2024-04-03 09:33 UTC by xiaozisong

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
#48241 

### 💡 Background and solution
Background：官网transfer组件demo中的table-transfer无法反选/取消反选
solution：list组件中第346行代码，在某些场景下组件是传递children了的，导致listBodyRef.current无法获取到keys数组，解决方法是通过判断listBodyRef.current.items的length，为空则取dataSource
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix TableTransfer unselecting the current page is invalid      |
| 🇨🇳 Chinese |       修复TableTransfer 反选当前页无效    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2024-04-03 09:40 UTC, yoyo837 commented on components/transfer/list.tsx
> +              ? listBodyRef.current?.items.map((entity) => entity.item)
```suggestion
              ? listBodyRef.current.items.map((entity) => entity.item)
```

2024-04-03 09:51 UTC, xiaozisong commented
> #48241
需要bug修复 刚才跑了一下 发现确实有这个问题

2024-04-03 09:52 UTC, yoyo837 commented
添加测试用例覆盖

2024-04-03 09:53 UTC, xiaozisong commented
需要晚一点  等今晚或者明天

2024-04-09 13:34 UTC, afc163 commented on components/transfer/list.tsx
> +          const list = document.querySelector(`#${id} .ant-table-tbody`)?.childNodes || [];
不应该有 dom 操作。

2024-04-09 13:34 UTC, afc163 requested changes
不应该有 dom 操作。

2024-04-18 08:01 UTC, afc163 commented
See https://github.com/ant-design/ant-design/issues/48241

2024-04-18 09:45 UTC, closed without merging