chore: add open with opensumi badge
ant-design/ant-design pull request #48401
Opened 2024-04-11 08:38 UTC by Aaaaash

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

![image](https://github.com/ant-design/ant-design/assets/17701805/7151bb88-bc26-42ec-a7a8-95e3147b0db5)

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add a badge opened with opensumi.run in README  |
| 🇨🇳 Chinese | README 中添加使用 opensumi.run 打开的 badge |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2024-04-11 08:49 UTC, MadCcc approved these changes, later dismissed
LGTM

2024-04-11 09:51 UTC, afc163 requested changes
挪到 https://github.com/ant-design/ant-design?tab=readme-ov-file#%EF%B8%8F-development 这里。

2024-04-11 11:30 UTC, Aaaaash commented
> 挪到 https://github.com/ant-design/ant-design?tab=readme-ov-file#%EF%B8%8F-development 这里。

好的

2024-04-12 03:33 UTC, vagusX approved these changes

2024-04-12 03:46 UTC, afc163 approved these changes

2024-04-12 03:46 UTC, merged