add custom selection in Table
ant-design/ant-design pull request #4962
Opened 2017-02-20 08:17 UTC by infeng

#2651 
- add `rowSelection.selections` that is add custom selection.
- add `rowSelection.onSelectInvert` that is callback that is called when select invert.
- add `rowSelection.onSelection` that is callback that is called when select custom selection.

2017-02-20 09:06 UTC, afc163 commented
Run `npm test -- -u` to update snapshots.

2017-02-20 09:16 UTC, benjycui commented on components/table/index.zh-CN.md
> +| selections | 自定义选择项 | {key: string, text: string}[] | - |
text 建议支持 `React.ReactNode`，因为国际化时会用到 `<FormattedMesage ... />` 之类

2017-02-20 09:20 UTC, benjycui commented on components/table/index.zh-CN.md
> +| onSelection | 用户选择自定义选择项的回调 | Fcuntion(key, changableRowKeys) | - |
建议 `onSelection` 合并为 `selections[n].onSelect`，这样就不需要用到 `switch` 了。

2017-02-20 09:24 UTC, infeng commented on components/table/index.zh-CN.md
> +| onSelection | 用户选择自定义选择项的回调 | Fcuntion(key, changableRowKeys) | - |
用`switch`确实不好，我改一下

2017-02-20 09:32 UTC, benjycui commented
有个疑问，如果我只需要全选和反选，现在的 API 好像不怎么友好？

2017-02-20 09:38 UTC, afc163 commented on components/table/index.zh-CN.md
> +| selections | 自定义选择项 | {key: string, text: string}[] | - |
onSelectInvert 和 `selections[n].onSelect` 都不需要的，都在 `rowSelection.onChange` 里就够了。

2017-02-20 09:39 UTC, infeng commented
现在是默认有全选和反选，如果只需要全选和反选，不需要设置什么，不过这样有一个问题是不能去除全选和反选

2017-02-20 09:43 UTC, infeng commented on components/table/index.zh-CN.md
> +| selections | 自定义选择项 | {key: string, text: string}[] | - |
这样`rowSelection.onChange`的参数需要改一下，我是想着不改变原本的属性，所以才加了`onSelectInvert`和`selections[n].onSelect`

2017-02-20 10:02 UTC, benjycui commented
> 现在是默认有全选和反选，如果只需要全选和反选，不需要设置什么，不过这样有一个问题是不能去除全选和反选

原来的使用方式要保留，然后如果不设置，就是原来的交互。

2017-02-20 10:10 UTC, afc163 commented
我觉得默认带全选和反选问题不大吧。

2017-02-20 10:12 UTC, afc163 commented
travis 还是挂的。

2017-02-20 12:51 UTC, afc163 commented
Add some test case?

2017-02-21 06:31 UTC, benjycui commented
👍

2017-02-23 02:56 UTC, afc163 requested changes
需要补充测试用例。

2017-02-23 07:26 UTC, afc163 commented
`rm -rf node_modules && npm install && npm test -- -u`

2017-02-23 07:30 UTC, infeng commented
是什么问题会导致生成的snapshot不对 :joy:

2017-02-23 07:38 UTC, afc163 commented
因为 rc-table 发了一个 patch。

2017-02-23 08:04 UTC, infeng commented
已加上几个测试用例

2017-02-23 08:14 UTC, afc163 approved these changes

2017-02-23 11:29 UTC, merged

2017-03-06 02:30 UTC, yesmeck commented
这个好像跟设计稿不一样？ checkbox 没对齐。

<img width="116" alt="dingtalk20170306103018" src="https://cloud.githubusercontent.com/assets/465125/23594812/eb4f873c-0257-11e7-9285-6ab9a859f649.png">

2017-03-06 02:33 UTC, infeng commented
这个没注意到，我改一下

2017-03-06 06:59 UTC, yesmeck commented
问了设计师距离，我来调整下吧。

2017-09-15 09:21 UTC, tailorsira commented
官网没有全选反选的例子？只有一个选择奇数行和偶数行的例子，点击后还无效，配置项里加了rowCounterSelection无效