filter the disabled options
ant-design/ant-design pull request #4981
Opened 2017-02-21 09:11 UTC by tianlizhao

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.
1、修复Transfer穿梭框这个组件，当选择已经被checked的时候，通过事件disable，然后还可以移动到左/右边

2017-02-21 09:52 UTC, afc163 commented on components/transfer/index.tsx
> +    });
```js
const newMoveKeys = moveKeys.filter(key => !dataSource.some(data => key === data.key && data.disabled));
```

2017-02-21 09:53 UTC, afc163 commented
<img width="314" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23159663/9c5ee954-f85e-11e6-83eb-b3f114c18298.png">

2017-02-21 10:03 UTC, tianlizhao commented
我要设置下我的email么？

2017-02-21 10:06 UTC, afc163 commented
否则无法出现在贡献者里。https://github.com/ant-design/ant-design/graphs/contributors

2017-02-21 10:13 UTC, tianlizhao commented
好的，我把我邮箱加上了

2017-02-21 10:14 UTC, afc163 commented
并没有变化：https://github.com/ant-design/ant-design/pull/4981/commits/34cfd9f890a68be46e3517290bb060d36ac0c4c5

2017-02-21 10:18 UTC, afc163 requested changes
1. 邮箱无法识别。
2. 按评论简化下代码。
3. 如果有时间的话，麻烦写一个用例如何？

2017-02-21 11:17 UTC, afc163 commented
```
components/transfer/index.tsx(164,65): error TS2345: Argument of type '(data: TransferItem) => boolean | undefined' is not assignable to parameter of type '(value: TransferItem, index: number, array: TransferItem[]) => boolean'.

  Type 'boolean | undefined' is not assignable to type 'boolean'.

    Type 'undefined' is not assignable to type 'boolean'.
```

typescript 语法有问题。

2017-02-21 12:48 UTC, tianlizhao commented
实在搞不明白了，我改了几次，每次都会有一个test文件不通过，我该怎么办呢？
我在本地`npm run lint`没有报错

2017-02-21 12:50 UTC, tianlizhao commented
可以写一个用例，有没有模板呢？写在哪里？

2017-02-21 14:11 UTC, afc163 commented
`__test__` 目录下就是。

2017-02-21 14:19 UTC, afc163 commented
test 不过的原因在这里：https://github.com/ant-design/ant-design/commit/79f222b86c8e30860c18330dd6decd9dc7d35515

主干已修复，rebase 一下即可。

2017-02-22 02:18 UTC, benjycui commented
Why did this happen?

Actually, disabled options should not be selectable...

2017-02-22 02:18 UTC, benjycui commented
And it's not selectable https://ant.design/components/transfer/#components-transfer-demo-basic

2017-02-22 05:51 UTC, tianlizhao commented
@benjycui 正常情况下disabled的选项是不可以选中的。只有当选项被选中后，再通过别的组件调用了render方法，动态disabled的时候会出现这样的问题。
如下：
左边选项是根据region动态改变disabled
![image](https://cloud.githubusercontent.com/assets/7292160/23198800/0a815a24-f905-11e6-911b-3e2159adea51.png)
如果先选择了option,再通过region过滤的话，就会出现已经被勾选的被disabled
![image](https://cloud.githubusercontent.com/assets/7292160/23198823/24d2613e-f905-11e6-97b7-e2f84e13d53b.png)
但是可以正常移动到右边
![image](https://cloud.githubusercontent.com/assets/7292160/23198827/2b164f74-f905-11e6-93e6-bd86d9db7ba4.png)

我也想过是否可以在render方法里把disabled的option去掉选中状态，但是看API和源码，没有发现可以在render里设置，好像只可以用selectedKeys也自己维护了。
按照正常逻辑的话，我还是觉得被disabled的option是不可以移动的，不管是不是被勾选状态。

2017-02-22 07:01 UTC, benjycui submitted a review, later dismissed
补充用例后就可以合了。

2017-02-22 09:30 UTC, afc163 approved these changes

2017-02-22 09:32 UTC, benjycui commented
你这样修改单测，和你这次逻辑的修改没关系吧。

把这个单测修改回滚。

新增一个单测，其实就是把你 https://github.com/ant-design/ant-design/pull/4981#issuecomment-281576532 说你话转成测试代码就可以了。

Thanks

然后不急的，周末才发版本，慢慢来吧

2017-02-22 09:50 UTC, tianlizhao commented
@benjycui 嗯嗯。好的，改的时候也觉得不太对，哈哈，好的，闲了我重写下

2017-02-23 01:35 UTC, benjycui commented
@tianlizhao just remove `[WIP]` in title when you have done.

2017-02-24 09:40 UTC, afc163 commented
@tianlizhao any progress?

2017-02-24 09:51 UTC, tianlizhao commented
今天下班回家弄吧，是周末才发吧？还是今天 ？

2017-02-24 10:06 UTC, afc163 commented
2.8 没这么快发，今天会发 master。不过你这个就差个用例了，估计花不了半小时。

2017-02-24 10:07 UTC, tianlizhao commented
好的，我现在试试

2017-02-24 10:53 UTC, afc163 commented on components/transfer/__tests__/index.test.js
> +  targetKeys: [],
可以多加一个不是 disabled 的 b 数据，保证 b 会被移动过去。

2017-02-24 10:53 UTC, tianlizhao commented
提交了，不过写的有点不好，本来想共享 `listCommonProps` 变量的，没找到如何在test case里面把一个`checkbox` 动态`disabeld`掉，只能自己再写一个`listDisabledProps`，一开始就`disabled=true`，如果有更好的方式，请告诉我，谢谢了。

2017-02-24 10:53 UTC, afc163 commented
没关系，分开也清晰点。

2017-02-24 10:55 UTC, tianlizhao commented on components/transfer/__tests__/index.test.js
> +  targetKeys: [],
好的

2017-02-24 11:08 UTC, merged

2017-02-24 11:08 UTC, afc163 commented
Great job!!! @tianlizhao

2017-02-25 02:41 UTC, benjycui commented
Excellent 👍