[WIP] feat: ColorPicker support gradient color
ant-design/ant-design pull request #50050
Opened 2024-07-24 12:23 UTC by zombieJ

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2024-07-25 06:53 UTC, li-jia-nan commented on components/color-picker/style/index.ts
> +        transformOrigin: `calc(100% - 1px) 1px`,
这里不用 token 吗？

2024-07-25 07:00 UTC, zombieJ commented on components/color-picker/style/index.ts
> +        transformOrigin: `calc(100% - 1px) 1px`,
看看上面一行 😈

2024-07-25 09:01 UTC, li-jia-nan commented on components/color-picker/__tests__/index.test.tsx
> +    console.log('disable');
console

2024-07-25 11:59 UTC, zombieJ commented
@SocketSecurity ignore npm/@ant-design/tools@18.0.2
@SocketSecurity ignore npm/sharp@0.33.4
@SocketSecurity ignore npm/@biomejs/biome@1.8.3

2024-07-25 14:09 UTC, li-jia-nan submitted a review, later dismissed

2024-07-26 02:23 UTC, li-jia-nan commented
大了 1.77kb

2024-07-26 03:30 UTC, zombieJ commented
> 大了 1.77kb

多了一个 fast-color，全部替换掉后会还回去 2KB

2024-07-26 03:46 UTC, li-jia-nan submitted a review, later dismissed

2024-07-26 03:54 UTC, afc163 commented
为啥没有 preview 和 size-limit 链接

2024-07-26 04:15 UTC, afc163 commented on components/color-picker/demo/line-gradient.md
> +Basic Usage.
这个文案不太对。

2024-07-26 04:17 UTC, afc163 requested changes
1. 渐变色演示的描述不太对。
2. 添加一个节点后，如何删除掉？
3. 点击节点白色外圈时不会选择节点，会创建一个新节点。这里要多给点容错度，不然很容易在相近位置点好几个出来。

2024-07-26 07:09 UTC, zombieJ commented
#### 渐变色演示的描述不太对。

Updated

#### 添加一个节点后，如何删除掉？

拖拽到外部，或者删除按键（出了 BUG 删不掉，已经修复并添加测试）

#### 点击节点白色外圈时不会选择节点，会创建一个新节点。这里要多给点容错度，不然很容易在相近位置点好几个出来。

Updated

#### input 内的 selection 效果还需不需要做？

Updated，编辑渐变色同步高亮文本。

#### 好像不支持角度？

嗯，这一期不支持。

#### 键盘操作好像也不太行。

同上，fixed

2024-07-26 08:26 UTC, li-jia-nan commented on components/color-picker/__tests__/gradient.test.tsx
> +    console.log('~~~~~~~~~~~~');
console 没删大佬

2024-07-26 14:49 UTC, afc163 approved these changes, later dismissed

2024-07-26 14:49 UTC, afc163 commented
<img width="340" alt="图片" src="https://github.com/user-attachments/assets/154c5e86-f4c0-4c2e-a50e-8e14794a6031">

左边应该垂直居中不？

2024-07-26 14:51 UTC, li-jia-nan commented
> 左边应该垂直居中不？

我感觉没必要，如果很高的话，左边的色块就在很下面了，不过感觉可以问问设计师的意见？

2024-07-26 18:39 UTC, wanpan11 commented
感觉这个当前 选中的节点 不太明显 😂

<img width="491" alt="image" src="https://github.com/user-attachments/assets/f9b402de-f815-4830-bd32-d874c0ff71fb">

2024-07-28 13:42 UTC, li-jia-nan commented on components/slider/style/Context.ts
> +  direction?: 'ltr' | 'rtl';
```suggestion
  direction?: DirectionType;
```

2024-07-29 02:14 UTC, zombieJ commented
> 左边应该垂直居中不？

原本是垂直居中的，切多行时不稳定感会加深丑的感觉。所以固定在上面位置了。

2024-07-29 02:53 UTC, MadCcc commented
1. 色相和透明度的拖动条感觉不需要点击之后放大节点（不如说感觉默认状态下的 handler 太小了）。如果要展示 focus 状态的话建议和 slider 一致，hover 的时候就放大。
2. 点击清除颜色后再选择颜色，渐变色条颜色不对。个人意见渐变色从无色恢复到有色时是不是默认添加两个节点比较好？
![image](https://github.com/user-attachments/assets/f66f14d2-1dfc-4122-b878-26156a3028a1)
3. 清除颜色的按钮布局在渐变色与单色下都有点难看，左边空了一大块，渐变色下更加明显了。

2024-07-29 07:18 UTC, zombieJ commented
@SocketSecurity ignore npm/esbuild@0.18.20
@SocketSecurity ignore npm/@swc/core@1.4.2

2024-07-29 07:26 UTC, afc163 commented
弹出动画貌似不太对，应该从左上角位置弹出。

> 当然最好从箭头位置弹出。

2024-07-29 07:42 UTC, zombieJ commented
> 弹出动画貌似不太对，应该从左上角位置弹出。

业界的 ColorPicker 默认都是左下弹出，因为人们习惯性不会给 ColorPicker 留上方空间来进行选择。这和 Select 类组件逻辑是类似的，优先下方，不够再翻转。

<img width="280" alt="截屏2024-07-29 15 38 00" src="https://github.com/user-attachments/assets/e7979078-91bc-490b-97c2-0402fc44cab5">


<img width="364" alt="截屏2024-07-29 15 37 07" src="https://github.com/user-attachments/assets/e29bfc6d-cee4-493f-83ca-98855db22e11">

<img width="402" alt="截屏2024-07-29 15 42 10" src="https://github.com/user-attachments/assets/a8b2b28e-b8e7-4a0f-aa22-7f9ceb765a50">


弹出中心不对看起来是 Popover 的问题，可以在 master 里开新的 Patch 修一下~

2024-07-29 07:46 UTC, zombieJ commented
> 色相和透明度的拖动条...

Updated

> 点击清除颜色后再选择颜色...

Fixed

> 清除颜色的按钮布局在渐变色与单色下都有点难看，左边空了一大块，渐变色下更加明显了。

单选之前也是这样，暂时先不改这个布局了。

2024-07-29 07:59 UTC, li-jia-nan approved these changes

2024-07-29 08:01 UTC, MadCcc approved these changes

2024-07-29 08:16 UTC, afc163 commented
> 弹出动画貌似不太对，应该从左上角位置弹出。

我意思是弹出动画的方向，应从箭头位置为起点弹出。

2024-07-29 08:38 UTC, merged

2024-07-29 08:59 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/50028 这个还需要么

2024-07-29 11:42 UTC, afc163 commented
<img width="318" alt="图片" src="https://github.com/user-attachments/assets/d16d7082-2dda-4215-9600-997b406ec7fb">

选中之后按左右键，是不是可以改变百分比？

2024-07-29 12:51 UTC, zombieJ commented
> 选中之后按左右键，是不是可以改变百分比？现在没有这个交互

和 删除、添加 节点的事件时机有冲突，渐变色的键盘左右先去掉了

2024-08-07 03:24 UTC, mufeng889 commented
大佬   能让token支持渐变色吗？

2025-03-06 04:07 UTC, diqye commented
无法指定渐变方向。