refactor(useLocale): make component locale overriding locale from con…
ant-design/ant-design pull request #50213
Opened 2024-08-02 13:56 UTC by Asanio06

…text

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

Today, if I inject parameters into the `locale` props in my Calendar component, it doesn't take them into account if I already have a `locale` in my ConfigProvider. This means that I can't have a global configuration that I override for specific cases.

### 📝 Changelog

refactor(useLocale): make component locale overriding locale from context

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |        X   |
| 🇨🇳 Chinese |           |

2024-08-02 13:58 UTC, afc163 commented
Please create a online reproduce and describe what problem this PR you want to resolve?

2024-08-02 13:58 UTC, afc163 requested changes
Please create a online reproduce and describe what problem this PR you want to resolve?

2024-08-02 13:59 UTC, li-jia-nan commented on package.json
> +  "version": "5.20.0",
Please do not modify the version

2024-08-03 08:39 UTC, Asanio06 commented
Sorry i will make all change you talk about

2024-08-04 05:39 UTC, Asanio06 commented on package.json
> +  "version": "5.20.0",
Sorry, i have change that

2024-08-04 05:40 UTC, Asanio06 commented
Hello @afc163 , I've updated my code to be clearer and not to cause any breaking changes.
Here some exemple : https://stackblitz.com/edit/react-o7hv5j?file=demo.tsx
You can see that if you remove ConfigProvider locale, all we work fine

2024-08-05 05:20 UTC, closed without merging