[WIP] Add Demo for Certain Category
ant-design/ant-design pull request #5105
Opened 2017-02-28 10:26 UTC by RaoHai

+ close #5095
 + support OptGroup of AutoComplete

pre PR here, waitting for the design draft.

2017-02-28 12:33 UTC, JesperWe commented
Thanks a lot, I think it was the missing docs for dataSource hierarchy with .children that I missed the most.

Some comments on the commit: 

- `optionLabelProp="text"` seems to be unused, and this prop is not in the API docs. 
- Using `dropdownMatchSelectWidth={false}` and `dropdownStyle={{ width: 300 }}` at the same time seems redundant, and these props are not in the API docs either.

2017-03-01 01:53 UTC, benjycui commented
And we can add link to demo in https://ant.design/docs/spec/reaction#Lookup-Patterns

2017-03-01 02:51 UTC, RaoHai commented
@JesperWe 

* `optionLabelProp` is the prop value of option which will be rendered as content of select.
* `dropdownMatchSelectWidth` means whether dropdown has same with with select field, when true, overriding with in `dropdownStyle` will not take effect.
* `AutoComplete` is implemented by `Select` recently. Some props are inherited.

I updated the document, now all the props of demo should have been used.

2017-03-02 02:31 UTC, yesmeck requested changes

2017-03-02 02:31 UTC, yesmeck commented on components/auto-complete/index.tsx
> +        (childArray[0] as React.ReactElement<any>).type === OptGroup
https://github.com/ant-design/ant-design/issues/4655

2017-03-02 02:31 UTC, yesmeck commented on components/auto-complete/demo/certain-category.md
> +  return (<span>
换行

2017-03-02 06:12 UTC, RaoHai commented on components/auto-complete/index.tsx
> +        (childArray[0] as React.ReactElement<any>).type === OptGroup
要改到 rc-select 里去？

2017-03-02 06:14 UTC, yesmeck commented on components/auto-complete/index.tsx
> +        (childArray[0] as React.ReactElement<any>).type === OptGroup
那这里应该用 `isSelectOption ` 和 `isSelectOptGroup` 判断吧。

2017-03-02 06:50 UTC, RaoHai commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
好像只能这样写了。。

2017-03-03 03:27 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
直接 `(child as any).isSelectOption` 就可以了。

2017-03-03 03:30 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
直接上面的 `React.ReactChild` 换成 any 就可以了吧。

2017-03-03 03:31 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
但是要判断下`child.type`是不是存在。

2017-03-03 03:34 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
不需要判断。。。

2017-03-03 06:14 UTC, RaoHai commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
类型推导严谨一些嘛 😢

2017-03-03 06:18 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = ((child as React.ReactElement<any>).type) as OptionClass<any>;
判断 `child.type` 还是需要的，因为 `child` 可能是字符串之类的，`(child as React.ReactElement<any>)` 这里已经不严谨了其实，`child` 不一定是 `React.ReactElement` 的。

2017-03-03 06:26 UTC, RaoHai commented on components/auto-complete/index.tsx
> +  const element = child.type as OptionClass<any>;
这样吧， `type ReactChild = ReactElement<any> | string | number;`
排除掉 string 和 number 之后就可以安全的 .type 了

2017-03-03 06:32 UTC, yesmeck commented on components/auto-complete/index.tsx
> +  const element = child.type as OptionClass<any>;
感觉 `child` 的类型就是 `any`，`null`、`undefined`、`boolean` 都有可能的。

2017-03-03 08:25 UTC, RaoHai commented
没啥问题的话我 rebase -i 一下然后合了吧

2017-03-03 08:26 UTC, yesmeck commented
👌

2017-03-03 14:10 UTC, merged