fix: form.item vertical height
ant-design/ant-design pull request #51743
Opened 2024-11-22 10:41 UTC by Bbbtt04

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #51626

### 💡 Background and Solution

覆盖了Form对item的样式影响
![image](https://github.com/user-attachments/assets/ea8ad79d-7dd0-4771-b17d-6482dbca049b)

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fixed form.item in form.list losing height when using layout="vertical" alone |
| 🇨🇳 Chinese | 修复 form.list 中form.item 单独使用layout="vertical" 会失去高度|

2024-11-25 13:28 UTC, ajenkins-mparticle approved these changes
I found this as well! I changed this to `flex: unset` - none is the same.

My approval means nothing, but thank you!

2024-11-25 14:20 UTC, afc163 commented
Visual diff 有点问题。

2024-11-25 14:25 UTC, ajenkins-mparticle commented
@afc163 it's not a problem, the visual diff just shows that the bug is indeed fixed.

I left a easy visual repro of the problem here: 

![image](https://github.com/user-attachments/assets/ab143a38-22b4-41f7-b939-a97021fa06dc)


https://stackblitz.com/edit/react-3aevyn?file=demo.tsx

2025-01-04 08:20 UTC, Bbbtt04 commented
> Visual diff 有点问题。

现在貌似好了 @afc163

2025-01-04 08:33 UTC, Bbbtt04 commented
> Visual diff 有点问题

![1735979465616](https://github.com/user-attachments/assets/f48821c6-4a3e-4649-a490-431ffb9af543)
![1735979465620](https://github.com/user-attachments/assets/4b4a742e-9624-46f3-8ed8-40b8aca03b95)

 因为原来的高度有问题，所以这里原来的<br/>现在看起来间距变大了些 @afc163

2025-01-04 08:44 UTC, Bbbtt04 commented
> > Visual diff 有点问题
> 
> ![1735979465616](https://private-user-images.githubusercontent.com/89759610/400127021-f48821c6-4a3e-4649-a490-431ffb9af543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5ODA1MjEsIm5iZiI6MTczNTk4MDIyMSwicGF0aCI6Ii84OTc1OTYxMC80MDAxMjcwMjEtZjQ4ODIxYzYtNGEzZS00NjQ5LWE0OTAtNDMxZmZiOWFmNTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA4NDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2FmZjY2ZTE0MjVlYzA0NmRmMjkyZDIwY2I3ZmM5NzMxZDBmYTNjMzk5ZTk5OTRkZTQyNWVlMDUzOWZiNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XuMgl5HrFURjXY-13S5wl82zMf3EQKe_Y9jaFkEuTfo) ![1735979465620](https://private-user-images.githubusercontent.com/89759610/400127012-4b4a742e-9624-46f3-8ed8-40b8aca03b95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5ODA1MjEsIm5iZiI6MTczNTk4MDIyMSwicGF0aCI6Ii84OTc1OTYxMC80MDAxMjcwMTItNGI0YTc0MmUtOTYyNC00NmYzLThlZDgtNDBiOGFjYTAzYjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA4NDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MzMxYmE4N2VkODIxYWMxZTllNDdiZTc0ZTkyNzE3MTdkZDgwM2Y4YmY1YmZkNmZmYmMyZDAxN2Q3YzRmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3i7sxwWZiewqqavUz2Nxf56C6qsDHqfeXQ0H5w0sNlE)
> 
> 因为原来的高度有问题，所以这里原来的现在看起来间距变大了些 @afc163

br

2025-01-04 08:53 UTC, yoyo837 commented
看着像border粗细不同呢

2025-01-04 08:58 UTC, Bbbtt04 commented
> 看着像border粗细不同呢

第一个button代码没修改但是这次扫描出来Visual diff不一致，不清楚是不是报告的问题

2025-01-04 21:31 UTC, ajenkins-mparticle commented
@yoyo837 the author didn't change the border, so that's not possible.

@afc163 is there any chance we could get another review of this one? It's a valid bug, the visual diff is correct - it was wrong before and now the bug is fixed by @Bbbtt04 - and I would love to have this fixed.

2025-04-24 19:40 UTC, ajenkins-mparticle commented
@Bbbtt04 and/or @afc163  Do we have to wait until antd 6 to get this because it's a "breaking" layout change, despite the fact that it fixes a layout bug?

2026-07-22 10:43 UTC, afc163 requested changes
Please rebase onto the current target branch and add focused regression/visual coverage for the Form.Item vertical-height behavior. The issue is still valid, but the current proof is not sufficient for a layout change.

2026-09-10 09:04 UTC, QDyanbing commented
https://github.com/ant-design/ant-design/pull/59263

2026-09-10 09:04 UTC, closed without merging