+ call onCancel when pressing esc key
ant-design/ant-design pull request #5209
Opened 2017-03-08 05:35 UTC by elios264

I think this is it, 

BUT, I couldn't test in on my computer since I use windows, and I can't get it to compile.

2017-03-09 01:28 UTC, benjycui commented on components/modal/Modal.tsx
> +  destroy: (e) => void
ref: https://github.com/ant-design/ant-design/issues/2110

Here is a problem, if developers call destroy, should he pass an event to it?

2017-03-09 01:28 UTC, benjycui commented on components/modal/Modal.tsx
> +  destroy: (e) => void
cc @afc163 @RaoHai

2017-03-09 03:35 UTC, afc163 commented on components/modal/confirm.tsx
> +      props.onCancel(e);
Put `props.onCancel` outside `if`.

2017-03-09 03:37 UTC, afc163 commented on components/modal/confirm.tsx
> +      props.onCancel(e);
```jsx
function close(...args) {
  ...

  props.onCancel(...args);
}
```

prevent problem @benjycui describes

2017-03-09 08:06 UTC, afc163 requested changes
check comments

2017-03-09 14:00 UTC, afc163 commented
@elios264

2017-03-10 02:10 UTC, benjycui approved these changes

2017-03-10 02:55 UTC, merged