RadioGroup add optional support
ant-design/ant-design pull request #5466
Opened 2017-03-24 02:01 UTC by ascoders

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you propose PR to correct branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

2017-03-24 03:42 UTC, benjycui commented on components/radio/group.tsx
> +          return React.cloneElement(radio, assign({}, radio.props, {
This will have conflict with @yesmeck 's refactoring https://github.com/ant-design/ant-design/commit/ab6e521ea221f19f7fd3604237c9380fb70c7cec

2017-03-24 03:42 UTC, benjycui commented
Pending.

2017-03-24 03:43 UTC, yesmeck commented
Write a test plz.

2017-03-24 04:28 UTC, ascoders commented on components/radio/group.tsx
> +          return React.cloneElement(radio, assign({}, radio.props, {
But not on current branch, can we solve it later?

2017-03-24 04:29 UTC, ascoders commented on components/radio/group.tsx
> +          return React.cloneElement(radio, assign({}, radio.props, {
Or to merge @yesmeck 's changes first, because there are more changes, I do not want to repeat the work.

2017-03-27 01:48 UTC, ascoders commented
Test has been added, so can we merge it?

2017-03-27 02:11 UTC, benjycui commented
`master` had been merged into `feature-2.9`, could you rebase it?

2017-03-27 02:12 UTC, benjycui commented
> This will have conflict with @yesmeck 's refactoring ab6e521

And @yesmeck 's refactoring had been merged into `feature-2.9` now.

2017-03-27 03:33 UTC, yesmeck requested changes

2017-03-27 03:33 UTC, yesmeck commented on components/radio/__tests__/group-optional.test.js
> +describe('Radio', () => {
不要 copy 代码，这里只要测试下去给 `options` 的时候也能正确  render 就可以了，写在 group.test.js 里即可。

2017-03-27 06:19 UTC, ascoders commented
I rebase upstream/feature-2.9 right now...

2017-03-27 06:24 UTC, ascoders commented
> `master` had been merged into `feature-2.9`, could you rebase it?

But so many file changed? If has been merged, pr will only show my own changes.

2017-03-27 06:53 UTC, benjycui commented
Oops... maybe just open a new PR.

2017-03-27 12:41 UTC, ascoders commented
to #5514

2017-03-27 12:41 UTC, closed without merging