Notification and Message add className and style
ant-design/ant-design pull request #6014
Opened 2017-05-04 07:11 UTC by lixiaoyang1992

Notification and Message add className and style

#5893

2017-05-04 07:21 UTC, xueqingxiao approved these changes

2017-05-04 07:32 UTC, afc163 commented on components/message/index.en-US.md
> +- `message.loading(content, duration, onClose, className, style)`
`message.info(<div className="" style={{ .... }}></div>)` will be enough.

2017-05-04 07:32 UTC, afc163 commented on components/message/index.en-US.md
> +- `message.loading(content, duration, onClose, className, style)`
The long arguments is a disaster..

2017-05-04 07:51 UTC, afc163 requested changes
Don't change message cause arguments is too long.

2017-05-04 08:12 UTC, lixiaoyang1992 commented
fixed. Now only Notification has been changed.

2017-05-05 06:26 UTC, merged

2017-05-05 06:27 UTC, benjycui commented
新增 feature 应该同时更新 API 文档，这次我补上，以后注意吧。