Create fa_IR.tsx
ant-design/ant-design pull request #6456
Opened 2017-06-13 13:01 UTC by farskid

Added fa_IR locale for Persian language.

2017-06-13 13:20 UTC, farskid commented
Seems like there is a deep dependency between locales of ant-design and other packages such as rc-pagination.
Should I update locales of all packages and components at once?

2017-06-13 13:22 UTC, afc163 commented
Yep, like https://github.com/react-component/pagination/pull/88 and https://github.com/react-component/calendar/pull/264 did.

2017-06-13 13:23 UTC, farskid commented
@afc163 Thanks for the rapid reply. I'll update the PR soon :)

2017-06-21 07:39 UTC, benjycui commented
ping~ @farskid

2017-06-21 07:40 UTC, farskid commented
@benjycui Sorry for the delay, I'll finish it today :)

2017-06-21 15:14 UTC, farskid commented
@benjycui I sent PR to pagination, calendar and m-datepicker. pagination and calendar have been merged and released. What's the next step?

2017-06-22 02:43 UTC, afc163 commented
Check the travis log and make sure it pass.

2017-06-22 02:45 UTC, afc163 commented
https://github.com/ant-design/ant-design/pull/5529

2017-06-28 07:46 UTC, benjycui commented on components/locale-provider/fa_IR.tsx
> +import Calendar from '../calendar/locale/fa_IR';
```jsx
import DatePicker from '../date-picker/locale/fa_IR';
import TimePicker from '../time-picker/locale/fa_IR';
import Calendar from '../calendar/locale/fa_IR';
```

There are missing.

2017-07-04 01:56 UTC, afc163 requested changes
ci breaks

2017-07-06 01:17 UTC, benjycui commented
Close for no response.

2017-07-06 01:17 UTC, closed without merging