Update Form.tsx
ant-design/ant-design pull request #6503
Opened 2017-06-16 14:37 UTC by Midqiu

getFieldDecorator 的 options 参数增加 onChange 说明。

2017-06-16 15:46 UTC, yesmeck requested changes

2017-06-16 15:46 UTC, yesmeck commented on components/form/Form.tsx
> +    onChange?: (value:any)=>void;
whitespace

2017-06-16 15:50 UTC, yesmeck commented
诶，并没有 onChange  哦。

2017-06-16 17:14 UTC, Midqiu commented
https://ant.design/components/form-cn/#components-form-demo-coordinated

2017-06-16 17:15 UTC, Midqiu commented
可是你们官网的例子有，我还试过了，确实有……

https://ant.design/components/form-cn/#components-form-demo-coordinated

![image](https://user-images.githubusercontent.com/5728399/27237134-7f6795f2-52fa-11e7-90ba-b0c22812de4a.png)

2017-06-19 02:46 UTC, benjycui commented
那是 Select 的方法。。。

2017-06-19 02:47 UTC, benjycui commented
这类 demo 我更新下吧，如果你还发现有类似的问题，欢迎反馈。

2017-06-19 02:47 UTC, closed without merging