fix dataPicker onOk type definition
ant-design/ant-design pull request #6619
Opened 2017-06-27 02:07 UTC by newraina

onOk 回调里可以接受参数，详见：[rc-calendar](https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L165)

但是 TS 定义里没有反应出来，导致使用时如果在回调里带参数会报错。

2017-06-27 15:19 UTC, BANG88 requested changes

2017-06-27 15:19 UTC, bang88 commented on components/date-picker/index.tsx
> +  onOk?: (selectedTime: moment.Moment) => void;
Please consider make it optional or this will break the following markup
```
onOK={()=>void}
```

2017-06-27 15:19 UTC, bang88 commented on components/date-picker/index.tsx
> +  onOk?: (selectedTime: moment.Moment) => void;
same here.

2017-06-28 02:08 UTC, newraina commented on components/date-picker/index.tsx
> +  onOk?: (selectedTime: moment.Moment) => void;
onOk is a callback function, base on [TS docs/Optional Parameters in Callbacks](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html):

> but there’s no need to make the parameter optional to accomplish this – it’s always legal to provide a callback that accepts fewer arguments.

No need to make `selectedTime` optional, you can try this: [playground](https://www.typescriptlang.org/play/index.html#src=const%20eat%20%3D%20(cb%3A%20(something%3A%20string)%20%3D%3E%20void)%20%3D%3E%20%7B%20%7D%0D%0Aconst%20something%20%3D%20()%20%3D%3E%20%7B%7D%0D%0A%0D%0Aeat(something))

2017-06-28 02:19 UTC, bang88 commented on components/date-picker/index.tsx
> +  onOk?: (selectedTime: moment.Moment) => void;
Yep, a few confusing, but you are right.

2017-06-28 02:19 UTC, BANG88 approved these changes

2017-06-28 02:19 UTC, merged