Translate documentation for Navigation, both Pattern and Guideline
ant-design/ant-design pull request #6911
Opened 2017-07-21 06:02 UTC by zachguo

According to comments [here](https://github.com/ant-design/ant-design/issues/1471#issuecomment-313475226) and [here](https://github.com/ant-design/ant-design/issues/1471#issuecomment-300466860), ping reviewers @choudlet @abenhamdine . Please take a look.

2017-07-21 06:44 UTC, abenhamdine commented
Nice work !
I'm not a native english-speaker, but it reads pretty well.

2017-07-22 08:09 UTC, afc163 commented
@choudlet @abenhamdine

2017-07-23 20:08 UTC, pierreneter requested changes

2017-07-23 20:08 UTC, pierreneter commented on docs/pattern/navigation.en-US.md
> +title:
Just keep the English title

2017-07-23 20:08 UTC, pierreneter commented on docs/spec/navigation.en-US.md
> +title:
And here

2017-07-23 20:09 UTC, pierreneter commented
Related to #6931

2017-07-23 22:46 UTC, zachguo commented
@pierreneter fixed and squashed

2017-07-24 02:31 UTC, benjycui commented on docs/pattern/navigation.en-US.md
> +Broadly speaking, anything telling user where to go and how to get there can be called navigation. We abstract common navigation patterns and provide handy components to helper designers and develope
`任何告知用户他在哪里` is missing.

2017-07-24 02:42 UTC, benjycui commented
👍

2017-07-24 02:51 UTC, yesmeck commented on docs/pattern/navigation.en-US.md
> +Broadly speaking, anything telling user where to go and how to get there can be called navigation. We abstract common navigation patterns and provide handy components to helper designers and develope
helper => help

2017-07-24 04:17 UTC, zachguo commented on docs/pattern/navigation.en-US.md
> +Broadly speaking, anything telling user where to go and how to get there can be called navigation. We abstract common navigation patterns and provide handy components to helper designers and develope
这里的“When using navigation or customizing navigational structures”根据原文翻的，但感觉很chinglish，直接简写成“When using and customizing navigation”如何？

2017-07-24 13:19 UTC, abenhamdine approved these changes

2017-07-24 17:24 UTC, pierreneter approved these changes

2017-07-24 23:45 UTC, merged