Translation pattern form
ant-design/ant-design pull request #6944
Opened 2017-07-24 21:21 UTC by shenlin192

Hello @choudlet @afc163, my translation for the form in pattern is finished. Please have a look if you are free.

2017-07-24 23:53 UTC, pierreneter commented
Related to #6931

2017-07-24 23:58 UTC, pierreneter reviewed
Nice translation

2017-07-24 23:58 UTC, pierreneter commented on docs/pattern/form.en-US.md
> +---
Just keep title of this file's language. `title: Form`

2017-07-24 23:58 UTC, pierreneter commented on docs/pattern/form.zh-CN.md
> +---
And here

2017-07-25 00:20 UTC, zachguo requested changes

2017-07-25 00:20 UTC, zachguo commented on docs/pattern/form.en-US.md
> +A form is an important human machine interface to obtain user information. It's necessary to consider what questions should be asked according to the expected answers.
"作为获取用户输入的重要交互方式，表单也承担将问题和答案进行配对的角色。"
The translation is a bit verbose. Taking first sentence as an example, we can just do 
'As an important interface to obtain user input, form plays a role of matching answers to questions.'

2017-07-25 00:20 UTC, zachguo commented on docs/pattern/form.en-US.md
> +1. Let a user knows exactly what information is required and why he needs to provide this information.
`a user` should be `an user`. I recommend using plural form `users` so you don't need to deal `he/she`.

2017-07-25 00:20 UTC, zachguo commented on docs/pattern/form.en-US.md
> +1. Let a user knows exactly what information is required and why he needs to provide this information.
I would rather make bullet points shorter, something like 
```
1. Make sure users know what is required to enter, and why
...
2. Provide rich context to help users complete the form
...
3. Error-sensitive and fault-tolerant
...
```

2017-07-25 00:20 UTC, zachguo commented on docs/pattern/form.en-US.md
> +1. Let a user knows exactly what information is required and why he needs to provide this information.
I think rest of the translation can also be improved this way, by making it less verbose. However, it's just my personal opinion anyway.

2017-07-25 10:31 UTC, shenlin192 commented on docs/pattern/form.en-US.md
> +1. Let a user knows exactly what information is required and why he needs to provide this information.
Thank you for your professional suggestions!
I will correct them. By the way, `a user` is correct for me.

2017-07-25 10:31 UTC, shenlin192 commented on docs/pattern/form.zh-CN.md
> +---
Thank you pierreneter. I will correct them.

2017-07-25 17:34 UTC, zachguo commented on docs/pattern/form.en-US.md
> +1. Let a user knows exactly what information is required and why he needs to provide this information.
> I will correct them. By the way, `a user` is correct for me.
@shenlin192 You are right! 🤦‍♂️

2017-07-27 09:26 UTC, afc163 commented on docs/pattern/form.zh-CN.md
> -  en-US: Form
```
title: 表单
```

2017-07-27 09:26 UTC, afc163 commented on docs/pattern/form.en-US.md
> +  en-US: Form
```
title: Form
```

2017-07-28 08:41 UTC, shenlin192 commented
I just changed the title of file `docs/pattern/form.zh-CN.md` and `docs/pattern/form.en-US.md` but I don't know why the continuous-integration fails. Is there something I did wrong? If yes, what should I do?

2017-07-29 06:17 UTC, merged