feat: add typescript demo
ant-design/ant-design pull request #7330
Opened 2017-08-25 11:02 UTC by LeezQ

add form typescript demo code

2017-08-29 05:34 UTC, afc163 commented
`components/form/index.zh-US.md`

2017-08-29 05:36 UTC, yesmeck commented on components/form/index.zh-CN.md
> +  }
这个没必要啦，跟 Form 没关系。

2017-08-29 07:56 UTC, LeezQ commented on components/form/index.zh-CN.md
> +  }
ok，我是看到 table 那边有这个 ts的使用例子，我就在这边也加一下了。

2017-08-29 07:58 UTC, yesmeck commented on components/form/index.zh-CN.md
> +  }
我的意思是这个 constructor 没必须要写。

2017-08-30 06:27 UTC, afc163 commented on components/form/index.zh-CN.md
> +  }
@LeezQ

2017-08-31 03:52 UTC, afc163 commented
> You should modify components/form/index.en-US.md too.

2017-08-31 09:24 UTC, yesmeck requested changes

2017-08-31 09:24 UTC, yesmeck commented on components/form/index.zh-CN.md
> +  key: number;
🤔不能访问 `key` 的。

2017-09-01 01:48 UTC, LeezQ reviewed
改成 age

2017-09-01 02:36 UTC, merged