[bugFix]duplicate css properties 'width'
ant-design/ant-design pull request #7698
Opened 2017-09-22 02:47 UTC by LoeiFy

should not set 'width: 80px'

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

2017-09-22 05:34 UTC, afc163 requested changes
I don't see what this for?

2017-09-22 06:17 UTC, LoeiFy commented
@afc163 

`input-number` 组件样式加了一个属性 `width: 80px`，会覆盖原来的 `width: 100%` 属性，这导致一些布局问题，我认为默认应该是 `width: 100%`，如果用户需要自定义可以自行加上 style 设置。

这里有一个我遇到的布局问题例子

![screen-shot-2017-09-22-at-2 10 34-pm](https://user-images.githubusercontent.com/2193211/30731569-c467534c-9f33-11e7-8131-c49cd7f00a3d.jpg)

2017-09-26 14:02 UTC, afc163 commented
由于 InputNumber 的特性，这里给了一个默认宽度。所以它的默认宽度和 Input 会有些不同，这里的确容易造成误解。但是去掉可能造成不兼容改动，故还是保持原样比较好。

感谢 PR~

2017-09-26 14:02 UTC, closed without merging

2018-05-23 01:51 UTC, jzoe commented
在 3.5.2 给InputNumbers设置了width:   @@100%，但还是被默认宽度覆盖了。 @afc163 

![image](https://user-images.githubusercontent.com/11612990/40399183-791ae098-5e6e-11e8-92ce-ac470441307c.png)

![image](https://user-images.githubusercontent.com/11612990/40399227-beb3e3a2-5e6e-11e8-89c6-aa9cae6f02ae.png)

2018-05-23 02:54 UTC, afc163 commented
@jzoe 来 pull request