table size padding use @table-padding-vertical & @table-padding-horiz…
ant-design/ant-design pull request #9106
Opened 2018-01-24 08:59 UTC by ryanhoho

…ontal (#8805)

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

2018-01-26 09:31 UTC, yesmeck requested changes

2018-01-26 09:31 UTC, yesmeck commented on components/tabs/style/card-style.less
> +  &&-card&-bottom > &-bar &-tab {
Plz open a separate PR.

2018-01-29 08:02 UTC, ryanhoho commented on components/tabs/style/card-style.less
> +  &&-card&-bottom > &-bar &-tab {
不小心把后面的commit带过来了，当前这个pr需要关闭重新来嘛？

2018-01-29 08:03 UTC, yesmeck commented on components/tabs/style/card-style.less
> +  &&-card&-bottom > &-bar &-tab {
不用，继续在这个分支上改就可以了。

2018-01-29 08:13 UTC, ryanhoho commented on components/tabs/style/card-style.less
> +  &&-card&-bottom > &-bar &-tab {
我把这个分支reset了，只剩下一个commit，现在这样吧。

2018-01-30 03:05 UTC, merged